outline/outline

package.json
yarn.lock

requestAnimationFrame polyfill for react tests

---

app/scenes/CollectionEdit/CollectionEdit.js
app/scenes/Document/Document.js
app/scenes/Document/components/SaveAction/SaveAction.js

Apparently we forgot to reset this at some point…

Fixes "Saving…" UI hanging

---

app/scenes/Document/Document.js

Set active document after save

---

server/pages/components/Hero.js

closes https://github.com/outline/outline/issues/435

Max hero height

---

package.json
yarn.lock

Unhandled case in `slate-md-serializer`, great find!

Closes #440

---

server/pages/Home.js
server/pages/components/Layout.js
server/pages/components/Navigation.js
server/utils/routeHelpers.js

Smaller home page fixes with mentions of a wiki

Small homepage improvements

---

app/components/SlackAuthLink/SlackAuthLink.js
app/scenes/SlackAuth/SlackAuth.js
app/stores/AuthStore.js
app/utils/routeHelpers.js
server/routes.js
shared/utils/routeHelpers.js
webpack.config.js

Visit `/auth/slack/install` to trigger install redirect
closes https://github.com/outline/outline/issues/433

Slack direct install flow

---

server/api/hooks.js

Added no results text for Slack slash command

---

app/index.js

I do believe this is the final fix for https://github.com/outline/outline/issues/384

Fixed: Possible cause of logout loop

---

app/components/DocumentPreview/DocumentPreview.js
app/components/Highlight/Highlight.js
app/components/Highlight/index.js
package.json
yarn.lock

Little quick win, adds highlighting to search results (as mocked) and a new component we can use for highlighting any text string.
---

Add highlighting to search results

---

README.md

Just spotted on their repo, couldn't resist.

Add prettier badge

---

package.json
server/pages/Home.js
server/pages/components/Hero.js
server/pages/components/Layout.js
server/pages/components/Navigation.js
yarn.lock

For now I just removed few not so important links from the footer and tweaked layout for mobile. Opted to use `styled-components-breakpoints` which the grid uses as well

Public page CSS tweaks

---

app/index.js
app/stores/AuthStore.js
app/utils/ApiClient.js
server/api/auth.js
server/pages/Api.js

Request auth on first load with existing token

---

app/components/Actions/Actions.js
app/components/DropdownMenu/DropdownMenu.js
app/components/Editor/Editor.js
app/components/Editor/components/Contents.js
app/components/Editor/components/Toolbar/BlockToolbar.js
app/components/Editor/components/Toolbar/Toolbar.js
app/components/Layout/Layout.js
app/components/Sidebar/Sidebar.js
app/menus/DocumentMenu.js

Added ability to print a document

---

server/models/Document.js

Fixes #467. Tested with local data

Fixed search ordering

---

app/scenes/Search/Search.js
app/stores/DocumentsStore.js
app/types/index.js
package.json
server/api/documents.js
yarn.lock

- Paginate search results
- Hide "no results" when starting writing (before debounce)
- Other tiny tweaks
Fixes #465

Search improvements

---

Dockerfile
Makefile
docker-compose.yml

start local development with one command! (`make up`)
commands: 
* `make up` start all required services and run migrations
* `make build` rebuild docker image
* `make destroy` stop and remove all containers

support local development with docker

---

server/models/Collection.js
server/redis.js

Had to promisify this myself, the implementation in redis lock fails with koa, no idea why https://www.npmjs.com/package/redis-lock#use-with-promises-and-asyncawait
Fixes #82

Lock collection navigation tree changes

---

server/pages/Privacy.js
server/pages/components/Content.js
server/routes.js
shared/styles/base.js

Added privacy policy

---

app/components/Auth.js
app/index.js

Also pulled the `Auth` component out into it's own file for legibility, that index.js is getting big.
Closes #480

Fixes exception visiting doc unauthenticated

---

app/models/Document.js
app/scenes/Document/Document.js
app/stores/DocumentsStore.js

Continues from https://github.com/outline/outline/pull/495
Closes https://github.com/outline/outline/issues/493
Closes https://github.com/outline/outline/issues/494

Seamless new doc save

---

package.json
yarn.lock

Improved handling of malformed urls.

---

server/models/Collection.js
server/models/Team.js
server/utils/onboarding.js

Opening this for ideas and discussion
Fixes #420

Improved onboarding

---

app/components/Icon/UserIcon.js
app/components/Sidebar/Settings.js
app/index.js
app/scenes/Settings/Members.js
app/stores/SettingsStore.js

Left this pretty bare as I didn't want to waste time on invites or admin stuff as it doesn't matter for launch. Would need an icon tho

Team members frontend

---

server/pages/About.js
server/pages/components/Content.js
shared/styles/base.js

Mostly fixing grammar, some small design tweaks. I also wanted to remove the explicit mention of it being a side project which I think is a negative and instead emphasis open source - which is positive 😄 
**NOTE**: base is your branch to make diffing easier.

About page

---

app/scenes/Settings/Members.js
app/stores/SettingsStore.js

Fixed UI issue and also reversed order (oldest at the top now)

Fixes to members

---

circle.yml
package.json
server/pages/components/Layout.js
server/utils/prefetchTags.js
webpack.config.dev.js
webpack.config.prod.js
yarn.lock

More prefetch tags and nicer reading webpack confif

Added link=“prefetch” tags

---

app/components/Editor/components/Contents.js
app/components/Editor/components/Heading.js
app/components/Editor/headingToSlug.js

closes https://github.com/outline/outline/issues/510

Stable heading IDs

---

package.json
yarn.lock

Moved webpack manifest plugin to prod dep (failing builds)

Updates editor dependencies

---

app/scenes/Document/Document.js

We don't want errors in the editor to make the entire document fail.

Remove Document error boundary

---

Makefile
server/api/hooks.js
server/api/hooks.test.js

Split results into individual attachments

Fixes 400 error response from slack hook

---

app/stores/DocumentsStore.js
server/models/Collection.js

Delete collection documents with it. Also fixed content on dashboard.

Fixed collection deletion

---

app/components/Auth.js
app/stores/CollectionsStore.js
app/stores/CollectionsStore.test.js
app/stores/DocumentsStore.js

I think this is the pragmatic solution for now but feel free to push back if you don't agree @jorilallo 😄 
Also renamed `fetchAll`, to the more accurate `fetchPage`.
closes https://github.com/outline/outline/issues/560

Increase collections pagination limit

---

app/components/Editor/components/Code.js

Fix code overflow. Fixes #563

---

server/api/documents.js
server/api/documents.test.js
server/migrations/20180207075429-rename-collection-atlasid.js
server/models/Collection.js
server/models/Collection.test.js
server/models/Document.js
server/presenters/document.js
server/test/support.js

Finally renamed this legacy field name
fixes #530

Renamed Document#atlasId finally

---

server/api/documents.js
server/api/documents.test.js
server/migrations/20180207075429-rename-collection-atlasid.js
server/models/Collection.js
server/models/Collection.test.js
server/models/Document.js
server/presenters/document.js
server/test/support.js

Revert "Renamed Document#atlasId finally"

---

server/api/documents.test.js
server/models/Collection.js
server/pages/Api.js
server/presenters/collection.js

Left the old implementation so that we can move into using it later.
Fixes #517

Order document structure alphabetically

---

.github/config.yml
.github/no-response.yml
.github/stale.yml

I added 5 bots to help us manage the project, together they'll mark issues as stale, or more information required, close old issues that aren't going to get tackled and welcome new contributors. WIP also stops branches from being merged that have WIP in the title.
---

Added Probot Config

---

circle.yml
package.json
server/index.js
yarn.lock

This should reduce Bugsnag noise

Catch server errors with koa-onerror

---

server/api/__snapshots__/documents.test.js.snap
server/api/documents.js
server/api/documents.test.js
server/api/hooks.js
server/api/middlewares/authentication.js
server/api/middlewares/pagination.js
server/emails/index.js
server/errors.js
server/routes.js
server/slack.js

Final removal of direct `BadRequest` calls so that all our errors return a valid error id.
Also closes https://github.com/outline/outline/issues/592 (again) – apparently we left in a server side restriction.

Validation Improvements

---

app/components/DropdownMenu/DropdownMenu.js
app/components/DropdownMenu/DropdownMenuItem.js
app/menus/AccountMenu.js
shared/utils/routeHelpers.js

Added some more items to the menu as I noticed we don't make it easy for folks to report bugs etc that they find if they don't come through GitHub… looks decent I think?
closes https://github.com/outline/outline/issues/605

Menu Improvements

---

app/components/Editor/components/ClickablePadding.js

Increase padding at the bottom of the editable area

---

app/components/Editor/components/Toolbar/components/LinkToolbar.js

- ESC now closes the toolbar and forgets any changes you made
- Closing the toolbar by clicking outside still saves changes
- Link is correctly cleared if left empty (behaviour was not consistent before)
closes #623

Improves behavior of link toolbar

---

app/stores/CacheStore.js

New document spacing is incompatible with old. Bumping cache version

Bump cache version

---

server/pages/Home.js

Promo slack on homepage

---

app/components/Scrollable/Scrollable.js
app/components/Sidebar/Main.js
app/components/Sidebar/Settings.js
app/components/Sidebar/components/HeaderBlock.js
package.json
yarn.lock

- Adds shadow when scrolled
- Adds dropdown icon
closes https://github.com/outline/outline/issues/627

Clarify account dropdown

---

app/components/Sidebar/components/SidebarLink.js
app/models/Collection.js
app/models/Document.js
app/scenes/Document/Document.js
app/scenes/Document/components/Actions.js
app/utils/importFile.js
server/api/documents.js
server/api/documents.test.js
server/models/Document.js
server/pages/Api.js

closes https://github.com/outline/outline/issues/612

Autosave Documents

---

package.json
shared/utils/parseTitle.js
shared/utils/parseTitle.test.js

Updated parseTitle to remove escape characters

---

server/auth/google.js
server/auth/slack.js
server/index.js
server/middlewares/authentication.js
server/migrations/20180604182823-user-tracking.js
server/models/User.js

Not quite ready yet, need to use `X-Forwarded-For` for this to work in production.

Track recently active and signin times

---

app/menus/AccountMenu.js
app/menus/DocumentMenu.js
app/menus/ShareMenu.js
app/models/Document.js
app/stores/DocumentsStore.js
server/pages/Changelog.js

Definitely felt this pushing on #658 again - it would be cleaner and easier to follow the code if models contained a reference to their store rather than using the event emitter system.
Closes #669 
Related #44

Duplicate Document

---

app/models/Document.js
app/scenes/Document/Document.js
app/scenes/Error404.js
app/scenes/Error404/index.js
app/scenes/ErrorOffline.js
app/scenes/Search/Search.js
app/stores/DocumentsStore.js
app/utils/ApiClient.js

- Tidied ApiClient to use async/await style
- response.json can't be used in error handling
- Added Offline error state
- Removed some unneeded toast warnings
Closes #331

Improved offline handling

---

app/models/Document.js
app/scenes/Settings/components/SlackButton.js
app/stores/DocumentsStore.js

Fixes initial draft save issue

---

app/scenes/Dashboard/Dashboard.js

Show the collection name in Dashboard

`showCollection` option in Dashboard documents list

---

app/components/ClickablePadding.js
app/scenes/Document/Document.js
app/scenes/Document/components/Editor.js
package.json
yarn.lock

Restores functionality removed from the rich-markdown-editor module version 2.

Upgrade to RME 2

---

server/auth/slack.js
server/middlewares/authentication.js

Allow Slack integration setup for Google Auth accounts

---

server/models/Integration.js
server/services/slack/index.js

Let other team members know what Outline is and what to expect when a Slack channel is connected.
---
closes #735

Adds a new Slack message when connecting a channel for posting

---

server/api/documents.js
server/api/documents.test.js
server/migrations/20180808061353-cleanup.js
server/models/Collection.js
server/models/Collection.test.js
server/models/Document.js
server/models/Event.js
server/presenters/document.js
server/services/slack/index.js
server/test/factories.js
server/test/support.js

It's time, but we reverted this last time. https://github.com/outline/outline/pull/573/files

Migrate atlasId -> collectionId

---

app/models/Collection.js
app/models/Document.js
app/scenes/Document/Document.js
app/scenes/Document/components/Editor.js
app/scenes/Document/components/Header.js
package.json
yarn.lock

Update to rich-markdown-editor 5.0

---

app/scenes/Settings/Notifications.js
server/api/notificationSettings.js
server/emails/CollectionNotificationEmail.js
server/emails/DocumentNotificationEmail.js
server/emails/components/Footer.js
server/models/NotificationSetting.js
server/models/Revision.js
server/models/User.js
server/services/notifications.js

Added: Unsubscribe option to notification email footers
Added: Two new notification types (emails not written yet)
Fixes: Validation added to notification setting event types
Fixes: Collection creation notification email
Fixes: NotificationSetting records should be deleted with the user

Unsubscribe links and email fixes

---

server/api/documents.test.js
server/models/Document.js

Adds wildcard matching to the end of search, nothing too fancy but this should improve the quality of search results.
closes https://github.com/outline/outline/issues/830

Improve partial word matching

---

app/components/Actions.js
app/components/Collaborators.js
app/models/Document.js
app/models/View.js
app/scenes/Document/Document.js
app/stores/DocumentsStore.js
app/stores/RootStore.js
app/stores/ViewsStore.js
server/api/documents.js
server/api/views.js
server/api/views.test.js
server/pages/developers/Api.js
server/presenters/document.js
server/presenters/view.js

closes https://github.com/outline/outline/issues/837

Display document views

---

app/scenes/Document/components/plugins.js
package.json
yarn.lock

closes https://github.com/outline/outline/issues/726

Fixes: Multiline blockquotes collapse

---

app/components/Checkbox.js
app/scenes/Search/Search.js
server/api/documents.js
server/api/documents.test.js
server/models/Document.js
server/pages/developers/Api.js

https://github.com/outline/outline/issues/857 (1 of 4)

Search archived documents

---

app/components/Button.js
app/components/Checkbox.js
app/components/DropdownMenu/DropdownMenu.js
app/components/Empty.js
app/routes.js
app/scenes/Search/Search.js
app/scenes/Search/components/CollectionFilter.js
app/scenes/Search/components/DateFilter.js
app/scenes/Search/components/FilterOption.js
app/scenes/Search/components/FilterOptions.js
app/scenes/Search/components/StatusFilter.js
app/scenes/Search/components/UserFilter.js
app/stores/DocumentsStore.js
package.json
server/api/documents.js
server/api/documents.test.js
server/middlewares/validation.js
server/migrations/20190423051708-add-search-indexes.js
server/models/Document.js
server/pages/developers/Api.js
shared/components/Time.js
shared/styles/theme.js
yarn.lock

closes https://github.com/outline/outline/issues/857

Improved search filtering

---

.env.sample
package.json
server/api/users.js
server/utils/s3.js
yarn.lock

Fix: https://github.com/outline/outline/issues/759

Fix: Now supports AWS signature version 4.

---

.env.sample
README.md

Ran into a few snags when trying to set this project up. Made a couple of changes to help the next person.

fix up the readme and sample .env to smooth out first dev experience

---

app/models/Document.js
app/scenes/Document/Document.js
app/scenes/Document/components/Header.js
server/api/documents.js

- removed some overly complex state from document model
- decoupled dirty and empty from document component state
- made publish state explicit
- allow creation of doc to have no title in api

fix: refactor document dirty and empty logic

---

app/components/Actions.js
app/components/Button.js
app/components/Collaborators.js
app/components/DropdownMenu/DropdownMenu.js
app/components/Sidebar/components/CollectionLink.js
app/components/Sidebar/components/Collections.js
app/components/Sidebar/components/DocumentLink.js
app/components/Sidebar/components/SidebarLink.js
app/menus/CollectionMenu.js
app/menus/DocumentMenu.js
app/menus/NewDocumentMenu.js
app/scenes/Collection.js
app/scenes/Dashboard.js
app/scenes/Document/components/Header.js
app/scenes/Drafts.js
app/scenes/Starred.js
app/scenes/UserProfile.js
shared/styles/theme.js

feat: document menu available in sidebar

---

app/menus/DocumentMenu.js
server/api/documents.js
server/api/documents.test.js

feat: sharing drafts

---

server/api/collections.js
server/api/collections.test.js
server/logistics.js
server/pages/developers/Api.js

closes https://github.com/outline/outline/issues/997

feat: Allow export of collections as sync zip

---

app/components/Sidebar/Main.js
app/components/Sidebar/Settings.js
app/models/Policy.js
app/stores/AuthStore.js
app/stores/BaseStore.js
app/stores/DocumentsStore.js
app/stores/PoliciesStore.js
app/stores/RootStore.js
app/stores/UsersStore.js
server/api/auth.js
server/api/collections.js
server/api/collections.test.js
server/api/documents.js
server/api/team.js
server/policies/document.js
server/policies/index.js
server/policies/index.test.js
server/policies/team.js
server/presenters/index.js
server/presenters/policy.js

closes https://github.com/outline/outline/issues/989

refactor: Policies Architecture

---

.env.sample
server/app.js

To solve the infinity redirect chain issue( #1041 )
https://github.com/outline/outline/issues/1041

chore: add env parameter for enforce https

---

app/components/DropdownMenu/DropdownMenu.js
app/components/Sidebar/components/CollectionLink.js
app/components/Sidebar/components/DocumentLink.js
app/scenes/Search/components/FilterOptions.js

completes #981 
still WIP, please see the comments on the files (I was gonna open it as a draft PR but forgot so just tagged it with WIP, soz)

fix: Ensure menus are always kept on the screen

---

app/components/Sidebar/Main.js
app/components/Sidebar/components/SidebarLink.js
app/components/SocketProvider.js
app/menus/DocumentMenu.js
app/models/Document.js
app/routes.js
app/scenes/Document/Document.js
app/scenes/DocumentDelete.js
app/scenes/Trash.js
app/stores/DocumentsStore.js
package.json
server/api/documents.js
server/api/index.js
server/api/utils.js
server/api/utils.test.js
server/migrations/20191118023010-cascade-delete.js
server/models/Document.js
server/models/Event.js
server/policies/document.js
yarn.lock

Adds a "Trash" menu item that shows items deleted in the last month, offers the ability to restore during this time period before permanent deletion.
closes https://github.com/outline/outline/issues/808
related https://github.com/outline/outline/issues/1010

feat: Trash

---

app/components/Editor/Editor.js
app/menus/DocumentMenu.js
app/menus/NewChildDocumentMenu.js
app/models/Document.js
app/scenes/Document/Document.js
app/scenes/Document/components/Editor.js
app/scenes/Document/components/References.js
app/scenes/DocumentDelete.js
server/pages/developers/Api.js

fix: Move references spacing directly below content

---

app/components/Modal.js
app/scenes/CollectionMembers/components/MemberListItem.js
app/scenes/CollectionMembers/components/UserListItem.js
app/scenes/Invite.js
app/scenes/Settings/components/UserListItem.js
app/stores/UsersStore.js
server/api/users.js
server/commands/userInviter.js

- Fixes unresponsive invite modal
- Fixes invited users should be immediately available in list to add to collections
- Clearly mark invited users in collection members list
closes #1115

fix: Invite modal unresponsive in collection members context

---

server/auth/google.js
server/auth/slack.js

Fixes auth queries to correctly find existing users.
closes #1116

fix: User records not written correctly on signin

---

app/scenes/Search/Search.js
server/api/documents.js
server/api/documents.test.js
server/models/Document.js
server/pages/developers/Api.js

fix: Drafts appear in document insert search

---

app/components/Input.js
app/components/InputSearch.js
app/scenes/Collection.js
app/scenes/Dashboard.js
app/scenes/Drafts.js
app/scenes/Search/Search.js
app/scenes/Search/components/SearchField.js
app/scenes/Starred.js
app/utils/routeHelpers.js

feat: Add search input to collection and home

---

server/api/views.js
server/api/views.test.js

feat: Return view model from views.create

---

app/components/PaginatedDocumentList.js
app/components/PaginatedList.js
app/scenes/Drafts.js
app/scenes/Starred.js

- Use progressive rendering on `PaginatedList` component
- Move drafts, starred, `PaginatedDocumentList` views to use `PaginatedList`
closes #1151

perf: Use progressive rendering on PaginatedList component

---

app/components/Editor/Editor.js

fix: Use alternative redirect method

---

server/api/collections.js
server/api/collections.test.js

fix: Newly created private collections do not return correct policies

---

app/scenes/Settings/People.js

fix: Pagination of people list items

---

app/components/Input.js
app/components/InputSearch.js
app/components/Modal.js
app/components/Sidebar/Sidebar.js
shared/styles/theme.js

Stacking up to 3 levels. Also fixes various mobile styling/layout issues
Related to https://github.com/outline/outline/pull/1102 – this PR introduces even more modal nesting than we've had before, it's quite valuable to have a clue as to where you are in the stack.

feat: Adds visual stacking to nested modals

---

app/menus/DocumentMenu.js
app/scenes/Document/components/Document.js
app/scenes/Document/components/Header.js
server/policies/document.js

fix: "Publish" item is disabled when it shouldn't be
closes #1191

fix: Nested document menu item appears where it shouldn't

---

app/embeds/GoogleDocs.test.js
app/embeds/GoogleSheets.test.js
app/embeds/GoogleSlides.js
app/embeds/GoogleSlides.test.js

Update slides to only embed pub links

test: Google embeds

---

LICENSE

BSL is a new alternative to Closed Source or Open Core licensing models. Under BSL, the source code is always freely available and it is guaranteed to become Open Source at a certain point in time (i.e., the Change Date). Usage below a specific level in the BSL is always completely free.
We are adopting this license to protect against third parties running competing hosted versions of the Outline service and ensure we can maintain a sustainable business to support the project. It will always remain possible to freely run an internal instance of Outline within your own company.

chore: Adopt BSL 1.1 license

---

server/api/collections.js
server/api/groups.js
server/pages/developers/Api.js

fix: Remove useless permission query param
closes https://github.com/outline/outline/issues/1210

docs: Add documentation for groups API endpoints

---

shared/components/Time.js

Fixes https://github.com/outline/outline/issues/1126
My biggest concern here is the `setInterval` at the global level: once started, it will not stop until the app stops. That seems bad, but I'm not sure if it's actually that bad in practice.

fix: Update all Time components each second

---

server/api/attachments.js
server/api/users.js
server/api/utils.js
server/migrations/20200328175012-cascade-delete.js
server/models/Attachment.js
server/utils/s3.js

fix: Cleanup S3 Attachments

---

README.md

Just went through the process of getting a new dev env set up and ran into a couple of minor stumbles. Tried to clear them up in readme

docs: minor ergonomic updates to readme

---

.env.sample

closes https://github.com/outline/outline/issues/1219

docs: make the team logo a little friendlier for first timers

---

server/services/backlinks.js
server/services/backlinks.test.js

Account for deleted documents and no previous revision

fix: Minor fixes in backlinks service

---

.env.sample
Makefile
README.md
docker-compose.yml

You may have to update your `.env` to point to localhost as in the sample changes, but other than that it should "just work".
One of the points raised in this discussion thread:
https://github.com/outline/outline/discussions/1269

chore: Improve performance in dev by running Node/Yarn outside of docker

---

app/components/DropdownMenu/DropdownMenu.js
app/components/DropdownMenu/DropdownMenuItem.js
app/components/Theme.js
app/menus/AccountMenu.js
app/stores/UiStore.js

I do a lot of work in Outline in the evenings, it's nice not to have to toggle the theme all the time 😆 
closes #1275

feat: System theme preference

---

app/scenes/Document/components/DataLoader.js
app/utils/ApiClient.js
app/utils/errors.js
package.json
server/app.js
server/static/index.html
yarn.lock

Reducing noise in error reporting by ignoring expected error cases and defining error classes.

feat: Improved error filtering and reporting

---

app/components/Sidebar/components/Collections.js
app/components/Sidebar/components/CollectionsLoading.js

Quick task to reduce the jank in the sidebar as the page loads using a skeletal loader.

chore: Reduce loading jank in sidebar

---

app/scenes/Settings/People.js
app/stores/UsersStore.js
server/api/users.js
server/api/users.test.js

fix: Suspended users showing in group and collection member management

---

app/scenes/Document/components/DataLoader.js
app/scenes/Document/components/Document.js
package.json
yarn.lock

closes https://github.com/outline/outline/issues/1159

feat: Add ability to create docs from link editor

---

app/components/Layout.js
app/components/PageTitle.js

Is everything right? 
If I am forgetting something please notify me to make it suitable

feat: Head tag title based on TeamName

---

app/components/Button.js
app/components/Editor/Editor.js
app/components/NudeButton.js
app/components/Sidebar/components/Version.js
app/embeds/components/Frame.js
app/scenes/Document/components/Contents.js
package.json
yarn.lock

Upgrade flow just far enough to remove a bunch of these ignore comments

chore: Update flow just far enough to get hooks libdefs

---

app/components/ScrollToTop.js
app/scenes/UserDelete.js
server/api/documents.js
server/models/Document.js
server/policies/document.js
shared/utils/domains.js

For reference: https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines

fix: common misspelling errors

---

.env.sample
app.json
app/components/SocketProvider.js
index.js
server/env.js
server/index.js
server/services/websockets.js

View with whitespace diff enabled
closes #1381

chore: Remove WEBSOCKETS_ENABLED flag

---

app/components/Editor.js
app/components/Input.js
app/components/Switch.js
app/components/Tooltip.js
app/menus/DocumentMenu.js
app/models/Document.js
app/models/Event.js
app/models/Share.js
app/scenes/Document/components/DataLoader.js
app/scenes/Document/components/Header.js
app/scenes/DocumentShare.js
app/scenes/Settings/Shares.js
app/scenes/Settings/components/EventListItem.js
app/stores/SharesStore.js
package.json
server/api/__snapshots__/shares.test.js.snap
server/api/documents.js
server/api/shares.js
server/api/shares.test.js
server/middlewares/validation.js
server/migrations/20200723055414-add-published-to-shares.js
server/models/Event.js
server/models/Share.js
server/policies/share.js
server/presenters/share.js
server/test/factories.js
shared/styles/globals.js
shared/styles/theme.js
yarn.lock

feat: Sharing improvements

---

app/models/Collection.js
server/api/collections.js
server/api/collections.test.js
server/api/documents.js
server/migrations/20200812170227-remove-collection-type.js
server/models/Collection.js
server/models/Document.js
server/models/Team.js
server/presenters/collection.js
server/test/factories.js
server/test/support.js

Remove unused collection column to reduce confusion and cleanup techdebt.
closes #1314

chore: Remove all usage of collection.type

---

app/scenes/Document/components/DataLoader.js

fix: Unnecessary shares.info request when loading public share

---

app/components/CenteredContent.js
app/components/DocumentPreview/DocumentPreview.js
app/components/DropdownMenu/DropdownMenu.js
app/components/LoadingIndicator/LoadingIndicatorBar.js
app/components/Modal.js
app/components/Popover.js
app/components/Sidebar/Sidebar.js
app/components/Tabs.js
app/components/Toasts/Toasts.js
app/scenes/Search/Search.js
app/stores/UiStore.js
shared/styles/theme.js

fix: Mobile style fixes and improvements

---

app/components/SocketProvider.js
app/scenes/Document/components/SocketPresence.js
app/utils/pageVisibility.js

fix: Improve websocket reliability

---

.env.sample
app.json
index.js
server/utils/s3.js

- Introduce AWS_S3_FORCE_PATH_STYLE option to maintain compatibility
- Make AWS_S3_UPLOAD_BUCKET_NAME optional

chore: Remove reliance on s3ForcePathStyle

---

app/scenes/DocumentDelete.js

Nice little UX improvement
closes #1483

fix: Redirect to parent document when deleting a child document

---

server/api/documents.js
server/models/Document.js
server/models/Document.test.js

`lastModifiedById` was not being set correctly in this circumstance. Added an associated model test.
closes #1482

fix: Deleting a document should correctly show who deleted

---

app/components/DocumentHistory/DocumentHistory.js

feat: Add Header to Document History Sidebar

---

app/scenes/Document/components/Document.js
app/scenes/Document/components/Editor.js

fixes: Editing document too wide when TOC visible in read only
closes #1499

fix: Regression with TOC not showing when navigating directly to doc

---

app/scenes/Document/components/Editor.js
package.json
yarn.lock

closes https://github.com/outline/outline/issues/1426

fix: Occasional render loop in editor toolbar

---

app/components/SocketProvider.js
app/scenes/Collection.js
app/scenes/Document/components/DataLoader.js
server/api/documents.js
server/policies/document.js

fixes https://github.com/outline/outline/issues/1095

fix: Improved handling of delete events from collection and document sockets

---

package.json
yarn.lock

chore: Upgrade Sentry to Latest Version

---

app/components/Button.js
app/components/DocumentPreview/DocumentPreview.js
app/components/DropdownMenu/DropdownMenuItem.js
app/components/NudeButton.js
app/components/Sidebar/components/HeaderBlock.js
app/components/Sidebar/components/SidebarLink.js
app/components/Tab.js
app/components/TeamLogo.js
app/index.js
app/menus/DocumentMenu.js
app/scenes/Document/components/Header.js
app/scenes/Document/components/ReferenceListItem.js
package.json
shared/styles/globals.js
yarn.lock

This small number of changes makes a number of improvements to focus accessibility. Tabbing through the app with the keyboard is improved and clicking on buttons no longer shows the focus ring unnecessarily.

fix: Focus accessibility

---

server/static/index.html

If Sentry is blocked by ad-tracking
closes #1539

fix: put guard around sentry init

---

app/components/Sidebar/components/CollectionLink.js
app/components/Sidebar/components/Collections.js
app/components/Sidebar/components/DocumentLink.js
app/components/Sidebar/components/EditableTitle.js
app/scenes/Document/components/Document.js
package.json

- Enables double click to edit document and collection titles in the sidebar
- Fixes document titles not updating when edited elsewhere
closes #1516

feat: Editable titles in sidebar

---

app/embeds/GoogleDocs.js
app/embeds/GoogleDocs.test.js
app/embeds/GoogleSheets.js
app/embeds/GoogleSheets.test.js
app/embeds/GoogleSlides.js
app/embeds/GoogleSlides.test.js
app/embeds/components/Frame.js
shared/styles/theme.js

Improve styling and added link to originally pasted url.
closes #1530

feat: Allow Google Embeds from regular (non publish-to-web) links

---

server/middlewares/authentication.js
server/types.js
server/utils/jwt.js

Improves flow typing, beginnings of correct `ctx` type.
This PR will integrate with https://github.com/outline/outline/pull/1554 to allow tracking of search queries from API tokens separately from app navigation and slack integration.

feat: Add ctx.state.authType for tracking

---

server/api/documents.js
server/api/documents.test.js
server/api/hooks.js
server/api/hooks.test.js
server/migrations/20200915010511-create-search-queries.js
server/models/Document.js
server/models/Document.test.js
server/models/SearchQuery.js
server/models/index.js

closes #1392
We can add tests later when the logic gets approved.

feat: Record search queries

---

app/scenes/Settings/Slack.js

background changed to props.theme.codeBackground

fix: Dark mode inline code styling fixed #1593

---

app/components/DocumentMetaWithViews.js
app/stores/ViewsStore.js

feat: Show unique views rather than total views in document meta.

---

server/api/notificationSettings.js
server/services/notifications.js

This work took priority as setting up these debounced systems is an enabler for realtime collaboration.
closes #1002

feat: Debounce notification emails by 5 minutes

---

app/scenes/Document/components/DataLoader.js
app/stores/RevisionsStore.js
server/api/documents.js
server/api/documents.test.js
server/api/revisions.test.js
server/events.js
server/models/Document.js
server/models/Document.test.js
server/models/Event.js
server/models/Revision.js
server/models/Revision.test.js
server/services/backlinks.js
server/services/backlinks.test.js
server/services/debouncer.js
server/services/notifications.js
server/services/revisions.js
server/services/revisions.test.js
server/services/slack.js

chore: Debounce revision creation

---

server/api/shares.test.js
server/policies/document.js

closes https://github.com/outline/outline/issues/1636

fix: Update document policy to disable sharing for read-only users

---

app/components/Collaborators.js

This pull request Fixes #1659 . 
Thanks!

fix: Prevent API request for views data for deleted documents

---

server/api/users.js
server/commands/userSuspender.js
server/commands/userSuspender.test.js
server/models/Team.js

Refactor suspend user to use command pattern
closes #1648

fix: Group membership count off after suspending users in groups

---

server/commands/userInviter.js
server/commands/userSuspender.js

fix: One source of transaction deadlock when invites > pg pool

---

server/migrations/20201206210619-update-attachment-cols.js

fix: Migrate attachment columns to increase available length

---

app/components/DropToImport.js
app/components/Layout.js
app/components/Sidebar/components/CollectionLink.js
app/components/Sidebar/components/SidebarLink.js
package.json
yarn.lock

fixes the internal hover state issue!
closes https://github.com/outline/outline/issues/1697

chore: React-Dropzone version bump

---

app/scenes/Settings/components/ImageUpload.js

fixes https://github.com/outline/outline/issues/1710

fix: dropzone error on image upload component

---

server/api/attachments.js
server/api/attachments.test.js

Missing endpoint as requested by customer 💪

feat: attachments.delete

---

server/api/auth.test.js
server/auth/email.js
server/auth/google.js
server/auth/slack.js
server/middlewares/authentication.test.js
server/models/Team.js
server/utils/jwt.js

Allows teams to be soft deleted, prevents any activity or sign-in on the team once marked as deleted.
Related OLN-40
Related #1086

fix: Allow soft deletion of teams

---

server/api/documents.js
server/api/documents.test.js

fix: Attempting to restore document in deleted collection without collectionId override

---

package.json
server/app.js
server/routes.js
server/static/index.html
server/utils/prefetchTags.js
webpack.config.prod.js
yarn.lock

This is something we used to have and was lost a couple of versions back when the marketing site was separated from the application. Lighthouse report told me to do this.

fix: Restore DNS prefetching for static resources

---

app/components/Layout.js
app/components/Sidebar/Sidebar.js
app/components/Sidebar/components/CollapseToggle.js
app/components/Sidebar/components/HeaderBlock.js
app/components/Sidebar/components/ResizeBorder.js
app/components/Sidebar/components/ResizeHandle.js
app/components/Sidebar/components/Section.js
app/components/Sidebar/components/SidebarLink.js
app/components/SkipNavContent.js
app/components/SkipNavLink.js
app/components/TeamLogo.js
app/scenes/Document/components/Header.js
app/stores/UiStore.js
shared/styles/theme.js

closes #753
ticks off a couple of https://github.com/outline/outline/issues/1801
https://user-images.githubusercontent.com/380914/105281303-b06f3c00-5b60-11eb-8a41-c189604dc80e.mp4

feat: Resizable sidebar

---

app/scenes/Login/index.js
app/stores/AuthStore.js

Removes unnecessary API request on authenticated app load
closes #1845

fix: auth.config request should only be made on Login screen

---

server/api/documents.js
server/api/documents.test.js
server/models/Document.js
server/models/Team.js
server/test/support.js

fix: Reassign user on unpublish

---

app/components/Sidebar/components/DocumentLink.js
app/components/Sidebar/components/NavLink.js
app/components/Sidebar/components/Section.js
app/components/Sidebar/components/SidebarLink.js
package.json
yarn.lock

When viewing a large knowledge base it's easy to end up on a document that's scrolled outside of the visible area of the sidebar.
Automatically scroll the sidebar to ensure the active item is in view

feat: Scroll to active sidebar item

---

.env.sample
README.md

chore: Improved deployment documentation

---

app/components/Sidebar/Main.js
app/scenes/Settings/People.js
server/api/users.js
server/api/users.test.js

- fix: Removes UI control from people settings
- fix: Avoids rendering React tree's for unused modals
- fix: Checks authorization on backend for this change \w test
closes #1902

fix: Disable 'Invite people…' for non-admins

---

server/mailer.js
server/test/helper.js

- Prevents creation of test mailer account
- Avoids duplicate migrations

chore: Test performance and warnings

---

app/components/Checkbox.js
app/components/Input.js
app/scenes/Document/components/Document.js
app/scenes/Settings/components/SlackButton.js
app/stores/AuthStore.js
server/middlewares/validation.js
server/models/Document.js
server/models/User.js
server/utils/jwt.js

A number of fixes were made over time that never made it back to this OSS repo for some reason or another, this PR syncs what can be.

chore: Syncs changes that were erroneously made in enterprise repo

---

app/menus/DocumentMenu.js

feat: Add "Import document" menu item to document menu

---

app/components/InputLarge.js

Increased the width of email login input to occupy the empty spcae.
fixes #1932

stretch email login input

---

app/scenes/Document/components/Document.js
app/scenes/Document/components/Editor.js

fix: Alignment of backlinks and references

---

app/components/Button.js
app/components/Sidebar/Sidebar.js
app/components/Theme.js
app/index.js
package.json
server/app.js
webpack.config.dev.js
yarn.lock

Works beautifully in my testing, and fast too~
closes #2021

chore: Enable HMR for frontend code

---

server/commands/userCreator.js
server/commands/userCreator.test.js
server/models/User.js
server/models/User.test.js

fix: Improved handling of authentication edge-cases

---

webpack.config.dev.js

Attempting to fix sporadic memory issues that appeared in CI after merging HMR: https://github.com/outline/outline/commit/cdc7f61fa1dcc72e10fafa4de18b5cada810cd86

fix: Remove HMR in test env

---

server/api/users.js
server/api/users.test.js
server/commands/userDestroyer.js
server/commands/userDestroyer.test.js
server/models/User.js

- Move to using command pattern
- Remove exception for last user in org
- Tests, tests, tests
closes #2053

fix: Correctly guard against last admin deleting their account

---

server/api/hooks.js
server/api/hooks.test.js
server/auth/providers/slack.js
server/models/Integration.js
server/models/IntegrationAuthentication.js
server/models/index.js
server/test/factories.js

chore: Rename `Authentication` -> `IntegrationAuthentication`

---

app/menus/AccountMenu.js

Changes:
=====
- Added onClick event listener to show Appearance Menu options in mobile

fix: Added onClick event listener to show Appearance Menu options in mobile

---

server/models/Collection.js

fix: Cannot read property 'collectionGroupMemberships' of null

---

app/stores/DocumentsStore.js

fix: Remove application/octet-stream as valid frontend mimetype

---

package.json
server/auth/providers/email.js
server/commands/accountProvisioner.js
server/commands/accountProvisioner.test.js
server/commands/userCreator.js
server/commands/userCreator.test.js
server/models/User.js
yarn.lock

Noticed this issue while testing the nodemailer bump.

fix: Welcome emails should not be sent when inviting a user

---

package.json
yarn.lock

Add support for concatenated modules: https://relative-ci.com/releases/2021-05-may-service-update#support-for-concatenated-modules

chore: Update @relative-ci/agent to v2

---

app/hooks/useMediaQuery.js

fix: window.matchMedia is not a function

---

app/components/Sidebar/components/Collections.js
shared/i18n/locales/en_US/translation.json

fix: Failure loading collections on frontend results in loading loop

---

.env.sample
package.json
server/app.js
yarn.lock

Add "http" to DEBUG env variable to enable.
closes #2174

feat: Add optional http logging in production

---

server/presenters/document.js

Makes you wonder if there are other serialized loading spots that could be easily parallelized 🤔 
closes #2157

fix: Parallelize loading attachments in document presenter

---

README.md

Update the documentation for local development.
#2165

documentation: Instructions for local development

---

app/components/InputSelect.js

This should fix https://github.com/outline/outline/issues/2015.
Please check with a Mac and leave a comment if it works.

style: add option background for InputSelect

---

server/app.test.js
server/routes.js
server/static/index.html
server/test/factories.js

feat: Return publicly shared document title in SSR HTML

---

server/api/collections.test.js
server/policies/collection.js
server/policies/collection.test.js

fix: Remove export permission for read-only users

---

package.json
server/main.js
server/utils/metrics.js
yarn.lock

Add tracking of additional metrics to DataDog, if enabled.

feat: DataDog metrics

---

.env.sample
app.json
server/mailer.js

feat: Add TLS ciphers option

---

server/middlewares/passport.js

fix: Server error when user cancels OAuth process with Azure

---

server/api/documents.test.js
server/models/SearchQuery.js

fix: Long search term causes server error writing query to db

---

app/components/DocumentListItem.js
app/components/Sidebar/components/DocumentLink.js
app/components/Sidebar/components/SidebarLink.js
app/scenes/Search/Search.js

fix: Down arrow in search input should move focus to results

---

app/components/LocaleTime.js
shared/i18n/index.js

Requested and translated by contributors :pray:

feat: Enable traditional Chinese translations

---

app/components/ContextMenu/MenuItem.js
package.json
yarn.lock

fix: Clicking dropdown menu items in FF

---

server/models/Collection.js

fix: Improve isChildDocument performance

---

app/scenes/Drafts.js
app/scenes/Search/Search.js
package.json
yarn.lock

fix: Make search query string user friendly

---

app/components/Header.js
app/components/Input.js
app/components/Tabs.js

Addresses issues found in #2289

fix: Various mobile fixes

---

server/api/collections.js
shared/i18n/locales/en_US/translation.json
shared/utils/indexCharacters.js

Index value set to `*space*D` was giving an error.

fix: Add space to the valid index characters list

---

server/commands/revisionCreator.js
server/commands/revisionCreator.test.js
server/models/Event.js
server/models/Revision.js
server/services/revisions.js

Towards https://github.com/outline/outline/issues/2230

feat: Add revisionCreator command

---

server/migrations/20210716162923-events-indexes.js

chore: Add documentId index to events table

---

package.json
yarn.lock

related https://github.com/outline/rich-markdown-editor/pull/492
closes #1338

feat: Add support for collapsible headings

---

app/components/LocaleTime.js
shared/i18n/index.js

feat: Enable Persian language translations

---

app/stores/AuthStore.js
app/stores/RootStore.js

…by caching team policy in localStorage
closes #2346

chore: Improve perf of new tab loading 

---

app/components/DocumentMeta.js
app/menus/TemplatesMenu.js
app/scenes/Document/components/Document.js
app/scenes/Document/components/Editor.js
app/scenes/Document/components/Header.js
server/policies/document.js

closes #2204
closes #2355
closes #2354
closes #2360

fix: Various editor header and metadata fixes

---

app/components/Sidebar/components/EditableTitle.js

fix: Editing title in sidebar allows removal of title 

---

.env.sample
package.json
server/index.js
server/main.js
server/sequelize.js
yarn.lock

Fork node process to use all available CPU cores by default, or allow override with semi-standardized `WEB_CONCURRENCY` env variable.
closes #2306

feat: Web concurrency

---

server/utils/avatars.js
server/utils/avatars.test.js
server/utils/s3.js
shared/i18n/locales/en_US/translation.json

fix: Error uploading fallback avatar when name contains characters that need to be escaped

---

shared/theme.js

chore: Tone down notices

---

server/auth/providers/google.js

fix: Enable offline access to google accounts

---

server/models/Document.js

Move from a LEFT OUTER JOIN to a separate query

perf: Separate slow joins

---

server/models/Team.js
server/onboarding/Getting Started.md
server/onboarding/Our Editor.md
server/onboarding/Support.md
server/onboarding/What is Outline.md

- Remove support document (support is easy to find and we don't want to mention bugs in the first moments of user experience)
- Remove confusing images (The images of the editor UI are confusing within the editor itself)
- Added onboarding checklist
---

chore: Add new 'getting started' onboarding document

---

app/scenes/Settings/Security.js

fix: Settings on 'Security' tab not persisting correctly after refactor

---

app/components/DocumentListItem.js
app/menus/DocumentMenu.js
app/menus/NewDocumentMenu.js
app/menus/NewTemplateMenu.js
app/scenes/Search/Search.js

fix: Options to create a document is available when the policies of collection in the context doesn't permits the user 

---

app/components/Sidebar/Main.js

fix: Sidebar links highlighting issue when a template is deleted or archived.

---

server/auth/index.js
server/utils/authentication.js

I realised that I was not redirected to the collection when launching the app for the first time 😄

fix: Redirect to collection on self-hosted

---

app/hooks/useSessions.js
app/menus/AccountMenu.js

feat: Add UI to switch teams where signed in to multiple

---

server/api/documents.js

fix: Missing document menu items

---

server/utils/queue.js

chore: Add basic logging of metrics to event queue

---

app/components/Sidebar/components/CollectionLink.js
app/components/Sidebar/components/DocumentLink.js
app/components/Sidebar/components/SidebarLink.js
app/components/Sidebar/components/StarredLink.js

Fixes double highlight when viewing starred docs from starred menu.
closes #2544

fix: Double document highlight in sidebar

---

app/components/Collaborators.js
app/scenes/Document/components/Document.js
app/scenes/Document/components/Header.js
server/collaboration/logger.js
server/collaboration/tracing.js
server/models/Event.js
server/services/collaboration.js
server/services/worker.js

- Remove "Saving…" message when collab enabled
- Add dd-trace metrics
- Slack notifications for edits are off the wall
- "Document reload" toast triggered and would not let other player exit as editor thinks there is a conflict.
related #811

fix: Various fixes for collaborative editing beta

---

server/models/Collection.js
server/routes/auth/index.js
server/routes/auth/index.test.js
server/utils/authentication.js

fix: Forward to incorrect collection url on first signin

---

app/utils/i18n.js
shared/i18n/index.js

fix: Add Polish to language choices

---

package.json
shared/theme.js
yarn.lock

Adds emoji suggest support through editor upgrade
The cost of emojis was always going to be a size bump, at least it isn't in the initial bundle size.

feat: Emoji picker in editor

---

app/scenes/Document/components/Document.js

Increases left gutter size
fixes #2715 
https://www.loom.com/share/42ec56033c9e463285271ed7c479da8a

Fix: increase left gutter spacing on mobile edit mode

---

app/components/Editor.js
package.json
yarn.lock

fix: Various collab cursor issues

---

server/routes/api/documents.js
server/routes/api/documents.test.js

fix: documents.publish event not triggered if nothing else changed in doc

---

app/utils/routeHelpers.js
server/presenters/slackAttachment.js
server/utils/robots.js
shared/embeds/Diagrams.js
shared/embeds/InVision.js

Resolves all issues raised by CodeQL, nothing here seems to be of particular security concern – but two are subtle bugs.

fix: code scanning alerts

---

app/scenes/Document/components/EditableTitle.tsx
app/scenes/Document/components/Editor.tsx

fix: Remove star option on publicly shared docs

---

.dockerignore

fix: Keep tsconfig.json in Docker build

---

Procfile
app.json

- Enhancement: Adding more descriptions for config vars
- Enhancement: Adding more vars to support Azure and OIDC login; adding support to change language
- Fix: Adding `collaboration` in `web` Dyno to fix collaboration in Heroku deployment

fix: Optimizing Heroku deployment: more configs, add collaboration support

---

Dockerfile
README.md

chore: Update Node.js version

---

app/components/Avatar/Avatar.tsx
app/components/Avatar/AvatarWithPresence.tsx
app/components/Collaborators.tsx
app/scenes/Document/components/Editor.tsx
app/scenes/Document/components/Header.tsx
app/scenes/Document/components/MultiplayerEditor.tsx
app/scenes/Document/components/ObservingBanner.tsx
app/stores/UiStore.ts
server/models/User.ts
server/routes/api/__snapshots__/users.test.ts.snap
server/utils/avatars.ts
shared/i18n/locales/en_US/translation.json

Mainly a fun hidden feature, but definitely useful during meetings and other synchronous collaboration sessions

feat: Added ability to click another user to observe them (sync scroll position)

---

app/components/Checkbox.tsx
app/components/Sidebar/components/Toggle.tsx
app/components/Toggle.tsx
app/menus/DocumentMenu.tsx
app/models/Document.ts
app/scenes/Document/components/Contents.tsx
app/scenes/Document/components/Document.tsx
app/scenes/Document/components/Header.tsx
app/scenes/Settings/Features.tsx
app/scenes/Settings/Security.tsx
app/scenes/Settings/components/NotificationListItem.tsx
app/scenes/Settings/components/SlackListItem.tsx
app/stores/DocumentsStore.ts
server/migrations/20211218193004-documents-full-width.js
server/models/Document.ts
server/presenters/document.ts
server/routes/api/documents.ts
shared/i18n/locales/en_US/translation.json

https://user-images.githubusercontent.com/380914/146657164-bcd99e7a-877c-4c7e-9071-a8fd2ae5599e.mov
closes #1479 
closes #2660

feat: Optional full-width toggle for document display

---

app/scenes/Document/components/Document.tsx
app/scenes/Document/components/Header.tsx

Templates menu should be available in a new collaborative editing document
closes #2905

fix: Templates menu does not appear in collab editing

---

README.md

Additional details for using redis or postgres installed outside docker

docs: Update instructions

---

app/editor/components/Styles.ts
shared/editor/nodes/CheckboxItem.ts

fix: Move checkboxes from real inputs to prevent password manager intrusion

---

app/components/RegisterKeyDown.ts
app/hooks/useKeyDown.ts
package.json
yarn.lock

fix: Editor shortcut conflicts

---

app/scenes/Templates.tsx

Interpose a space in the templates scene empty state.

fix: Missing space character

---

app/scenes/CollectionEdit.tsx
server/routes/api/collections.test.ts
server/routes/api/collections.ts
shared/i18n/locales/en_US/translation.json

fix: trim collection name on save rather than on change

---

.env.sample
.gitignore
server/index.ts
server/utils/ssl.ts

feat: Support SSL without reverse proxy

---

app/editor/components/FloatingToolbar.tsx
app/editor/components/SelectionToolbar.tsx
app/editor/components/ToolbarMenu.tsx
app/editor/index.tsx
app/hooks/useComponentSize.ts

fix: Flash of content when selecting text on RHS of document

---

app/components/Sidebar/components/CollectionLink.tsx

#2974
WIP:  Need to confirm this is the correct approach & if new unit tests are appropriate

fix: issue-2974 reparent nested document when dropped on current collection

---

app/scenes/Document/components/DataLoader.tsx

fix: Cannot view history with view-only permissions and collab editing enabled

---

app/components/Sidebar/components/Version.tsx

Discussed  https://github.com/outline/outline/pull/3029#discussion_r795323075

fix: error from api rate limiting

---

app/components/ContextMenu/index.tsx
app/components/Popover.tsx

fixes https://github.com/outline/outline/issues/3011

fix: make mobile popover dialog styling nice

---

app/editor/components/ComponentView.tsx
app/editor/components/Styles.ts
package.json
shared/editor/nodes/Image.tsx
yarn.lock

Unfortunately hacky, but this is something of a requirement when you have inline nodes that sometimes are laid out to look like block nodes.
closes #2854 
closes #3013
supersedes #3014

fix: Improvements to image positioning 

---

app/components/ContextMenu/MenuItem.tsx
app/components/ContextMenu/Template.tsx
app/menus/CollectionGroupMemberMenu.tsx
app/menus/CollectionMenu.tsx
app/menus/DocumentMenu.tsx
app/menus/FileOperationMenu.tsx
app/menus/GroupMemberMenu.tsx
app/menus/GroupMenu.tsx
app/menus/MemberMenu.tsx
app/menus/ShareMenu.tsx
app/menus/UserMenu.tsx
app/types.ts

Also adds some missing menu icons while I was in here
closes #3105

chore: Add danger background to dangerous menu items on hover

---

app/scenes/Collection.tsx
app/scenes/CollectionDelete.tsx
app/scenes/CollectionEdit.tsx

fix: editing collections should not forward to collection on save

---

shared/editor/nodes/Image.tsx

fix: SVGs without a natural px width are invisible

---

app/components/Sidebar/Settings.tsx

chore: Drive settings sidebar from new config

---

app/components/ContentEditable.tsx
app/hooks/useOnScreen.ts
app/hooks/usePageVisibility.ts

fix: Editor title does not autoFocus on first load

---

app/components/Flex.tsx

just using React.CSSProperties to replace types of flex component

refactor: ♻️ Flex type

---

app/components/Analytics.ts
app/components/AuthenticatedLayout.tsx
app/components/Breadcrumb.tsx
app/components/ButtonLink.tsx
app/components/CenteredContent.tsx
app/components/DocumentBreadcrumb.tsx
app/components/ErrorBoundary.tsx
app/components/EventBoundary.tsx
app/components/Guide.tsx
app/components/Labeled.tsx
app/components/Layout.tsx
app/components/Modal.tsx
app/scenes/Settings/components/SettingRow.tsx
server/emails/components/Body.tsx
server/emails/components/Button.tsx
server/emails/components/EmailLayout.tsx
server/emails/components/Heading.tsx

The children property does not need to appear in the custom props type

refactor: ♻️ del children type

---

shared/editor/marks/Bold.ts
shared/editor/marks/Italic.ts
shared/editor/marks/Strikethrough.ts
shared/editor/marks/Underline.ts

Specifically, Google Docs.
closes #3320

fix: Improve paste handler parsing for more cases

---

app/components/Editor.tsx
app/components/HoverPreview.tsx
app/scenes/Document/components/DataLoader.tsx
app/scenes/Document/components/Editor.tsx

fix: Link preview and search should work on collection descriptions

---

app/components/SearchPopover.tsx

- adds "/" keyboard shortcut to focus search input on share screen
- auto-focus content body on search item selection

feat: adds "/" keyboard shortcut to share, focus content body on search selection

---

server/logging/logger.ts
server/logging/tracing.ts
server/queues/index.ts
server/services/worker.ts
server/utils/queue.ts

Noticed that failed events were not retrying as expected

fix: Queue retry behavior

---

server/commands/userCreator.test.ts
server/commands/userCreator.ts
server/routes/auth/providers/azure.ts
server/routes/auth/providers/google.ts
server/routes/auth/providers/oidc.ts

fix: Lowercase email from auth providers to match any outstanding invites

---

app/actions/index.ts

I'm reading the code for this project and can only do simple things at the moment 😅

feat: refactor resolve ♻️

---

app/components/Sidebar/Settings.tsx
app/components/Sidebar/components/Collections.tsx
app/components/Sidebar/components/Header.tsx
app/components/Sidebar/components/SidebarLink.tsx
app/components/Sidebar/components/Starred.tsx
app/hooks/usePersistedState.ts
app/models/Document.ts
app/stores/AuthStore.ts
app/stores/UiStore.ts
app/utils/Storage.ts
shared/editor/nodes/Embed.tsx

Also normalizes `localStorage` access to a `Storage` class.
closes #3001

fix: Embed disabled state should persist

---

app/components/DocumentMeta.tsx

My first (very tiny) PR for Outline project
Trying to fix issue https://github.com/outline/outline/issues/2955

fix : translation strings in DocumentMeta component (2955)

---

shared/i18n/index.ts

This PR includes one fix for type error via non-null assertion operator.

chore: fix i18n type error

---

server/collaboration/PersistenceExtension.ts
server/commands/documentCollaborativeUpdater.ts

fix: Race condition in collaboration document persistence (needed locking transaction)
closes #3427

fix: CRDT creation from markdown state touches document updated timestamp

---

server/models/Document.ts
server/models/Share.ts
server/policies/document.ts
server/routes/api/documents.ts
server/routes/api/shares.ts

perf: Not looping collection documentStructure for unpublish permission calculation

perf: Requesting less db columns when calculating collection permissions

---

server/routes/api/cron.test.ts
server/routes/api/cron.ts
server/routes/api/index.ts

Includes backwards compatability.

chore: utils.gc -> cron.:period

---

shared/editor/lib/textBetween.ts
shared/editor/nodes/Attachment.tsx
shared/editor/nodes/Embed.tsx
shared/editor/nodes/Emoji.tsx
shared/editor/nodes/HardBreak.ts
shared/editor/nodes/Node.ts
shared/editor/packages/basic.ts
shared/editor/plugins/ClipboardTextSerializer.ts
shared/editor/types/index.ts
shared/typings/prosemirror-model.d.ts

Issue received through support.

fix: Emojis and embeds cannot be copied to plain text clipboard

---

app/components/Sidebar/components/DocumentLink.tsx
package.json

Functions (isDragging, isOver, canDrop) always return a boolean value

fix: simplify transformation

---

app/components/DocumentMetaWithViews.tsx
app/components/DocumentTasks.tsx
app/editor/components/EmojiMenu.tsx
app/editor/index.tsx
app/models/Document.ts
app/scenes/Document/components/Document.tsx
app/scenes/Document/components/MultiplayerEditor.tsx
app/scenes/KeyboardShortcuts.tsx
shared/editor/lib/getHeadings.ts
shared/editor/lib/getTasks.ts
shared/editor/lib/headingToSlug.ts

see: https://github.com/outline/outline/issues/3325#issuecomment-1133643088
Also brought some perf wins across from https://github.com/outline/outline/pull/3503 as not sure when that will land.

perf: Remove markdown serialize from editor render path

---

yarn.lock

This is just me running `yarn` on main

chore: minor version bump

---

server/emails/templates/WebhookDisabledEmail.tsx
server/queues/tasks/DeliverWebhookTask.ts

fix: Webhook not disabled under some error conditions
closes #3700

feat: Send warning email to creator when webhook is disabled

---

app/scenes/Settings/Notifications.tsx
server/commands/userCreator.ts
server/emails/templates/BaseEmail.tsx
server/emails/templates/CollectionNotificationEmail.tsx
server/emails/templates/DocumentNotificationEmail.tsx
server/emails/templates/InviteAcceptedEmail.tsx
server/emails/templates/WelcomeEmail.tsx
server/models/NotificationSetting.ts
server/models/User.ts
server/routes/auth/providers/email.ts
server/routes/auth/providers/google.ts
server/utils/authentication.ts
server/utils/jwt.ts
shared/i18n/locales/en_US/translation.json

- Adds a new notification email sent to the inviter when an invite is accepted, it can be unsubscribed from.
- Updates copy of welcome email a bit
closes #3716

feat: Add optional notification email when invite is accepted

---

server/migrations/20220702132722-add-webhooks-deleted-at.js
server/models/WebhookSubscription.ts

chore: Soft delete webhooks

---

server/index.ts
server/logging/Logger.ts
server/services/collaboration.ts
server/services/websockets.ts

Fixes a number of potential server crashes as the result of maliciously malformed and unhandled websocket requests.

fix: Improved websockets error handling

---

server/commands/teamUpdater.ts
server/models/TeamDomain.test.ts
server/models/TeamDomain.ts
server/models/validators/IsFQDN.ts
shared/constants.ts

- fix: Validate team domains are FQDN's
- fix: Deletion of domains not happening within request lifecycle
- fix: lowercase domain before validating against banned list
closes #3730

fix: Add 10 domain limit per team

---

app/scenes/CollectionEdit.tsx
app/scenes/CollectionNew.tsx
server/models/Collection.ts
server/models/Document.ts
server/models/User.ts
server/models/WebhookSubscription.ts
server/models/validators/IsHexColor.ts
server/models/validators/Length.ts

Also made `min` attribute on `Length` validator optional.

fix: Improved model validation for `Collection`

---

app/stores/SharesStore.ts
server/routes/api/__snapshots__/shares.test.ts.snap
server/routes/api/shares.test.ts
server/routes/api/shares.ts
server/routes/api/team.test.ts

Deprecated for over a year, time to remove old codepath.

chore: Remove `shares.info` apiVersion 1

---

server/models/ApiKey.ts
server/models/Attachment.ts
server/models/AuthenticationProvider.ts
server/models/Collection.ts
server/models/Document.ts
server/models/Event.ts
server/models/Group.ts
server/models/Integration.ts
server/models/Revision.ts
server/models/Team.ts
server/models/TeamDomain.ts
server/models/User.ts
server/test/factories.ts

File by file model column validation audit

chore: Audit of all model column validations

---

app/scenes/Document/Shared.tsx

Unauthorized / Not logged in users should be redirected to login page. Login page should prompt user to login to colab on this document. 
Closes #3745

feat: Redirect on unpublished share access

---

package.json
server/logging/Logger.ts
server/services/websockets.ts
yarn.lock

chore: Remove unmaintained `socket.io-auth`

---

server/utils/startup.ts

fix: Account for non-SSL database connection in pending migrations check

---

server/commands/teamCreator.test.ts
server/commands/teamCreator.ts

fix: authentication error the maximum number of teams has been reached

---

app/scenes/Document/components/DataLoader.tsx
package.json
server/commands/documentImporter.test.ts
server/commands/documentImporter.ts
server/models/Collection.ts
server/queues/tasks/ImportNotionTask.ts
server/queues/tasks/ImportTask.ts
shared/validations.ts
yarn.lock

fix: Parallelize attachment upload during import

fix: Long collection description prevents import

---

server/migrations/20220722184916-remove-event-updatedat.js
server/models/Event.ts

chore: Remove updatedAt column from events table

---

app/components/Editor.tsx
app/editor/components/CommandMenu.tsx
app/scenes/Settings/components/ImageUpload.tsx
server/routes/api/attachments.test.ts
server/routes/api/attachments.ts
server/utils/__mocks__/s3.ts
shared/editor/nodes/Image.tsx
shared/utils/files.ts
shared/validations.ts

fix: substitution of content when sending an image to a profile

---

server/queues/tasks/ImportTask.ts

fix: Cleanup attachments uploaded to S3 when import fails

---

package.json
yarn.lock

Revert "chore(deps-dev): bump react-refresh from 0.9.0 to 0.14.0"

---

app/actions/definitions/documents.tsx

fix(app): remove templatize action for trashed document

---

app/utils/ApiClient.ts
app/utils/errors.ts
app/utils/sentry.ts
server/RateLimiter.ts
server/__mocks__/RateLimiter.ts
server/logging/Logger.ts
server/middlewares/rateLimiter.ts
server/models/FileOperation.ts
server/routes/api/collections.ts
server/routes/api/index.ts
server/routes/api/users.ts
server/routes/auth/index.ts
server/routes/auth/providers/email.ts
server/types.ts

- Refactor
- api/users
- api/collections
- auth
Towards #3950

chore: Rate limiter audit

---

shared/editor/plugins/Mermaid.ts

perf: Suppress Mermaid diagram rendering when hidden

---

server/migrations/20220720221531-remove-deprecated-columns.js
server/models/Attachment.ts
server/test/factories.ts

chore: Remove long deprecated database columns

---

server/utils/parseDocumentIds.test.ts
server/utils/parseDocumentIds.ts
shared/utils/parseDocumentSlug.ts

fix: Allow backlinks to work with fully qualified urls and anchors

---

app/scenes/Login/index.tsx
app/styles/globals.ts
server/static/index.html

fix: Login screen not vertically centered on mobile

---

server/models/UserAuthentication.ts

fix: Handle GitLab can be configured for tokens to not expire.

---

app/stores/AuthStore.ts

fix: Post-signin redirect path is no longer saved

---

server/emails/templates/BaseEmail.tsx
server/emails/templates/DocumentNotificationEmail.tsx
server/migrations/20220828144837-add-columns-to-notifications-for-tracking.js
server/models/Notification.ts
server/queues/processors/NotificationsProcessor.test.ts
server/queues/processors/NotificationsProcessor.ts
server/queues/tasks/EmailTask.ts
server/types.ts

Throttle email notifications upon updating document frequently

---

app/components/Editor.tsx
app/components/SearchListItem.tsx
app/components/Sidebar/components/SharedDocumentLink.tsx
app/routes/index.tsx
app/scenes/Document/components/PublicBreadcrumb.tsx
app/scenes/Document/components/ReferenceListItem.tsx
app/utils/routeHelpers.test.ts
app/utils/routeHelpers.ts
server/models/Share.ts
server/presenters/share.ts
server/routes/index.test.ts
server/routes/index.ts

Permanently redirect to `/s/...` for share links

---

server/migrations/20220909203454-fix-notification-constraints.js

fix: Missing cascade constraints on notifications table

---

app/components/DocumentCard.tsx
app/components/PinnedDocuments.tsx
app/components/Squircle.tsx

The colored blocks really don't work very well in a lot of circumstances, they can be overbearing and ugly. Moving to a subtler document-like look with some cute details.

feat: Updated designs for pinned docs

---

server/emails/templates/BaseEmail.tsx
server/emails/templates/DocumentNotificationEmail.tsx

Probable fix for #4169 – but needs to be deployed to production to know for sure

Extract email styles into head

---

shared/editor/embeds/Abstract.tsx

Issue: #4204.
Refactor Abstract class component to functional

Refractor Abstract class component to functional

---

shared/editor/embeds/Airtable.tsx

Issue: #4204.
Refactor Airtable class component to functional

Refactor Airtable class component to functional

---

app/components/Theme.tsx
app/components/Tooltip.tsx
app/editor/components/Tooltip.tsx
package.json
yarn.lock

fix: Upgrade popper, tippy to fix error

---

app/components/Analytics.tsx

https://github.com/outline/outline/issues/4204#issue-1393503119
Refactored Analytics component to Functional component

Refactored Analytics component to functional component

---

shared/editor/embeds/Bilibili.tsx

Issue: #4204.
Refactor Bilibili class component to functional

Refactor Bilibili class component to functional

---

shared/editor/embeds/Berrycast.test.ts
shared/editor/embeds/Cawemo.tsx
shared/editor/embeds/ClickUp.tsx
shared/editor/embeds/Codepen.tsx
shared/editor/embeds/DBDiagram.test.ts
shared/editor/embeds/DBDiagram.tsx
shared/editor/embeds/Descript.tsx

Issue: #4204.
Refactor DBDiagram class component to functional
Added missing tests.

Refactor DBDiagram class component to functional

---

app/components/Input.tsx
app/scenes/Invite.tsx

Remove invite button should not overlap with member dropdown button

---

server/collaboration/LoggerExtension.ts
server/collaboration/PersistenceExtension.ts
server/commands/documentCollaborativeUpdater.ts
server/commands/documentUpdater.ts
server/logging/Logger.ts
server/models/Event.ts

Also performance improvements in collaboration persistence.
closes #4267

fix: Multiplayer changes potentially attributed to incorrect user

---

app/hooks/useRequest.ts
app/menus/DocumentMenu.tsx

Set subscribe/unsubscribe state correctly for documents

---

shared/editor/embeds/GoogleDocs.tsx
shared/editor/embeds/GoogleDrive.tsx
shared/editor/embeds/GoogleSheets.tsx
shared/editor/embeds/GoogleSlides.tsx

Functional Component Refactor: Google Docs, Drive, Sheets, & Slides

---

shared/editor/embeds/Figma.tsx
shared/editor/embeds/Framer.tsx
shared/editor/embeds/Gist.tsx

Functional Component Refactor: Figma, Framer, Gist

---

shared/editor/embeds/InVision.tsx
shared/editor/embeds/Loom.tsx
shared/editor/embeds/Lucidchart.tsx

Functional Component Refactor: InVision, Loom, Lucidchart

---

shared/editor/embeds/Marvel.tsx
shared/editor/embeds/Mindmeister.tsx
shared/editor/embeds/Miro.tsx
shared/editor/embeds/ModeAnalytics.tsx

Functional Component Refactor: Marvel, Mindmeister, Miro, ModeAnalytics

---

shared/editor/embeds/Pitch.tsx
shared/editor/embeds/Prezi.tsx
shared/editor/embeds/Spotify.tsx
shared/editor/embeds/Trello.tsx

Functional Component Refactor: Pitch, Prezi, Spotify, Trello

---

shared/editor/embeds/Typeform.tsx
shared/editor/embeds/Vimeo.tsx
shared/editor/embeds/Whimsical.tsx
shared/editor/embeds/YouTube.tsx

Functional Component Refactor: TypeForm, Vimeo, Whimsical, YouTube

---

app/scenes/CollectionPermissions/AddPeopleToCollection.tsx
server/commands/userDemoter.test.ts
server/models/User.ts
server/routes/api/__snapshots__/collections.test.ts.snap
server/routes/api/collections.test.ts
server/routes/api/collections.ts

fix: Disallow adding self to collection

---

server/routes/auth/providers/email.test.ts
server/routes/auth/providers/email.ts

As discussed, this solves some potential confusion with email logins.

fix: Logging in with email on a subdomain should not forward to other subdomains

---

.env.sample
app.json
app/hooks/useAuthorizedSettingsConfig.ts
app/scenes/Login/index.tsx
app/scenes/Settings/Features.tsx
app/stores/AuthStore.ts
server/env.ts
server/presenters/env.ts
server/routes/api/auth.ts
shared/i18n/locales/en_US/translation.json
shared/types.ts

Add team preference to use logo for branding

---

app/components/Editor.tsx
app/editor/index.tsx
app/scenes/Settings/Preferences.tsx
package.json
shared/editor/components/Styles.ts
shared/editor/nodes/CodeFence.ts
shared/editor/plugins/Prism.ts
shared/i18n/locales/en_US/translation.json
shared/types.ts
yarn.lock

New user preference toggles line numbers displayed on code blocks

feat: Code blocks can now optionally display line numbers 

---

server/routes/api/documents.ts

Return correct permissions upon document update

---

server/models/Team.ts
server/models/User.ts
server/queues/tasks/DeleteAttachmentTask.ts
server/routes/api/attachments.test.ts
server/routes/api/attachments.ts
server/routes/api/users.ts
server/utils/parseAttachmentIds.ts

fix: Remove previous avatar when possible.
closes #4340 
closes #4293

fix: Allow viewers to upload avatar

---

server/commands/accountProvisioner.ts
server/commands/userProvisioner.test.ts
server/commands/userProvisioner.ts
server/models/Team.ts

Paired with @thenanyu on this,

fix: Unable to login with matching email from another auth provider

---

app/scenes/Document/components/MarkAsViewed.ts

Functional Component Refactor: MarkAsViewed

---

app/editor/components/ComponentView.tsx
app/index.tsx
shared/editor/commands/insertFiles.ts
shared/editor/components/Styles.ts
shared/editor/nodes/Image.tsx

closes #3537
closes #3329 
closes #3248
closes #804

feat: Image resizing

---

server/commands/teamPermanentDeleter.ts
server/migrations/20221111171828-fix-user-constraints.js

Migration already applied in prod.
closes OLN-101

Add missing team->user constraint

---

server/commands/accountProvisioner.test.ts
server/commands/teamProvisioner.test.ts
server/commands/teamProvisioner.ts

fix: Self-hosted logic for allowed domains

---

server/migrations/20221112162341-attachment-tracking.js
server/models/Attachment.ts
server/routes/api/attachments.ts

feat: Track attachments access

---

app/components/Avatar/Avatar.tsx
app/components/Sidebar/App.tsx
app/components/Sidebar/Settings.tsx
app/components/Sidebar/Shared.tsx
app/components/Sidebar/Sidebar.tsx
app/components/Sidebar/components/HeaderButton.tsx
app/components/Sidebar/components/SharedDocumentLink.tsx
app/components/Sidebar/components/SidebarButton.tsx
app/components/TeamLogo.ts
app/scenes/Document/Shared.tsx
app/scenes/Settings/Features.tsx
app/stores/DocumentsStore.ts
server/routes/api/auth.ts
server/routes/api/documents.ts

- Also some nice improvements to the sidebar for public nested docs.
- Removed the sidebar if there are no subdocuments
closes #4291

feat: Optional branding on shared documents

---

server/routes/api/attachments.test.ts
server/routes/api/attachments.ts

Enable viewers to upload attachments for documents in collections where they have edit permission

---

app/components/Sidebar/components/Version.tsx

fix: correct stats for update-checker

---

server/routes/api/documents/documents.test.ts
server/routes/api/documents/schema.ts

Allow document to be dragged to the top of a collection

---

app/components/NudeButton.tsx
app/components/Sidebar/App.tsx
app/components/Sidebar/Settings.tsx
app/components/Sidebar/Sidebar.tsx
app/components/Sidebar/components/Header.tsx
app/components/Sidebar/components/HeaderButton.tsx
app/components/Sidebar/components/HistoryNavigation.tsx
app/typings/window.d.ts
shared/i18n/locales/en_US/translation.json

- History navigation
- Remove promise from bridge interface
- More undraggable items
- Adjust traffic light control position

Desktop improvements

---

server/utils/s3.ts

fix: Remove unused S3 methods

---

shared/editor/plugins/PasteHandler.ts

fix: Don't embed pasted links in list

---

server/commands/documentCollaborativeUpdater.ts
server/models/Document.ts

perf: Improve collab persistence performance

---

server/index.ts
server/routes/api/index.ts
server/routes/auth/index.ts

Rate limit all routes

---

server/commands/documentPermanentDeleter.test.ts
server/commands/documentPermanentDeleter.ts
server/models/Team.ts
server/models/User.ts
server/queues/tasks/DeleteAttachmentTask.ts

…upon permanant delete
closes #4557

fix: Uploaded and immediately deleted images are not removed from storage

---

server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts
server/test/factories.ts

Additional backend filters for https://github.com/outline/outline/pull/4442

Add additional filters to `search_titles` endpoint

---

shared/editor/components/Styles.ts

Mainly just a lack of CSS specificity.
closes #4635

fix: List inside of checkbox list is not styled correctly

---

app/components/Sidebar/components/EditableTitle.tsx

fix: Start editing with all text selected
fix: Styling issue around input
closes #4715

fix: Cannot click on input in sidebar when editing doc/collection

---

app/actions/definitions/documents.tsx
shared/i18n/locales/en_US/translation.json

show collection name in pin menu

---

app/components/Sidebar/components/SidebarLink.tsx
app/stores/DocumentsStore.ts
server/presenters/collection.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts

Updated the API to return the collection that's already in memory so that everything can be updated at once.
closes #4702

fix: Sidebar jumps when publish or unpublish document

---

server/collaboration/ConnectionLimitExtension.ts
server/env.ts
server/services/collaboration.ts

chore: Add configurable per-document connection limit extension

---

app/stores/CollectionsStore.ts

Collections order in publish modal

---

app/components/DocumentExplorerSearchResult.tsx
app/utils/tree.ts

Missing collection name in path section of search results

---

app/stores/DocumentsStore.ts

Duplicate docs as unpublished drafts

---

app/utils/tree.ts

Remove document name from path

---

server/models/helpers/DocumentHelper.test.ts
server/models/helpers/DocumentHelper.tsx
shared/editor/nodes/Table.ts

feat: For changes in long tables do not print the entire table in the email

---

server/policies/document.test.ts
server/policies/document.ts

Viewer should be allowed to subscribe to a document

---

app/components/DocumentExplorer.tsx
app/components/DocumentExplorerNode.tsx

Scroll children into view upon expansion

---

app/components/Sidebar/App.tsx
app/components/Sidebar/components/CollectionLinkChildren.tsx
app/components/Sidebar/components/DocumentLink.tsx
app/components/Sidebar/components/DragPlaceholder.tsx
app/components/Sidebar/components/DraggableCollectionLink.tsx
app/components/Sidebar/components/DropCursor.tsx
app/components/Sidebar/components/Starred.tsx
app/components/Sidebar/components/StarredLink.tsx

This is still pretty far from perfect, but I'm glad to get rid of the native drag previews which looked awful.

Improve drag-and-drop

---

.circleci/config.yml

Testing this as a solution in CI.

fix: Bundle size calculation includes development React

---

package.json
vite.config.ts
yarn.lock

Reduce bundle size by automatically replacing lodash imports with individual imports.

Optimize lodash bundle size

---

server/static/index.html
vite.config.ts

Fix PWA manifest

---

server/middlewares/coaleseBody.ts
server/routes/api/index.ts
server/routes/auth/index.ts

Succesfully fetch drafts

---

plugins/webhooks/client/components/WebhookSubscriptionForm.tsx
plugins/webhooks/server/tasks/DeliverWebhookTask.ts
shared/editor/plugins/Prism.ts

Webhook support for comments

---

.env.sample
server/env.ts
server/logging/Logger.ts

Configure server logs severity using environment var

---

app/editor/components/CommandMenu.tsx
shared/editor/commands/insertFiles.ts

fix: Allow uploading multiple media files at once

---

server/collaboration/ViewsExtension.ts
server/emails/templates/CommentCreatedEmail.tsx
server/models/View.ts
server/models/helpers/NotificationHelper.ts
server/queues/processors/NotificationsProcessor.test.ts
server/services/collaboration.ts
server/services/websockets.ts

Suppress comment notifications when viewing document

---

app/components/Portal.tsx
app/editor/components/BlockMenu.tsx
app/editor/components/CommandMenu.tsx
app/editor/components/EmojiMenu.tsx
app/editor/components/EmojiMenuItem.tsx
app/editor/components/FloatingToolbar.tsx
app/editor/components/MentionMenu.tsx
app/editor/components/MentionMenuItem.tsx
app/editor/components/SelectionToolbar.tsx
app/editor/components/SuggestionsMenu.tsx
app/editor/components/SuggestionsMenuItem.tsx
app/editor/index.tsx

chore: Refactoring some editor controls

---

server/models/Group.ts
server/routes/api/groups/groups.test.ts
server/routes/api/groups/groups.ts
server/routes/api/groups/schema.ts

Filter groups given a member

---

plugins/oidc/server/auth/oidc.ts
server/commands/accountProvisioner.test.ts
server/commands/accountProvisioner.ts
server/commands/userProvisioner.test.ts
server/commands/userProvisioner.ts
server/migrations/20230317144617-remove-user-username.js
server/models/User.ts
server/presenters/user.test.ts
server/test/factories.ts
server/test/support.ts

Drop `username` column

---

shared/editor/nodes/CodeFence.ts
shared/editor/plugins/Prism.ts

Nix is a build system and package manager and used in one of the top-10
most active repos on GitHub.

feat: add support for Nix code highlight (#4781

---

yarn.lock

Subject to internal testing
related #4318

chore: Upgrade `lib0`

---

shared/editor/components/Image.tsx

This actually works really nicely…
closes #5114

Adds placeholder during image loading (#5120

---

server/migrations/20230330181038-remove-column-userId-from-documents.js

Remove unused column from documents table

---

server/commands/commentUpdater.ts
server/emails/templates/CommentMentionedEmail.tsx
server/emails/templates/DocumentMentionNotificationEmail.tsx
server/emails/templates/DocumentMentionedEmail.tsx
server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx
server/queues/processors/NotificationsProcessor.test.ts
server/queues/processors/NotificationsProcessor.ts
server/queues/tasks/CommentCreatedNotificationTask.ts
server/queues/tasks/CommentUpdatedNotificationTask.ts
server/types.ts

fix: Email notifications not sent when mention added to edited comment (#5145

---

plugins/oidc/server/auth/oidc.test.ts
plugins/oidc/server/auth/oidc.ts
server/routes/api/auth.test.ts
server/routes/api/authenticationProviders/authenticationProviders.test.ts
server/test/env.ts

Pass query params to authorize endpoint during OIDC login

---

app/editor/components/MentionMenu.tsx
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts

fix: Mentions do not show any options in public collections

---

app/components/Layout.tsx
app/components/PageTitle.tsx
app/editor/components/SelectionToolbar.tsx
app/index.tsx
app/scenes/Document/Shared.tsx
app/scenes/Settings/Zapier.tsx
package.json
yarn.lock

fix: React devmode warnings (#5169

---

app/models/Team.ts
app/scenes/Login/index.tsx
app/scenes/Settings/Features.tsx
app/scenes/Settings/Preferences.tsx
app/scenes/Settings/Security.tsx
server/models/Team.ts
server/models/User.ts
server/policies/document.ts
server/presenters/publicTeam.ts
shared/constants.ts
shared/types.ts

Passing the fallback at each callpoint was dumb, lets be honest.

Centralize default user and team preferences. (#5172

---

server/routes/api/documents/documents.ts

Collection memberships required to be preloaded before publishing a document

---

app/components/Sidebar/Right.tsx
app/components/Sidebar/Sidebar.tsx
app/scenes/Document/components/CommentThread.tsx
app/scenes/Document/components/CommentThreadItem.tsx
app/scenes/Document/components/Editor.tsx

See individual commits and #5191

fix: Various fixes for commenting on mobile (#5195

---

app/editor/components/SelectionToolbar.tsx
app/editor/menus/formatting.tsx
app/hooks/useDictionary.ts
package.json
shared/editor/nodes/ListItem.ts
shared/i18n/locales/en_US/translation.json
yarn.lock

Add list indent/outdent controls on mobile

---

server/models/helpers/ProsemirrorHelper.tsx
server/utils/parseAttachmentIds.test.ts
server/utils/parseDocumentIds.test.ts
server/utils/parseDocumentIds.ts
server/utils/parseImages.test.ts
server/utils/parseImages.ts
shared/editor/commands/createAndInsertLink.ts

fix: Double recursive loops can cause server lockup on deeply nested docs

---

app/editor/components/SelectionToolbar.tsx

fix: Hide floating toolbar when dragging content

---

server/policies/comment.ts
server/routes/api/comments/comments.ts

Allow workspace admins to remove comments

---

server/models/WebhookSubscription.ts

fix: use real boolean instead of aws's bool
