outline/outline

app/models/Document.js, app/scenes/Document/Document.js, server/api/__snapshots__/documents.test.js.snap, server/api/documents.js, server/api/documents.test.js, server/presenters/document.js
Whilst we're waiting on collaborative editing this simple safety measure ensures that you can't accidentally overwrite another users edits.
It also ensures that the latest content is always displayed when entering edit mode which wasn't happening previously – the content would be fetched but the Editor would not update.
Note: Base is `collection-home` for review purposes. Needs changing to `master` to merge.
=> Prevents accidental overwriting of another users work

app/models/Collection.js, app/scenes/Collection/Collection.js, app/stores/DocumentsStore.js
Instead of documents store needing reference to collections we collection the documentIds from the collection model itself as the source of truth. Removes expectation that `document.collection.id` exists.
=> Fixes: Issue with missing collection id

index.js
Basically check for an undefined SECRET_KEY in index before starting the server. An undefined entry is the result of a missing or misconfigured .env file or environment variables.
The error message could be more specific but as it is you are at least pointed at the right direction to get your install config going.
=> Address failing startup without .env #459

app/components/Sidebar/components/Collections.js
The active link were also applies to collection links
=> Fixed sidebar styles when on collection home

app/components/CenteredContent/CenteredContent.js, app/components/ErrorBoundary/ErrorBoundary.js, app/scenes/Document/Document.js
Wrapped the Document scene into an error boundary so that the navigation etc will work as I'm expecting that most our bugs will be in this view. Also made the error message little friendlier.
=> More detailed error boundary for Document

app/components/Collaborators/Collaborators.js, app/components/DocumentPreview/DocumentPreview.js, app/components/Sidebar/Sidebar.js, app/components/Sidebar/components/Collections.js, app/components/Sidebar/components/SidebarLink.js, app/scenes/Collection/Collection.js, app/scenes/Dashboard/Dashboard.js, app/scenes/Document/Document.js, app/stores/UiStore.js
- Removed "scroll to view" from the sidebar as it felt more broken than useful. Potentially can bring back later in more tuned version
- Fixed react warnings, mainly missing keys and nested `<a>`s
- Clear active collection when moving out to dashboard for example
=> Sidebar fixes and warnings

app/scenes/Document/Document.js
Hey guys! Jori especially ;). This project looks awesome! I wanted to get involved if possible so I set it up today. This is a tiny PR to address issue #493. It's a little weird to have the text be Publish when in fact you are just saving, so I'm not sure if this fix is sufficient. Generally there is a publish/save distinction if you can have content that is visible to you in draft form but is not ready for the group to see yet. Also it doesn't look like there are component level tests so I didn't write one, hopefully that's okay!
=> CMD+S in a new document should not exit edit mode

package.json, server/api/__snapshots__/team.test.js.snap, server/api/__snapshots__/user.test.js.snap, server/api/apiKeys.js, server/api/auth.js, server/api/hooks.js, server/api/index.js, server/api/middlewares/authentication.js, server/api/middlewares/authentication.test.js, server/api/team.js, server/api/team.test.js, server/api/user.js, server/api/views.js, server/migrations/20171225143838-set-admins.js, server/models/Team.js, server/pages/Api.js, server/presenters/__snapshots__/user.test.js.snap, server/presenters/document.js, server/presenters/user.js, server/sequelize.js, server/test/support.js, yarn.lock
I'll implement the UI in a separate PR as this grew in size:
- Updated `sequelize` so that ops match current documentations. No change in Jest but did it anyway
- Started using dormant `User#isAdmin` as each user can only belong to one team at the time. Seemed to be the easiest for now but `Team` has functions to abstract admin promotion/demotion if we want to swap the implementation later
- Moved `auth()` middlewares to utilize `router.use()` where it makes sense (ie. we expect the same authentication for the API section)
- `auth` middleware now takes `adminOnly` option
- Added unit tests for `auth()` middleware (finally)
- New endpoints to fetch, promote and demote admin users
- User email is now only exposed to the user themselves and admins. There's no real reason for this but I don't …
=> Backend support for team admins

app/components/Editor/components/Toolbar/Toolbar.js
- When selecting with a mouse, only show the inline toolbar on `mouseup` event
- Delay showing the toolbar a tiny bit, feels more natural
=> Toolbar select tweaks

app/components/Editor/components/Toolbar/Toolbar.js, app/components/Editor/components/Toolbar/components/LinkToolbar.js
Bug: When selecting large section of text with a link it it, LinkToolbar would be opened and focus drawn to it automatically.
With these changes, toolbar is only shown when user has the focus within the link bounds. I also took out the autofocus as I found it feeling wrong as it captures user's focus. Also adjusted the toolbar size to give more space for links
=> LinkToolbar changes

app/components/Editor/Editor.js, app/components/Editor/plugins/KeyboardShortcuts.js, app/components/Editor/utils.js, app/components/Layout/Layout.js, app/scenes/KeyboardShortcuts/KeyboardShortcuts.js
`event.metaKey` maps to Windows key and not the Ctrl so keyboard shortcuts weren't working on Windows.
Fixes #525
=> Map keyboard shortcuts on windows

app/scenes/Document/Document.js
I removed this in https://github.com/outline/outline/pull/529 - that was dumb. The remount is very much needed and navigating between docs is broken without.
=> Ensure Document remount on nav

.env.sample
I do not have applying migrations, the problem is why it's written [here](https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers/33363660).
=> Fixed database urls in .env.sample file

app/components/Editor/components/Toolbar/components/LinkToolbar.js
Seems simple and obvious because it is, we should check that startBlock exists before using it
closes #538
=> Fix JS error where selection has no startBlock

app/components/DropToImport/DropToImport.js, app/components/Sidebar/components/Collections.js, app/menus/CollectionMenu.js, app/scenes/Collection/Collection.js, app/utils/importFile.js
The menu in the top right of the collection dashboard was not really working at all. I think we kinda just forgot to finish it off 😬 .
As it needed the logic to import files I refactored that out into it's own lib as it's used in several different places - which also means we can stop passing refs to the dropzone around.
closes https://github.com/outline/outline/issues/537
=> Fixes Collection ... menu not working

app/models/Document.js, server/api/documents.test.js, server/models/Document.js, server/presenters/document.js
Previously the default title was added on the client, and only on `documents.create`, so you could update it to a blank value easily. The server is the right place to do this and makes accepting documents through the API more reliable too.
closes #546
=> Move title validation to server

.flowconfig, app/components/Editor/components/Code.js, app/components/Editor/components/CopyButton.js, app/components/Editor/components/Image.js, app/components/Editor/marks.js, app/components/Editor/nodes.js, app/components/Editor/plugins.js, package.json, yarn.lock
There were several different bugs layered on top of each other with code blocks that made this something of a nightmare to figure out:
- `slate-edit-code` plugin depended on only having `code-line` blocks as children however it didn't automatically make this conversion. I [submitted a PR](https://github.com/GitbookIO/slate-edit-code/pull/34) and published the fixes that are relevant to us to my scoped npm.
- `slate-prism` also has a bug that causes the slate edit code normalization not to work on first load if there is a language class set on the block. I've gone ahead and disabled that for now, the default highlighting is still pretty good.
- The combination of the first two made any code blocks after the first appear empty.
=> Fixes code blocks

app/scenes/Search/Search.js, server/routes.js
I noticed that search behaves wonky now: typing from `10` to `100` just appends results and doesn't clear the previous results. Also it seems that react router decodes GET params automatically and re-decoding can lead to exceptions which we seen.
Also removed server side catch which doesn't do anything as we have a wildcard catch before it afaik
=> Search and routing fixes

package.json, yarn.lock
Fixes a number of the editor JS issues we've seen, including a JS error when pasting text over other text that I could reproduce and can't after the upgrade 😄
=> Upgrade Slate

app/components/Editor/plugins/MarkdownShortcuts.js, app/components/Editor/schema.js
Two fixes - ensure that Slate gets rid of anything other than text nodes in headings, and make sure that the markdown shortcuts functionality doesn't attempt to even put anything there.
Works beautifully.
=> Fixes: Possible to create blocks inside document title

app/index.js
Build failed because turns out the autotrack on npm is published as ES6 🙄 
https://dashboard.heroku.com/apps/beautifulatlas/activity/builds/8d15ec1e-cf12-4575-916a-b136a795cc8d
=> Fix autotrack not building correctly in prod

app/index.js, shared/components/Analytics.js
Accidentally removed tracking from static pages by moving the pageview call into the SPA 🙈
=> Restore static pageview tracking

app/menus/CollectionMenu.js, app/menus/DocumentMenu.js, app/models/Collection.js, app/models/Document.js
Seems like this was just kinda totally unneeded - we can re-add a working version of this as other permissions / policies get built later.
closes #592
=> Remove delete restriction

app/components/Auth.js, app/menus/AccountMenu.js, app/scenes/Home/Home.js, app/stores/AuthStore.js, app/utils/ApiClient.js
In my testing this fixes the redirect loop. I'm not a huge fan of putting the redirect in the model but it's kind of the only way to handle it when the clearing of local storage needs to be awaited – it's also a vital part of completing the logout.
=> Fix logout redirect loop

app/scenes/Document/components/DocumentMove/DocumentMove.js
It seems that my previous code to detect if the move location is the current location, was totally wrong; I was checking if the current parent is on the path, and not the last like it should be.
=> Fixed document move

.flowconfig, app/components/Editor/plugins.js, package.json, yarn.lock
They published my fixes for multiline support and Slate 32 compatibility in version `0.14.0` so we no longer have to use my fork 😄
=> Upgrade slate-edit-code

app/components/Scrollable/Scrollable.js
Prevent scrolling in the sidebar/ content area scrolling the other section when the boundary of a scrolling area is reached.
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
=> Improve scrolling behavior

package.json, yarn.lock
…to have better spacing in the Markdown output. Backwards compatible, docs will improve themselves as they are re-saved so no migration needed.
=> Improves rendering of headings 

app/utils/routeHelpers.js
Several characters that the slug library allows through but we weren't deeming as acceptable for a document route: https://github.com/dodo/node-slug/blob/master/slug.js#L60
closes #636
=> Adds _ and ~ as allowed slug characters

app/components/Sidebar/components/CollectionLink.js, app/components/Sidebar/components/Collections.js, app/components/Sidebar/components/DocumentLink.js, app/components/Sidebar/components/SidebarLink.js, app/menus/DocumentMenu.js, app/scenes/Document/components/Actions.js
Note: Based on `flow-71` branch for ease
- Clarify "New child document"
- Remove "Print" option from document menus on dashboard (it just prints the page)
- Cleanup / refactor component hierarchy a little
Towards https://github.com/outline/outline/issues/625
=> Sidebar cleanup

package.json
Deploys are failing. Looks like bcrypt isn't available pre-built for node 10 yet.
=> Restrict engines to < node 10

.env.sample, server/auth/google.js, server/pages/Home.js
Implements #681.
* Added an optional `GOOGLE_ALLOWED_DOMAINS` parameter in the environment which takes a comma separated list of domains to allow in Google auth.
* If it is not set, all Google apps domains are allowed by default.
@tommoor Please let me know if any changes have to be made. Open for feedback.
=> Allowed domains env variable for Google Auth

app/stores/SharesStore.js, server/api/__snapshots__/shares.test.js.snap, server/api/documents.js, server/api/documents.test.js, server/api/shares.js, server/api/shares.test.js, server/migrations/20180604191743-revoke-share-links.js, server/models/Share.js, server/pages/Api.js, server/policies/share.js
- Changes share link revocation to not delete the shares from the db entirely. Instead flagging when and who revoked the link.
- Adds missing tests for share revoke endpoint
- Updates API documentation to detail `shares` API.
This will also potentially allow us to display useful UI like "This link isn't available anymore".
=> Revoked share links

app/components/Sidebar/Main.js, app/components/Sidebar/components/Bubble.js
Based on feedback that its not clear on initial use where drafts go to. Looks something like…
=> Added bubble to side of drafts in sidebar with count of pending drafts

app/menus/NewChildDocumentMenu.js, app/scenes/Document/components/Header.js
New submenu gives the clear option of whether to create a doc in the collection or as a child document:
closes https://github.com/outline/outline/issues/625
=> Clarify where new document will be created from document header

Dockerfile, docker-compose.yml
See #756 for details. Also moved NODE_ENV definition under Dockerfile for the sake of consistency.
=> Fix PATH in modified shell environment

app/scenes/Dashboard.js
It was added in #718, but seems to have gone after the new tabs are added in the dashboard.
=> `showCollection` option in Dashboard documents list

server/utils/s3.js
The max size should be an integer rather than a string (environment variables
are strings). More strict s3 implementations reject the upload because they do
not consider the policy valid if a string is used rather than an integer.
=> server: fix content-length-range s3 uplaod policy

app/scenes/Document/Document.js
I believe this fixes a bug that means a user cannot edit a document if there is the word "history" in the user-generated part of the slug (ie. the title).
To reproduce the bug - make a document called "Transaction History", then try to edit it. The sidebar will keep opening and the url state will keep getting changed to history rather than edit.
=> Make isHistory regex slightly more specific

app/components/DocumentList.js, app/components/DocumentPreview/DocumentPreview.js, app/components/DocumentPreview/components/PublishingInfo.js, app/components/PaginatedDocumentList.js, app/components/Sidebar/components/CollectionLink.js, app/components/Tab.js, app/routes.js, app/scenes/Collection.js, app/scenes/Dashboard.js, app/stores/DocumentsStore.js, app/utils/routeHelpers.js
Adds 3 additional tabs as sort options when viewing a collection and infinite pagination.
ref https://github.com/outline/outline/issues/834
=> Add new document sort options to collections

server/api/hooks.js, server/api/hooks.test.js
Regex-like search queries from Slack should not cause a server error
closes #854
=> Fixes: Regex-like search queries error

app.json
Hey there! 
I saw a previous attempt to get this working, and you already have a Procfile in the root that Heroku needs.
I have tested this and done a couple of installs. Getting Google or Slack auth login support working is the hardest part, with Slack being easier. I still had a bit of difficulty -- probably walking people through what they need to do would be helpful.
Also, SLACK VERIFICATION is, I think deprecated, and might not be needed anymore -- both in your `env.sample` and in `app.json`.
You can do a test yourself by following this link, which will deploy from the branch that I am PR'ing here: https://heroku.com/deploy?template=https://github.com/bmann/outline/tree/heroku-deploy-support
=> Heroku deploy support

README.md
The previous link was giving 404. Changed the relative URL to absolute URL.
=> Fixed broken License link in Readme

README.md, app/components/PathToDocument.js, app/models/Collection.js, app/models/Document.js, app/scenes/Document/components/DocumentMove.js, app/stores/BaseStore.js, app/stores/CollectionsStore.js, app/stores/DocumentsStore.js, server/api/documents.js, server/commands/documentMover.js, server/commands/documentMover.test.js, server/models/Collection.js, server/models/Collection.test.js, server/models/Document.js, server/pages/developers/Api.js, server/policies/document.js
- Allow moving a document between collections
- Introduces a new `commands` pattern to reduce domain logic within models
- Introduces `get` method on base store to retrieve model by `id`
- Adds new server policy for `"move"`
- Improved `documents.move` error messages
- `parentDocument` parameter is now `parentDocumentId` in `documents.move`
- `collectionId` is now required by `documents.move`
closes https://github.com/outline/outline/issues/233
=> Move document improvements

server/api/__snapshots__/documents.test.js.snap, server/api/documents.js, server/api/documents.test.js
the documents.update API has been updated to accept a parameter `append`. When present, the text sent in the request will be appended to the existing document's text instead of replacing it.
Test cases to verify this have been added.
Resolves #950
=> Added ability to append to documents. Added test cases for the same

app/stores/DocumentsStore.js
This is because the front-end sends `collectionId` as `collection`, instead of `collectionId`.
Request:
Response:
=> fix: document duplicate command

app/models/Collection.js, app/scenes/CollectionExport.js, app/utils/ApiClient.js, app/utils/download.js, server/api/collections.js, server/api/index.js, server/api/middlewares/apiWrapper.js, server/pages/developers/Api.js
@captn3m0 this PR takes a step towards your export requirements, the `collections.export` endpoint allows downloading individual collections as a zip directly with this change – I've also made this behavior the default in the in-app UI.
Next step would be the entire wiki, however I'm going to disable that functionality on the hosted version in favor of keeping email export as It's pretty inadvisable to do so much heavy lifting on a node process that has to continue serving http requests.
closes https://github.com/outline/outline/issues/1000
=> feat: Export collection as direct download instead of emailing

Dockerfile
Otherwise, the running container does not show up in Traefik 😅
=> chore: add missing EXPOSE rule

.circleci/config.yml, Dockerfile, README.md, package.json
I recently upgraded Sequelize which was the biggest blocker to going to Node 12. Now it's just a version number update, everything seems to work well in tests and local testing.
closes https://github.com/outline/outline/issues/961
=> chore: Upgrade Node to v12

server/api/__snapshots__/users.test.js.snap, server/api/hooks.js, server/api/hooks.test.js, server/api/users.test.js, server/models/Document.js, server/models/Team.js
This PR addresses an issue where users that have never signed in to Slack are unable to search team accessible documents.
Previously the search was based entirely off user permissions, now if the passed user is unknown docs that are published in team visible collections will be searchable. This also means that teams using Google to sign in with a Slack integration get a much better experience.
If the user _is_ recognized then their permissions are used to retain searching of their own drafts and private collections.
closes https://github.com/outline/outline/issues/1047
=> fix: Unknown Slack users should be able to search team accessible docs

shared/styles/theme.js
Since `black50` sets 50% opacity, it causes the text behind the sidebar to be seen behind the sidebar at smaller/mobile device widths.
This adds a new `veryDarkBlue` color variable to theme.js and uses that for the dark theme sidebar's background color instead.
=> fix: remove transparency from dark theme sidebar background

server/migrations/20191118023010-cascade-delete.js, server/migrations/20191119023010-cascade-backlinks.js, server/migrations/20191119023011-cascade-parent-documents.js, server/migrations/20191119023012-cascade-shares.js, server/migrations/20191119023013-cascade-backlinks2.js
Seems like the issue was caused by changes made in https://github.com/sequelize/sequelize/pull/9890 – the foreign key name will change depending on which version of the app the migrations were originally made on.
closes https://github.com/outline/outline/issues/1117
=> fix: Account for migrations ran on old versions of Sequelize

app/stores/DocumentsStore.js
This is the simple solution, drafts are shown mixed in with all other documents with the "Draft" label. They're only visible if you're the author.
closes #1133
=> feat: Show drafts to author in collections

app/components/Editor/Editor.js, app/scenes/Document/components/Document.js, app/scenes/Settings/components/ImageUpload.js, app/utils/uploadFile.js, server/api/users.js, server/migrations/20200104233831-attachments.js, server/models/Attachment.js, server/models/index.js, server/pages/developers/Api.js
This PR provides the foundation for storing images and other file uploads in a private bucket.
Currently some of the data is stored in the `events` table but this is supposed to be an audit log, not a place to query for active data so it makes sense to create a new table for this concept with it's own schema and validation.
related https://github.com/outline/outline/pull/1137
related https://github.com/outline/outline/issues/1010
related https://github.com/outline/outline/issues/859
=> feat: Store image uploads as attachments in database

.env.sample
When running tests, `server/api/utils.test.js` would fail:
```
Summary of all failing tests
FAIL  server/api/utils.test.js
● #utils.gc › should require authentication
expect(received).toEqual(expected)
Expected value to equal:
401
Received:
200
70 |   it('should require authentication', async () => {
71 |     const res = await server.post('/api/utils.gc');
> 72 |     expect(res.status).toEqual(401);
73 |   });
74 | });
75 | 
at _callee3$ (server/api/utils.test.js:72:24)
at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
at step (server/api/utils.test.js:25:191)
at server/api/utils.test.js:25:361 …
```
=> fix: Add UTILS_SECRET to .env.sample

index.js
This allows for the Slack slash command to be used without
needing Slack sign in enabled.
connects to #1199
=> feat: Split up check for Slack environment variables

server/onboarding/editor.md
On the Editor page, after I first sign up for an account, the "integrations" link links to https://[mysubdomain].getoutline.com/integrations, which is a 404. 
The link needs to be the full link: https://www.getoutline.com/integrations
=> fix: Absolute routes won't work when users have subdomains

app/models/Document.js, server/api/documents.js, server/migrations/20200316040755-document-editor-version.js, server/models/Document.js, server/models/Revision.js
As we migrate to a brand new editor this will be useful to track and debug issues.
closes #1209
=> feat: Ensure that editorVersion is saved with document/revisions

app/components/Button.js, app/components/Editor/Editor.js, app/components/Sidebar/components/SidebarLink.js, app/models/Document.js, app/models/Revision.js, app/scenes/Document/components/Contents.js, app/scenes/Document/components/Document.js, app/scenes/Document/components/Editor.js, app/scenes/Document/components/Header.js, app/stores/RevisionsStore.js, app/stores/UiStore.js, package.json, shared/components/Breadcrumb.js, shared/styles/theme.js, shared/utils/getHeadingsForText.js, shared/utils/slugify.js, yarn.lock
The table of contents has long been relegated to a little strip down the right of the screen. It's very easy to miss and not a great reading experience.
This PR adds a new table of contents that can be expanded to the left hand side of the document body. The selected state follows the scroll position too. this PR works best when combined with the title separation PR so that the main document title is not included in the table of contents.
=> feat: Improved table of contents

server/models/Document.js, server/services/backlinks.js, server/services/backlinks.test.js, server/utils/slugify.js
If a document title is edited, and that document is directly linked from another – update the title in the link too.
=> feat: Auto update titles in linked documents

app/menus/DocumentMenu.js, app/models/Document.js, app/scenes/Document/components/Document.js
=> fix: Restore ability to disable embeds on a document

app/components/DocumentHistory/DocumentHistory.js, app/components/InputRich.js, app/components/Layout.js, app/components/Sidebar/Sidebar.js, server/pages/developers/index.js
According to [caniuse](https://caniuse.com/#feat=viewport-units) 100vw not considering scrollbars is considered a layout bug in the browsers:
closes #1241
=> fix: Various extra scrollbars when not using mac-style overlaying scrollbars

app/models/Document.js, app/utils/ApiClient.js, server/api/documents.js, server/api/index.js, server/api/middlewares/editor.js, server/errors.js
Split from https://github.com/outline/outline/pull/1227 – this will be deployed ahead of time to reduce the amount of clients that will write version 1 docs
=> chore: Auto reload frontend of client is out of date

server/api/groups.js, server/api/groups.test.js
Ideally this would be solved at the query level, but adding `required: true` on the GroupUser association causes us to bump into [this old Sequelize bug](https://github.com/sequelize/sequelize/issues/9869) – it generates an invalid query.
closes https://github.com/outline/outline/issues/1287
=> fix: Server error when listing memberships for group with deleted user

server/pages/developers/index.js
Menu items pointed to anchors links that were non-existent. 
Adding id's to proper sections (h2 tags) for anchor links in the menu to work.
=> fix: Make MenuItem Links work in Developer Page  (API)

server/api/documents.js, server/api/documents.test.js
Returns only the cleaned up Markdown, useful for display purposes or import into another system.
closes https://github.com/outline/outline/issues/1308
=> feat: Adds documents.export endpoint 

app/models/Document.js, app/utils/isInternalUrl.js, shared/utils/domains.js
adds a case in `util/domains` to account for one-part domains like `localhost:3000`
=> fix: allow one part domains in links

app/components/HoverPreview.js
For previews that do not use all the available space, it's nicer when we don't mask any of the content
---
For previews that use all of the space, mask only the last part of the last line for readability and implied continuation
---
This is similar to what Wikipedia does
---
=> feat: nicer gradient mask for hover previews

server/utils/updates.js
Was taking a peek at the file and noticed that this literal was probably supposed to be the `UPDATES_KEY` constant instead.
=> refactor: Fix updater's use of the UPDATES_KEY constant

app/components/IconPicker.js
closes https://github.com/outline/outline/issues/1377
handleOpen was already defined just not wired through
```ts
handleNameChange = (ev: SyntheticInputEvent<*>) => {
this.name = ev.target.value;
// If the user hasn't picked an icon yet, go ahead and suggest one based on
// the name of the collection. It's the little things sometimes.
if (!this.hasOpenedIconPicker) {
const keys = Object.keys(icons);
for (const key of keys) {
const icon = icons[key];
const keywords = icon.keywords.split(" ");
const namewords = this.name.toLowerCase().split(" ");
const matches = intersection(namewords, keywords);
if (matches.length > 0) {
this.icon = key;
return;
}
}
this.icon = "collection";
}
};
handleIconPickerOpen = () => {
this.hasOpenedIconPicker = true;
};
```
...
```ts
handleOpen = () => { …
```
=> fix: added missing call to onOpen

webpack.config.js, webpack.config.prod.js
Both of these updates do not change the initial download size, but they should massively reduce subsequent downloads when new deploys of the app go out.
- Split initial vendors and runtime into their own bundles
- Correctly hash bundles based on content so they don't need reloading on every deploy
closes #1460
=> pref: JS bundling improvements

app/components/PathToDocument.js, app/scenes/Document/components/DocumentMove.js
This PR includes a number of improvements to the document move dialog to improve the experience:
- There is no longer an artificial cap on results, instead the UI is scrollable. closes #1410 
- The original document name only shows in the path on hover now to reduce visual clutter and add clarity to the end desination.
- Fixed a number of visual and spacing bugs
- Fixed templates should not appear here as an option to move
=> fix: Unable to view all possible locations when moving document

app/menus/DocumentMenu.js, app/models/Document.js, app/stores/DocumentsStore.js, server/api/documents.js, server/api/documents.test.js, server/models/Document.js, server/policies/document.js
Implements the action to allow unpublish a document.
This option is only available for a publish document that wasn't archived or deleted.
Should check if the permissions for allowing whom can unpublish are set correctly.
=> feat: Allow unpublishing documents

app/scenes/Document/components/DataLoader.js, app/stores/DocumentsStore.js, package.json, server/api/documents.js, server/api/documents.test.js, yarn.lock
Moves searching for a document via the link editor to it's own endpoint. There are a couple of reasons for this:
- We're now recording search queries and these shouldn't be mixed in with link searches, it will improve the signal to noise ratio.
- Returning results that match based on content of the document doesn't make much sense for this context
- Faster!
=> feat: Improved search results when finding links in document editor

server/.babelrc
This cuts the amount of transpilation that is needed drastically by not treating the server like it has the same feature set as a browser from several years ago. It also cuts the server build time from ~16s -> ~3s
closes #1580
=> chore: Specify babelrc specifically for node environment

app/embeds/Spotify.js
Hello, while using outline I noticed the spotify iframe elements were using a wrong size. The spotify widgets are all using the same size either for tracks, playlist, album and podcast. This results in a lot of wasted space on the wiki page.
This fix allows to create widgets with specific size depending if it's a podcast episode, a song track, a playlist or an album following [the spotify recommandations](https://developer.spotify.com/documentation/widgets/).
Feel free to comment 👍
=> fix: spotify widget wrong size

server/api/hooks.js, server/api/hooks.test.js, server/auth/slack.js, server/test/factories.js
Allows searching from inside of Slack for Google-authed teams.
closes #1315
=> fix: Match search requests from Slack using Integration for non-Slack teams

app/scenes/Document/components/DataLoader.js, app/stores/RevisionsStore.js, server/api/documents.js, server/api/documents.test.js, server/api/revisions.test.js, server/events.js, server/migrations/20201028043021-reverse-document-id-index.js, server/models/Document.js, server/models/Document.test.js, server/models/Event.js, server/models/Revision.js, server/models/Revision.test.js, server/services/backlinks.js, server/services/backlinks.test.js, server/services/debouncer.js, server/services/notifications.js, server/services/notifications.test.js, server/services/revisions.js, server/services/revisions.test.js, server/services/slack.js
- Removes the dependency on revisions for updating backlinks and titles on documents
- Refactors debouncing out of notifications to it's own service
- Debounced revision creation (create a revision only if there has been no activity for X period of time)
- Debounced slack notifications (create a post only if there has been no activity for X period of time)
- Ensure there is always an item in document history for the current state
- Adds missing index to backlinks
- Suppress email notifications if document already viewed
closes #1607
closes #1608
=> chore: Refactor backlinks and revisions

app/components/Authenticated.js, app/models/Team.js, server/api/auth.js, server/auth/index.js, server/middlewares/authentication.js, server/migrations/20201103050534-custom-domains.js, server/models/Team.js, server/models/User.js, server/presenters/team.js, server/utils/domains.js, server/utils/jwt.js, shared/utils/domains.js
In order to support custom domains, the way authentication is passed between subdomains on signin is changing from a cross-subdomain cookie to a single-use token.
_Note_: For self-hosted installations this change has no impact.
=> chore: Refactor authentication pass between subdomains

app/embeds/Gist.js, app/embeds/Gist.test.js
Problem REGEX: https://regex101.com/r/Tm3EFc/1/
Fixed REGEX: https://regex101.com/r/3es1Mf/2
=> fix: gist not support username contains numbers

app/stores/AuthStore.js
If the user signs in or out in one tab, then make sure their session on the same subdomain is kept in sync on other tabs so you're not "fake" logged in.
Often folks will open multiple tabs to keep documents around for viewing, in that scenario this becomes a really nice detail to have.
=> feat: Sync sessions across browser tabs

app/components/DocumentPreview/DocumentPreview.js, app/components/EventBoundary.js
This bug affects the three places modals exist within the document dropdowns:
- Share link
- Create template
- Delete document
closes #1642
=> fix: Clicking the share link from a context menu navigates to document

server/commands/documentImporter.js, server/commands/documentImporter.test.js
=> fix: Unknown mimetype should fallback to Markdown parsing if .md

app/stores/SharesStore.js, app/utils/ApiClient.js, server/api/shares.js, server/api/shares.test.js
This pull request Fixes #1658 
I have updated server/api/share.js to send 204 status for unshared documents.
=> chore: Change response of shares.info response for unshared document

server/app.js
Server side reports are currently missing the user context which can be invaluable in debugging. `id` is the only context sent as elsewhere to keep PII out of third party services.
=> chore: Add user and auth context to server side error reports

.env.sample
Just adding a bit more context around the required information for setting up Google auth.
=> docs: Add note to .env.sample about Google OAuth URI

.env.sample, server/mailer.js
Setting up a test email environment is a pain, this PR means it'll happen automatically if no email server details are set in development.
Unfortunately `ethereal.email` has chosen today to have SSL issues, so leaving this in draft until the service is resolved.
=> chore: Enable automatic generation of email server in non production env

server/models/Document.js, server/models/Document.test.js
=> fix: Unable to delete archived and templated documents

README.md, package.json
This is my first minor contribution to this awesome product! Kudos for the team behind it. 
This PR introduces a new `yarn upgrade` command that fetches the latest branch updates and rebuilds the project.
I've also updated the README.md to include a block for upgrading
Fixes #1328
=> feat: command to upgrade outline

app/scenes/Settings/components/ImageUpload.js, app/utils/compressImage.js, app/utils/uploadFile.js, package.json, yarn.lock
Since avatar images are never displayed in full size, this PR compresses and reduces them to 256x256.
=> feat: Compress avatar images before upload

app/embeds/Miro.js, app/embeds/Miro.test.js
I've started trying to use Outline (it's great and has huge potential - thanks!), and we use Miro a lot.  I notice that the embed forces the embed url to `realtimeboard.com` - which breaks access to logged in boards, as we login via miro.com.  This change uses the incoming url domain to generate the iframe src url domain.
=> fix: miro - use the incoming domain to ensure access to logged in boards works

app/components/Editor.js, app/components/InputSearch.js, app/components/Layout.js, app/scenes/Document/components/Document.js, app/scenes/Document/components/Editor.js, app/scenes/Document/components/Header.js, app/scenes/KeyboardShortcuts.js, app/scenes/Search/Search.js, app/utils/keyboard.js, shared/i18n/locales/en_US/translation.json
- Removes incorrect use of `event.metaKey` (It's the Windows key on Windows)
- Adds additional helpers and utils for keybinding
- Fixes shortcuts incorrectly bound to Windows key
closes #1745
=> fix: Meta key shortcuts not bound correctly in Windows browsers

app/components/Breadcrumb.js, server/api/collections.test.js, server/models/Collection.js
=> fix: Deleting a collection should not deleted archived documents within

app/components/DocumentListItem.js, app/components/NudeButton.js, app/components/Star.js, app/scenes/Document/components/Editor.js, app/utils/keyboard.js
=> fix: Add indicator of starred status when viewing a document

app/components/Button.js, app/components/Editor.js, app/scenes/Document/components/DataLoader.js, app/scenes/Document/components/Document.js, app/scenes/Document/components/Header.js, package.json, yarn.lock
- fix: Don't remount document when switching between view and edit
- fix: Don't remount `MarkAsRead` when switching from view to edit
- fix: Button vertical alignment when using `as={Link}`
- Update latest editor for related fixes switching between edit/read-only. This brings in new functionality like the image toolbar and float controls too.
=> fix: Unintended scroll reset when switching between view / edit

.env.sample, app/components/Editor.js, app/components/HoverPreview.js, app/components/Image.js, app/components/PageTitle.js, app/embeds/GoogleDocs.js, app/embeds/GoogleDrive.js, app/embeds/GoogleSheets.js, app/embeds/GoogleSlides.js, app/embeds/index.js, app/scenes/Document/components/DataLoader.js, app/utils/urls.js, server/app.js, server/emails/components/Header.js, server/env.js, webpack.config.prod.js
Currently in testing on staging, adds an **optional** `CDN_URL` environment variable that can be pointed at a Cloudfront distribution or alternative proxy CDN that hosts static assets.
=> feat: Add CDN support

README.md
I tested this on the server. Running `yarn upgrade` will result in yarn self updating. To solve this issue we need to run `yarn run upgrade`.
=> fix: upgrade command

package.json, server/utils/s3.js, yarn.lock
Changes from the discussion here: https://github.com/outline/outline/discussions/1813
✅  Tested with old pre 2020 buckets (`AWS_S3_FORCE_PATH_STYLE=true`)
✅  Tested with new 2021 buckets (`AWS_S3_FORCE_PATH_STYLE=false`)
✅  Tested with new 2021 buckets
=> fix: Adds support for VirtualHost style AWS S3 buckets

server/app.js, server/routes.js, server/utils/prefetchTags.js
- Enables collection of detailed performance data by Sentry when the integration is enabled.
- Added cap to script prefetching
- Added additional comments
- Removed unused scriptsrc for Sentry now that we bundle in vendors
=> chore: Add Timing-Allow-Origin header

app/utils/ApiClient.js, server/static/index.html
Makes Outline work correctly behind Cloudflare Access proxies which require passing credentials (cookies) with API requests.
Fixes #1866
Fixes #1850
=> fix: Pass credentials with API requests when required to work with Cloudflare Access

server/api/attachments.js, server/api/attachments.test.js
=> fix: Documents in trash should still load their attachments

app/components/Header.js, shared/styles/globals.js, webpack.config.js
PWA support was added for self hosted installations in `0.53.0` however it hasn't yet worked for the cloud hosted version due to the reliance on a single domain. These changes add support for multiple subdomains and clean up the styling a little.
closes #1892
=> feat: Add PWA support to subdomains

app/scenes/Document/components/Header.js
=> fix: Centered document title moves when saving

app/menus/CollectionMenu.js
=> fix: Remove double separator in collection menu

app/components/Badge.js, app/components/CollectionDescription.js, app/components/CollectionIcon.js, app/scenes/Collection.js, shared/i18n/locales/en_US/translation.json
- Show "private" badge next to collection title when viewing collection scene
- Update badge styling
- Remove usage of specific icon for private collections as this is often overridden by a custom icon. Users can choose to have a padlock icon if they prefer.
---
closes #1897
=> chore: Show 'private' badge on private collections

app/embeds/GoogleSheets.js
The GoogleSheets component has an incorrect name which is "GoogleSlides". Its probably result of a copy/paste mistake.
=> fix: correct GoogleSheets component class name

app/components/Breadcrumb.js, app/components/Header.js, app/components/Sidebar/components/Toggle.js, app/scenes/Document/components/Header.js, server/static/index.html
Very wide viewport; the title is visually centered in the content area
When the viewport is made smaller, we use overflow ellipses to condense the title
Mobile breakpoint now displays the title
Saving indicator does not affect visual center...
...and it causes sensible overflow behavior
=> feat: use flexbox to center the floating title

app/components/Breadcrumb.js, app/components/DocumentMeta.js
1. adds ellipses to last segment of list item metadata
2. makes the slashes more visible, especially in dark mode and fixes vertical alignment
=> fix: touch up UI for compact breadcrumbs

.env.sample, app.json, app/scenes/Login/Notices.js, server/auth/google.js, server/commands/teamCreator.js, server/commands/teamCreator.test.js, server/errors.js, server/test/helper.js, server/utils/authentication.js
Behavior is as follows:
- On first install signup is open (apart from `ALLOWED_DOMAINS` restriction)
- After first team is registered no other teams can be created
- If attempting to signin with another google hd that's within `ALLOWED_DOMAINS` it will be assigned to the existing team, otherwise an error will be returned
- The addition of https://github.com/outline/outline/issues/1945 will enable adding multiple authentication methods in the future.
closes #862
=> feat: Enforce single team when self-hosted

server/api/documents.js, server/api/documents.test.js, server/commands/documentMover.js, server/commands/documentMover.test.js
This fixes an issue where the policies returned from a move operation were overly restrictive, resulting in no further moves being allowed (infact all editing actions were disallowed) until app is reloaded after moving a doc in a private collection.
Glad this was caught before this months release.
closes #1968
=> fix: Moving document in private collection returns incorrect policies

app/components/Sidebar/Main.js, app/menus/UserMenu.js, app/scenes/Settings/People.js, app/scenes/Settings/Shares.js, server/api/__snapshots__/users.test.js.snap, server/api/apiKeys.js, server/api/attachments.js, server/api/collections.js, server/api/documents.js, server/api/events.js, server/api/groups.js, server/api/notificationSettings.js, server/api/users.js, server/models/ApiKey.js, server/policies/apiKey.js, server/policies/attachment.js, server/policies/collection.js, server/policies/document.js, server/policies/group.js, server/policies/index.test.js, server/policies/integration.js, server/policies/notificationSetting.js, server/policies/team.js, server/policies/team.test.js, server/policies/user.js, server/test/factories.js
Exposing model creation policies on the team allows us to gate functionality on the frontend in a scalable way. This is particularly important as we introduce read-only roles.
closes #1158
=> chore: Serialize domain policies on team

server/api/shares.js, server/api/shares.test.js, server/policies/share.js
Currently multiple share records are created per-document – one per-user, this makes it hard to reason about and understand whether a document is truly shared publicly or not without checking in the admin interface.
This change makes it so that there is a single canonical share record per document.
=> fix: Single share record per document

server/api/documents.js, server/api/events.js, server/api/groups.js, server/api/integrations.js, server/api/revisions.js, server/api/shares.js, server/api/users.js, server/middlewares/validation.js
We've seen some errors where API clients submit an invalid value for the `sort` parameter, it must be a column in the database. Added a new validation to ensure this and return a more useful error to the API consumer.
=> fix: Add 'sort' parameter validation

app/models/Document.js, server/presenters/document.js
This data was unused by the frontend and the cause of a non-negligible portion of the API request time, this removal will make all document list actions more performant.
closes #2037
=> perf: Remove collaborators from documents.list response

.env.sample
Our Outline setup uses private Cloud SQL proxy connections so we didn't need to have SSL for our PG connections. I needed to configure this but had to read through the source code to figure out how to do it. Adding the config in the sample config file could make this a lot easier to discover.
=> chore: Document and include PGSSLMODE in sample env file

app/components/Input.js, app/components/InputSearch.js, app/components/InputSearchPage.js, app/scenes/Collection.js, app/scenes/Drafts.js, app/scenes/Home.js, app/scenes/KeyboardShortcuts.js, app/scenes/Starred.js
This bug came through support this morning – solution is to separate the search inputs for screens from a generic search input, in hindsight this should have been the first pass.
- `InputSearch` -> `InputPageSearch`
- [new] `InputSearch`
=> fix: CMD+F not working on screens with keyboard shortcut guide

app/components/Sidebar/components/SidebarLink.js
The cause seems to be nesting the input within an anchor tag – moving the associated actions _next_ to the anchor does the trick and doesn't seem to cause regressions with other sidebar functionality.
closes #1877
=> fix: Page reloads in Firefox when clicking some menu items

app/scenes/Login/index.js, server/auth/providers/email.js, server/middlewares/passport.js, server/migrations/20210430024222-marketing-tracking.js, server/models/Team.js, server/utils/authentication.js
In order to know where new teams are coming from we want to add minimal tracking so that we can quantify the value of different traffic sources.
This doesn't have any use that I can think of for self-hosted installations as it only applies to team creation, which will only happen once for these folks.
=> feat: Signup query params tracking

server/api/hooks.js
Removes redundant checks that prevent "post to slack" functionality from being used without Slack SSO (authentication provider matching teamId being present).
Note to self: We need to upgrade to use the new signed requests soon, verification token approach is deprecated due to the theoretical ability to tamper with the payload
=> fix: 'Post to channel' functionality does not work unless Slack SSO used

server/api/collections.js, server/api/collections.test.js, server/middlewares/validation.js, shared/utils/indexCharacters.js
Closes #2055 
Apart from abstracting the logic, this PR does two more things.
1. Add index characters validation in `collections.move` as well.
2. Necessary tests for both the endpoints.
=> fix: Move collection index validation logic to a context assert function

server/commands/documentMover.js, server/commands/documentMover.test.js, server/test/factories.js
=> fix: Moving documents between collections does not update attachment permissions

app/components/Editor.js, app/components/IconPicker.js, app/components/Time.js, app/index.js, app/routes/authenticated.js, app/routes/index.js, app/scenes/Settings/components/PeopleTable.js
Prevent webpack from renaming chunks between builds:
1. improve chunk modules tracking between builds
2. deterministic cache invalidation - chunks will be invalidated only when the content will change
=> build: Add async chunk names

webpack.config.js
- revert resolve.mainFields to [default](https://webpack.js.org/configuration/resolve/#resolvemainfields)
- revert boundless-* package aliases to commonjs folder to avoid transpiling
rel: https://github.com/outline/outline/pull/507/commits/fe00e1f76d080107bf7f0c4ec40e24c754efc521
@tommoor I pushed the config change to see the impact. There are many changes across the modules, please consider merging only if you don't see any side-effects.
=> build: Webpack config - allow package.json module field usage

app/index.js, webpack.config.js
1. make chunkIds deterministic (do not change across builds)
On webpack 4, chunkIds are set by default to `natural` ([non deterministic, based on usage order](https://v4.webpack.js.org/configuration/optimization/#optimizationchunkids)). This is causing hash changes across all chunks when a chunkId is changing:
In webpack 5 there is a new  default option ([`deterministic`](https://webpack.js.org/configuration/optimization/#optimizationchunkids)) that will achieve the same behaviour with a smaller size.
2. fix `webpackChunkName` syntax (rel: 082ced3)
=> Fix chunks setup

app/menus/DocumentMenu.js, server/api/documents.test.js, server/models/Document.js, server/policies/document.js
This PR fixes the bug of two restore options showing in the document menu when an archived document is deleted.
=> fix: Two restore options when an archived document is deleted

server/mailer.js
Hello, 
Here is a small pull request to change strategy related to SMTP "secure" configuration, that currently rely on NODE_ENV.
I think it should be overrided by an environment variable, because SMTP configuration is not related to Outline configuration.
Best regards
=> Use SMTP_SECURE environment variable to force secure parameter of smtp configuration

app/scenes/Document/components/Document.js, app/scenes/Document/components/Header.js, app/scenes/KeyboardShortcuts.js
`metaDisplay` is **Ctrl** on non-Mac systems so this key becomes "Ctrl+ctrl+h" which doesn't work. Changing `metaDisplay` to Alt seems to be a safe choice that should work on Mac too.
I also tried creating `KeyboardShortcuts.test.js` to detect duplicate keys in `KeyboardShortcuts` component's config but somehow can't install `enzyme` with yarn.
=> fix: change `metaDisplay` key to Alt for "Table of contents"

app/components/CopyToClipboard.js, flow-typed/npm/copy-to-clipboard_v3.x.x.js, package.json, yarn.lock
Upgrade `copy-to-clipboard` dep
closes #2207
=> fix: Link copied to clipboard takes dark mode styles

.env.sample
Updated the description of the `SECRET_KEY` variable in the `.env.sample` file to clarify that the key needs to be 32 bytes long and hex-encoded and make the suggested OpenSSL command slightly more prominent.
The previous description of "32 character hexadecimal" was confusing as it left open the possibility of a hex-encoded 16-byte key (see #1267 -- and I made the same mistake a year later).
=> Fix "secret key" variable description

server/utils/parseAttachmentIds.js, server/utils/parseAttachmentIds.test.js
Fun coincidence, I was already updating this logic for the work over in https://github.com/outline/outline/pull/2239 – the regex did not account for markdown image tags containing titles.
closes #2247
=> fix: Aligned images do not load in publicly shared documents

app/components/PaginatedList.test.js, app/test/setup.js, app/test/support.js
Tests have begun intermittently failing on a regular basis due to OOM errors, hoping this addresses the issue based on local heap measurements.
=> test: Reduce memory usage

server/auth/providers/email.js, server/auth/providers/email.test.js, server/migrations/20170712055148-non-unique-email.js, server/test/factories.js, server/test/support.js
It is possible to invite, say, a contractor `tom@example.com` to two teams – `one.getoutline.com` and `two.getoutline.com`, prior to these changes it was not possible to signin to the second created team via email, even when doing so via the `two.getoutline.com` subdomain.
Now the current domain or subdomain is given precedence.
closes #2249
=> fix: Email auth should allow same guest user on multiple subdomains

app/components/Sidebar/components/EditableTitle.js, app/components/Sidebar/components/SidebarLink.js
Hey, @tommoor.
I wanted to patch outline regarding RTL titles and sidebars, then I noticed you already worked on it. Thanks!
However, I found some small issues with the side bar regarding nested positions and edit mode, which I tried to address in this PR.
1. Nested documents appear flat.
2. Wrong input direction during edit.
1. Even though the text are aligned to left, the direction is correct and nesting is preserved. Since direction of app (regardless of the content) is LTR, this is acceptable even if texts are RTL.
2. Input direction is correct during edit.
=> fix: nested link positions for RTL titles in sidebar

server/api/events.js, server/api/events.test.js
This is one of several enablers for https://github.com/outline/outline/issues/2230 so we can drive the history panel from the events API.
=> feat: Add `documentId` filter to `events.list`

app/scenes/Document/components/Contents.js
closes https://github.com/outline/outline/issues/2240
=> fix: Allow TOC to scroll when larger than browser height

shared/i18n/locales/en_US/translation.json
#2307 introduced a duplicate `"Contents"` key in [`shared/i18n/locales/en_US/translations.json`](https://github.com/outline/outline/commit/959697999383bf5643813ae9ec00edfe0cc2c8dc#diff-16efc6d9ffa448721d7d5d26405b78774523868c4a2bfeb7e602f23918070a99R222)
=> fix: Remove duplicate translation key

app/components/Sidebar/Main.js
- Move 'templates' to bottom of sidebar – we expose the ability to create a document from a template as part of the new doc flow, so the list of templates doesn't need to be so prominently positioned 
- Hide trash and archive for read-only users, they can never use them
cc @iamsaumya there will be a small conflict with your drag and drop PR here.
=> chore: Move 'templates' to bottom of sidebar

server/scripts/20210716000000-backfill-revisions.js, server/scripts/20210716000000-backfill-revisions.test.js
Final piece of the puzzle to allow document history sidebar to be driven from events table.
Towards #2230
=> chore: Add revisions.create backfill script

app/components/Tab.js, app/scenes/Home.js, server/auth/index.js, shared/i18n/locales/en_US/translation.json
- When joining a team for the first time send the user to the default Collection directly. This improves the smoothness of onboarding experience by automatically expanding the sidebar too
- "Recently viewed" is a much more useful default for the Home screen
=> feat: Default to "recently viewed"

Dockerfile, package.json
* Use new BuildKit dockerfile syntaxes
* Leverage multi-stage build steps for faster builds
* Strip Yarn install cache from image, reducing final size
* Use a stricter version of `yarn install` such that it will fail with an invalid lockfile
* Run as a non-root user for security
* `yarn-deduplicate` was moved to a required dependency, otherwise running `yarn install --production` will fail on fresh installs.
* In my testing the image sizes were reduced from ~1.4GB to ~450MB
=> feat: Optimize Dockerfile

server/migrations/20210730042450-remove-unused-indexes.js
These are the biggest offenders for unused indexes. There are a few more, such as those on `search_queries` and `collection` search vectors, but we have plans to use those.
=> perf: Remove unused database indexes according to production data

Dockerfile
regressed in https://github.com/outline/outline/pull/2337
closes #2416
cc @lolPants
=> fix: /public directory missing in new docker releases

server/services/notifications.js
Notifications from the application are currently being sent to a user even when the user is suspended. This PR implements a change that suppresses notifications for suspended users.
=> fix: Suppress notifications for suspended users

server/api/auth.js, server/api/auth.test.js, server/auth/providers/google.js
> The `hd` parameter streamlines the login process for G Suite hosted accounts. By including the domain of the G Suite user (for example, mycollege.edu), you can indicate that the account selection UI should be optimized for accounts at that domain
To be very clear – it is just a hint and can be bypassed or modified by the client, it provides no security – just a push in the right direction and some reassurance that they are at the right Outline subdomain.
closes #2454
ref: https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param
=> feat: Add hosted domain hint when signing in through Google SSO from subdomain

server/api/auth.js, server/api/auth.test.js, server/auth/providers/google.js
Reverts outline/outline#2458 because it is confusing when team has multiple Google SSO, need to account for this case.
=> Revert "feat: Add hosted domain hint when signing in through Google SSO from subdomain"

app/scenes/Document/components/Header.js, app/scenes/Document/components/SharePopover.js, server/api/documents.js, server/api/documents.test.js
Show the share button even when public sharing is disabled in the security settings.
It basically checks if the person who opens the share link is logged in and has read access. If that's the case it will display the document.
Let me know if there's anything that need to be changed or if there's other feedback!
closes #2443 
closes #2444
=> feat: Always show share button

app/scenes/Document/components/ShareButton.js, app/scenes/Document/components/SharePopover.js, server/api/shares.js, server/api/shares.test.js, server/models/Share.js, server/policies/share.js
- No `shares.create` request made when a doc is viewed
- Use `read` policy in `shares.update` to allow users to create links for team sharing 
- Update `allow(User, "update", Share)` policy to check document sharing ability of user.
=> fix: Improvements in share feat

.env.sample, server/commands/accountProvisioner.js, server/commands/accountProvisioner.test.js, server/commands/userCreator.js, server/commands/userCreator.test.js, server/routes/auth/providers/oidc.js, server/test/factories.js
This is functionality described in the initial OIDC PR (#2369), but was removed as it was easier to make the PR smaller. I am unsure how much use the username property sees, however I do note that it exists and that most IdPs will provide some kind of `username` claim.
If this is useful then I will add polish as necessary.
Add an additional field to the authenticated user from the contents of `userinfo`. Specifically, the mapping is as follows:
- `preferred_username` (standard OIDC claim) &#8594; `user.username`
- `OIDC_USERNAME_CLAIM` &mdash; Override which claim to check for the user's username. Defaults to `preferred_username` which is the standard OIDC claim name.
=> feat: map preferred_username claim to user record

server/queues/processors/notifications.js, server/queues/processors/notifications.test.js, server/queues/processors/slack.js, server/routes/api/documents.js
Kind of thought I did this already 🤷  – because revisions are only created when the text actually changes this protects against sending notifications that are unneccessary 
closes #2703
=> fix: Move notifications to be revision driven

app/components/Editor.js, app/hooks/useIsMounted.js, app/scenes/Document/components/MultiplayerEditor.js
Second attempt, adds a class to the editor for a couple of seconds when the awareness is loaded to force cursors to display.
closes #2704
=> feat: Show collab cursor names upon loading document.

app/components/ContentEditable.js
The title can be changed (but not saved) when the document is in read only mode.
Before:
After:
----
By the way, I don't see any use of `disabled` props, perhaps `disabled` might be renamed to `readOnly`?
=> fix: fix issue where the title can be modified in read-only mode

app/scenes/Document/components/Contents.js
Hi, I think it would be fantastic if we could highlight the active item in the outline.
Dark theme:
Light theme:
=> feat: Highlight active ListItem in outline.

.babelrc, app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/NavLink.tsx, app/components/Sidebar/components/SidebarLink.tsx, app/components/Sidebar/components/StarredLink.tsx
closes #2486
based on #2741 – this PR was half way there but it drilled an `isOverlay` prop down through several components that don't need it and also didn't handle the background color correctly when the sidebar item is highlighted.
=> fix: No reserving space in sidebar for overflow

docker-compose.yml
If you open such services publicly, that might cause some security issues (i.e. every one can access those services). No matter it's on production or development.
=> Let redis, pgsql and s3 listen on localhost only. (docker-compose)

app/models/Document.ts, package.json
adds `done` and `publish` options to document.update - these got removed during the switchover to ts
=> fix: document publishing

app/components/Sidebar/components/CollectionLink.tsx, app/components/Sidebar/components/Collections.tsx, app/components/Sidebar/components/DocumentLink.tsx
Also simplifies the logic for collapsing collections when dragging by avoiding sending state out to the parent component and relying on the `useDrop` `monitor` instead.
This is so much nicer now, no "dead" areas in the sidebar when hovering over docs in manually sorted collections.
closes #2808
=> fix: Clickable area for docs in sidebar is obstructed

app/stores/DocumentsStore.ts
In try/catch blocks, `return await` is necessary to reach the `catch` clause.
=> fix: Catch error in promise and fix typo

Dockerfile
`process.env.CDN_URL` is evaluated during compile time in `webpack.config.prod.js`, so it has to be passed to `yarn build` to work.
=> feat: Support custom CDN in Dockerfile

docker-compose.yml
Commit 18cf148bd176d06d760555542bd8784eab5a36d9 made Yarn run locally outside of Docker, so there is no need to mount files into the container. This commit allows hosts without Node.js environment to run Outline with docker-compose.
Depends on #2823.
=> chore: Remove outline service in docker-compose.yml

package.json, server/commands/accountProvisioner.test.ts, server/commands/documentPermanentDeleter.test.ts, server/commands/fileOperationDeleter.test.ts, server/commands/teamCreator.test.ts, server/commands/teamPermanentDeleter.test.ts, server/routes/api/attachments.test.ts, server/routes/api/attachments.ts, server/routes/api/fileOperations.test.ts, server/routes/api/utils.test.ts, server/utils/s3.ts, yarn.lock
With an asynchronous credential provider like EC2 IAM roles, `createPresignedPost()` should always be called with an asynchronous callback.
closes #2829
Note: This implementation has not been tested against S3-compatible storage.
=> feat: Support IAM role authentication for S3

app/scenes/Document/components/ReferenceListItem.tsx
Related to https://github.com/outline/outline/issues/2810.
Now:
Fixed:
-------
We can deduce the cause of the overflow problem from this stackoverflow answer. We can do some tricks to achieve `text-overflow: ellipsis`. The solution is `width: calc(100%)`. We also need to change the display to inline block and add the line`vertical-align: middle` to align the svg and h3 vertically.
Reference:
https://stackoverflow.com/questions/17779293/css-text-overflow-ellipsis-not-working
https://stackoverflow.com/questions/9670469/css-vertical-alignment-of-inline-inline-block-elements
=> fix: Document icon overflow in ReferenceListItem

server/utils/s3.ts
`.bind()` returns `any`, so it no longer benefits from type checking.
=> fix: Bind context to util.promisify

app/components/Button.tsx, app/components/Sidebar/components/DocumentLink.tsx
- show children when the only child is the active draft
- disable drop onto draft items
- fix danger button hover color
=> fix: various bugs on draft sidebar items

app/scenes/Document/components/Document.tsx, shared/i18n/locales/en_US/translation.json
=> fix: changing the title and body content in quick succession would trigger unsaved changes warning prompt

app/scenes/Document/components/SharePopover.tsx, server/models/Collection.ts, server/models/Share.ts, server/policies/share.ts, server/routes/api/shares.ts, shared/i18n/locales/en_US/translation.json
fixes #2956 
- when a draft sharing is updated, the auth check failed because it could not locate the draft document when performing an auth check against collections. fixed here
- also uncovers and fixes a related issue: check the "include children" box when sharing a draft document causes an authorization error
- there's an open question on whether we should hide this option from draft shares. this patch make it a safe state but the UX is confusing enough that I think we should remove the option for drafts, so I also hide the secondary checkbox from draft documents
=> fix: issue-2956 

app/components/Sidebar/components/TeamButton.tsx
=> fix: truncate a very long team name with ellipses

app/scenes/Document/components/ShareButton.tsx, app/scenes/Document/components/SharePopover.tsx
=> fix: Share popover incorrectly displays draft as publicly shared

server/commands/teamCreator.ts, server/routes/auth/providers/google.ts, server/routes/auth/providers/oidc.ts, server/utils/authentication.ts
Currently the way allowed domains are checked is (just an example): https://github.com/outline/outline/blob/390a1343b788af56ad52f9bb267edf82e65920bf/server/routes/auth/providers/oidc.ts#L87-L92
Notice that empty `ALLOWED_DOMAINS` will result into this error never being thrown thus allowing all domains. This is desired behavior. 
In this piece of code introduced in #1954 we forgot to check the length of `ALLOWED_DOMAINS`. As a result empty `ALLOWED_DOMAINS` in self-hosted installations will be equivalent to all domains being invalid. As a workaround new users' domains have to be explicitly whitelisted (which is a big pain as we can't even wildcard it or smth).
https://github.com/outline/outline/blob/390a1343b788af56ad52f9bb267edf82e65920bf/server/commands/teamCreator.ts#L59-L75
Add …
=> Fix: consistently check allowed domains

server/policies/document.ts
Should be able to unstar archived and trashed documents otherwise they're "stuck" in the sidebar
=> fix: Should be able to unstar archived and trashed documents

app/editor/components/Styles.ts, shared/editor/nodes/CodeFence.ts, shared/editor/nodes/Notice.tsx
Also wraps copy and select language in another div so that they can layout next to each other, previously they never appeared together so were absolutely positioned.
closes #2979
=> fix: Ensure copy code button appears in collab editing

server/migrations/20220127000000-index-fixes.js
There were several compound db indexes left from the early days where it seems like `id` was added as the first field by mistake, these indexes should be largely useless.
=> chore: Database index improvements

server/utils/zip.ts
Previously this was querying attachments that have been uploaded at some point for a document rather than attachments that are _currently_ referenced from the document.
closes #2578
=> fix: Images no longer in original document not included in export 

app/models/BaseModel.ts, app/stores/AuthStore.ts
I'm not sure exactly when this regression occurred, but at some point serializing these stores to localStorage stopped working due to a serialization loop. It may have been with the TS conversion (likely).
=> fix: Auth persistence to `localStorage`

app/components/ContentEditable.tsx, app/components/Heading.ts, app/hooks/useEmojiWidth.ts, app/scenes/Collection.tsx, app/scenes/Document/components/EditableTitle.tsx
More keylining, aligns the text of the collection name with the content below rather than the icon.
=> Inset icon in collection headers, minor ContentEditable refactor

app/actions/index.ts, app/hooks/useCommandBarActions.ts, app/scenes/Collection.tsx
The edit collection action was always happening with the previous collection.
=> fix: sync the correct collection with edit action

app/scenes/DocumentMove.tsx
=> fix: Reuse `InputSearch` style for move dialog

app/components/Sidebar/Shared.tsx, app/components/Sidebar/components/SharedDocumentLink.tsx, app/scenes/Document/Shared.tsx, app/stores/UiStore.ts
Removes the requirement for the `documents.info` request to complete before updating the state of the shared sidebar, this makes navigation feel much more responsive on shared links with nested docs.
=> perf: Navigation of shared trees feels slow

app/scenes/Document/components/Document.tsx, app/scenes/Document/components/Header.tsx
=> fix: Hide TOC toggle on publicly shared links if there are no headings

server/collaboration/persistence.ts, server/commands/documentPermanentDeleter.ts, server/commands/documentUpdater.ts, server/models/Document.ts, server/models/Share.ts, server/routes/api/utils.ts
Excludes `state` from default columns, renamed `withUnpublished` -> `withDrafts`
=> perf: Don't load CRDT state from database by default

app/components/ActionButton.tsx, app/components/NudeButton.tsx, app/components/Sidebar/components/CollectionLink.tsx, app/components/Star.tsx, app/components/Tooltip.tsx, app/hooks/useActionContext.ts, app/types.ts
Working towards making "actions" the central definition of how interactions are defined in the UI. Adds the ability to construct a button from an action easily.
In the future we can also automatically build a context menu if the action has children
=> chore: Allow `Button` s to take action prop

app/components/ContextMenu/index.tsx
If the entire component is unmounted then the state got stuck as if a context menu is open, preventing sidebar collapse.
=> fix: Sidebar cannot collapse after visiting settings

server/commands/documentMover.test.ts, server/commands/documentMover.ts, server/routes/api/attachments.ts
Towards #3239
This logic to copy attachments when moving documents no longer makes sense as the markdown is no longer the canonical copy of the document since `document.state` was introduced, replacing the attachment urls here will literally be overridden the next time an edit is made.
The better approach is to slightly loosen the attachment permissions so that an attachment can be viewed as long as:
a) you're on the right team
b) you have the attachment id
=> perf: Stop copying attachments when moving documents

server/models/Collection.test.ts, server/models/Collection.ts, server/routes/api/documents.ts
use the new method on server document model that checks via traversing parent ids rather than using the collection structure json
=> chore: change the way that share permissions are checked on child docs

app/components/ContentEditable.tsx, app/scenes/Document/components/EditableTitle.tsx, app/scenes/Document/components/Editor.tsx, shared/editor/packages/basic.ts, shared/editor/plugins/DateTime.ts, shared/utils/date.ts
Suggested here: https://github.com/outline/outline/discussions/3306 – supported in title and body:
`/date`
`/time`
`/datetime`
=> feat: Add patterns to insert current date and time into doc

shared/editor/rules/emoji.ts
=> fix: `::` symbols appearing between lines when pasting plaintext

app/models/Document.ts, app/scenes/Document/components/Document.tsx
I looked at doing this from the side of the collaboration server but I feel like it introduces more race conditions honestly. There are two edge cases for client-side that I can see but neither feels terrible considering the current behavior:
1. two people are looking at a totally empty doc and the creator leaves causing it to be deleted, in this case it can be restored.
2. close tab with totally empty doc means it won't have a chance to cleanup so draft is left
closes #3179
=> fix: Cleanup totally empty drafts on leave

server/policies/collection.ts, server/routes/api/collections.test.ts
Admins should always be able to update and delete collections that they can view, regardless of it's other permissions.
Note: This does not change the list of collections visible in the sidebar.
closes #3331
=> fix: Allow admin edit/update access to all collections

.circleci/config.yml
Update from deprecated images and split build so it's easier to tell what failed and faster to pass.
=> chore: CircleCI Images

app/components/Collaborators.tsx, app/stores/BaseStore.ts, server/routes/api/users.test.ts, server/routes/api/users.ts
- Change usage from `users.info` loop to `users.list` request
- Fix logic to make less requests in useEffect
Note: The collaborators can change over time, which is why we can't just make this request once on mount and must check when the data changes to see if any more user profiles need loading.
closes #3267
=> fix: `users.info` request flood

server/models/Document.ts, server/routes/api/documents.ts
=> fix: Archived documents should be filtered from `getChildDocumentIds`

app/components/CollectionDescription.tsx, app/components/Editor.tsx, app/scenes/Document/components/Editor.tsx, shared/editor/commands/insertFiles.ts
This is weird, it works most of the time but I'm seeing drop events not triggered at the browser level sometimes. Trying to dig into when that's the case.
closes #3372
=> fix: Capture drop events in clickable padding below editor

server/models/Collection.test.ts, server/models/Document.test.ts, server/models/Document.ts, shared/utils/urlHelpers.ts
Fixes #3423
This PR refactors the `Document.findByPk` method to not require the
`slug` portion of the urlID.
Before this function accepted two different 'formats' for the ID.
- The `uuid` ID of the Document
- The full `urlID` which looked something like
`some-document-1234567890`
However the `some-document` slug portion of this identifier wasn't
actually used when looking for a document.
We now allow searching by JUST the postfix of the `urlID`, in the above
example that is `1234567890`.
We do this via a new Regex pattern to match on that just looks for the
right looking id alone, without the prefix.
This codepath looks the same as when we find it by the full `urlID`
besides the different regex that we match on.
The issue #3423 mentions that this should apply to all the API
endpoints. I …
=> feat: Allow Document to be fetched without Slug

app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/useCollectionDocuments.ts, app/models/Collection.ts, app/scenes/Collection.tsx, app/stores/DocumentsStore.ts, server/migrations/20220430043135-collection-sort-backfill.js, server/models/Collection.ts, server/presenters/collection.ts, shared/utils/collections.ts
Also backfills the `sort` column to reduce ongoing code complexity
closes #3466
=> perf: Move collection sorting to frontend

.env.sample, docker-compose.yml, server/redis.ts, server/services/websockets.ts, server/utils/queue.ts, server/utils/updates.ts
As mentioned in #2608 we need support for Redis Sentinel to increase fault tolerance. This PR makes the all `ioredis` client options available to administrators by setting `REDIS_URL` to `ioredis://<base64 encoded json>` instead of the usual `redis(s)://` URL (which will still work).
I first started to implement parsing of a custom `redis+sentinel://` URI scheme, which is not officially supported by redis, but used by some other redis client projects. Then I realized that I also need access to some other TLS related options. So I came up with the current solution, which basically gives us access to all redis related options and adds minimal complexity / maintenance burden to this project (as opposed to parsing a bunch of options to just hand them down to `ioredis`).
I realize that this …
=> feat: make ioredis configurable via environment variables

app/components/PaginatedList.tsx, yarn.lock
the internal render function was being run more than once for every render of the paginated list component, so previous header was not reset
=> fix: paginated list history headings were not rendering when there was only one unique heading

app/components/Collaborators.tsx, server/models/View.ts, server/routes/api/views.test.ts, server/routes/api/views.ts
It can be a bit weird to show folks that have left your company front-and-center at the top of documents.
- Hide in facepile
- Hide in list of viewers
=> fix: Don't show suspended users in document facepile

app/scenes/Settings/Slack.tsx, server/routes/api/hooks.ts
Users often expect search in Slack to "just work" when they authenticate to Outline with Google. This provides just that as long as the email addresses match.
=> feat: Match incoming search requests using confirmed email as fallback

.github/workflows/stale.yml
the github action "Close Stale PRs" fails with error "`The workflow is not valid. .github/workflows/stale.yml (Line: 28, Col: 13): A sequence was not expected`"
=> Fix github action for stale issues

.github/workflows/codeql-analysis.yml
v1 will be declared deprecated starting dec' 22
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> upgrade CodeQL action to v2

.env.sample, docker-compose.yml
The wrong Redis port is specified in the sample file, in the [Documentation](https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t) is an example docker-compose.yml using the correct port for Redis.
To avoid confusion I have updated it in the sample.env
=> Update redis port in sample env file

app/menus/UserMenu.tsx, app/stores/AuthStore.ts, server/policies/user.ts, server/routes/api/users.test.ts, server/routes/api/users.ts
Also removes requirement to pass 'confirmation' to users.delete. I think both of these checks were well-meaning, but ultimately not very useful.
closes #3604
=> fix: Unable to delete user via API

app/stores/AuthStore.ts, server/models/Event.ts, server/routes/api/auth.test.ts, server/routes/api/auth.ts, server/types.ts
This revokes all previously issued sessions on sign-out so even if the access token has been copied elsewhere it will no longer be usable. Also recording an event for sign-out, so that's a nice improvement too.
The small UX regression here is that logged in sessions on other browsers/computers will also get signed out, but this feels like a pragmatic trade-off for a rarely used action.
=> fix: Previously provisioned JWT's should be revoked on signout

server/models/Document.ts, server/models/decorators/Length.ts, server/routes/api/documents.test.ts
Fixes error when importing document through `ImportTask` with a title longer than 100 chars.
Uses same strategy as in
https://github.com/outline/outline/blob/68dd76cfa37cc4559ffc323937456b8afb652889/server/commands/documentImporter.ts#L224
Closes #3705
=> feat: Custom Length decorator for UTF-8 chars len 

.gitignore, app/scenes/Login/Notices.tsx, server/errors.ts, server/routes/auth/providers/google.ts
As discussed in the [slack thread](https://getoutline.slack.com/archives/DKTBDD5EU/p1656075504147239)
New messaging
=> fix: show a distinct error message when a user tries to create an account using a personal gmail

app/scenes/Document/components/ShareButton.tsx, app/scenes/Document/components/SharePopover.tsx
fix: Docs appear to be publicly shared when sharing previously enabled
closes #3708
=> fix: Don't show /share/ link in popover when team sharing disabled

server/collaboration/PersistenceExtension.ts, server/commands/documentCollaborativeUpdater.ts, server/commands/documentCreator.ts, server/commands/documentLoader.ts, server/commands/userInviter.ts, server/queues/processors/RevisionsProcessor.ts, server/queues/tasks/DeliverWebhookTask.ts, server/queues/tasks/ExportMarkdownZipTask.ts, server/queues/tasks/ImportTask.ts, server/routes/api/auth.ts, server/routes/api/collections.ts, server/routes/api/documents.ts, server/routes/api/fileOperations.ts, server/routes/api/groups.ts, server/routes/api/hooks.ts, server/routes/api/pins.ts
We already have a typescript-safe alternative in `rejectOnEmpty`.
=> chore: Remove over-usage of invariant

server/models/Collection.ts, server/models/Document.ts, server/models/Group.ts, server/models/Team.ts, server/models/TeamDomain.ts, server/models/User.ts, server/models/WebhookSubscription.ts, server/models/validators/Length.ts, server/models/validators/NotContainsUrl.ts
Add model-level protections so that long strings do not cause database insertion errors.
=> fix: Add additional model validations

app/components/SocketProvider.tsx, app/scenes/Document/components/DataLoader.tsx, app/scenes/Document/components/Document.tsx, app/scenes/Document/index.tsx, app/stores/BaseStore.ts, app/stores/CollectionsStore.ts, app/utils/ApiClient.ts
This also fixes an issue where if a document is deleted or your access is removed while viewing the document it would remain on screen.
In the process I converted `DataLoader` from a class component with local copies of data to a functional component that relies on the stores. So this is the thing to test in all it's variances. This was required as the class was caching the model.
=> fix: Models are not all removed from local store upon access change

app/stores/AuthStore.ts
- fixes a bug that left user, team and policy information in localstorage after logout.
- the problem was that localstore was being cleared but the store itself was not, so `autorun` repopulated the values when `team` or `token` was modified
=> Fix: clear localstore after logout

app/components/Sidebar/App.tsx, app/routes/authenticated.tsx, server/middlewares/authentication.ts, server/models/User.ts, server/routes/api/apiKeys.ts, server/routes/api/documents.test.ts, server/routes/api/documents.ts, server/routes/api/fileOperations.ts, server/routes/api/webhookSubscriptions.ts, server/routes/auth/providers/slack.ts, server/test/factories.ts, server/types.ts
Another layer in the onion of security and performance.
=> feat: Adds route-level role filtering. 

server/commands/userCreator.test.ts, server/commands/userCreator.ts, server/routes/api/team.test.ts, server/test/factories.ts
- when a user signs in via SSO, we look up existing user records on the same team by email and associate the SSO auth with that record if found
- this essentially treats all existing user records as if they were "invites"
=> Feat: add auth provider to users on sign in

server/index.ts, server/utils/startup.ts
PR prevents server startup if migrations are outstanding.
``` shell
[api] info: [email] SMTP_USERNAME not provided, generating test account...
[api] Running Outline in development mode. To run Outline in production [omit]
[api] You have pending migrations
[api] 1. 20220702132722-add-webhooks-deleted-at.js
[api] Please run `yarn sequelize db:migrate` to run all pending migrations
[api] node build/server/index.js --services=collaboration,websockets, [omit]
```
``` shell
❯ yarn sequelize db:migrate
Sequelize CLI [Node: 16.15.1, CLI: 6.4.1, ORM: 6.20.1]
Loaded configuration file "server/config/database.json".
Using environment "development".
== 20220702132722-add-webhooks-deleted-at: migrating =======
== 20220702132722-add-webhooks-deleted-at: migrated (0.012s)
Done in 0.49s
```
``` shell …
```
=> feat: Add pending migrations check during startup

app/editor/components/Styles.ts, shared/editor/commands/splitHeading.ts
Should create a new heading of the same type above, currently the cursor disappears into the collapsed heading creating a new, hidden, paragraph.
closes #3753
=> fix: Enter at beginning of collapsed heading

shared/editor/nodes/Image.tsx
`svg+xml` image type wasn't being set properly because
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/shared/editor/nodes/Image.tsx#L122
which uses 
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/shared/utils/files.ts#L26
particularly 
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/shared/utils/files.ts#L36
would apply like 
``` js
"image/svg+xml".split('/')[1]
"svg+xml"
```
PR does this
``` js
"image/svg+xml".split('/')[1].split('+')[0]
"svg"
"image/jpeg".split('/')[1].split('+')[0]
"jpeg"
```
Download link is set here
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/shared/editor/nodes/Image.tsx#L128
Closes #3768
=> fix: `svg+xml` image type ext not assigned properly

app/editor/components/SelectionToolbar.tsx, app/editor/menus/formatting.ts
This 
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/app/editor/components/SelectionToolbar.tsx#L184
combined with
https://github.com/outline/outline/blob/e92d68a0a3328227daabea0d2db2db8f3efbb6d7/app/editor/components/SelectionToolbar.tsx#L188-L190
takes care of code blocks like
```
```
PR adds check for `inline` code
| Before  | After |
| ------------- | ------------- |
|   ![Screenshot 2022-07-12 at 22-03-42 test - outline-dev-test](https://user-images.githubusercontent.com/58817502/178547014-d2ec8132-1e95-4d55-898a-503e76437c82.png)                |          ![Screenshot 2022-07-12 at 22-17-04 test - outline-dev-test](https://user-images.githubusercontent.com/58817502/178547198-51136b95-df31-4f1b-9646-b67793e9525f.png)       |
Mentioned in  #3742
=> fix: ToolbarMenu popup on inline code selection

app/scenes/Settings/Security.tsx, app/stores/AuthStore.ts
Note: This is my first commit into this repo; I have used prettier to ensure the styling matches, but could not find any unit tests to add/modify. Please let me know if I have missed something; I have thoroughly manually tested these changes.
Please also let me know if this commit overreaches its goal or goes against some underlying design goals that I was not aware of!
---
This change consists of two commits.
The first one fixes an existing bug: The change handlers for the toggles on the Security page were submitting all data on toggle, including the "allowed domains" config which had its own save button. As a result, if a user added some domains (without saving), then changed a toggle value, their domains would be updated. Similarly, the "save" button also submitted all toggle states, …
=> #3665: Save button should not be shown when adding and removing a domain row

shared/editor/nodes/CodeFence.ts
PR adds ability to select single line by triple clicking in code blocks. Previously a single click will place cursor, two will select a word and three will select entire block. 4th click will then deselect everything and place cursor.
Now single click will display cursor inside the block, double will highlight a word.
4 consecutive clicks will select the entire block.
These clicks should be roughly even, 3 quick ones and 1 slow will select a line and deselect it at final click.
Closes  #3304
=> feat(editor): Ability to select line in codeblocks

app/editor/components/Styles.ts, shared/editor/nodes/Emoji.tsx
This took _surprisingly long_ to debug, had to go down a very deep and convoluted rabbit hole but finally figured it out!
---
Here's a clip describing the issue (Two parts, bug then solution)
https://user-images.githubusercontent.com/58817502/179033019-18e27163-47a7-4238-967d-3a3da6f312a9.mp4
---
Finding this disappeared cursor becomes a guessing game if there are more than a few emojis in the document. Only way to fix it was clicking around a lot until you see it pop up somewhere.
---
Here are some reference that should explain why that happens.
ProseMirror issue 
- 1241
- 1069
- 472
[Source](https://github.com/ProseMirror/prosemirror-view/blob/089aa9bd8f261d8181782bc5f8c46c5dc5e11a5f/src/viewdesc.js#L1271)
[Solution hint](https://github.com/Patternslib/pat-tiptap/pull/8/files)
[About …
=> fix: Cursor disappearing behind emoji

shared/editor/nodes/CodeFence.ts
=> fix: Use previous language when creating code block from markdown shortcut

app/components/IconPicker.tsx, app/scenes/CollectionNew.tsx, server/routes/api/collections.test.ts, server/routes/api/collections.ts, shared/random.ts, shared/utils/collections.ts
Fixes #3900 
Choose a random color from a shared color palette between backend and frontend during collection creation.
=> feat: Choose random color on collection creation

.eslintrc, app/editor/index.tsx, app/scenes/GroupEdit.tsx, app/scenes/GroupNew.tsx, app/stores/DocumentsStore.ts, app/utils/browser.ts, server/__mocks__/bull.ts, server/commands/teamUpdater.ts, server/models/Group.ts, server/presenters/webhook.ts, server/routes/auth/providers/index.ts, server/utils/turndown/breaks.ts, server/utils/turndown/confluence-code-block.ts, server/utils/turndown/confluence-task-list.ts, server/utils/validators.ts, shared/editor/nodes/Image.tsx, shared/editor/rules/notices.ts
`yarn lint --fix` will now auto-correct.
ref: https://github.com/outline/outline/pull/3935#discussion_r943397751
=> chore: Add eslint rule for object shorthand

app/scenes/CollectionExport.tsx, app/scenes/Settings/Export.tsx, app/scenes/Settings/Notifications.tsx, server/emails/templates/ExportFailureEmail.tsx, server/emails/templates/ExportSuccessEmail.tsx, server/models/NotificationSetting.ts, server/models/User.ts, server/queues/tasks/ExportMarkdownZipTask.ts, shared/i18n/locales/en_US/translation.json
See: #3934
This adds a notification event called `emails.export_completed`. When a user is subscribed to this event, both success and failure emails can be sent when an export they requested is completed. Neither can be sent if the user is not subscribed to the event.
A toggle has been added to the notifications settings page for `emails.export_completed`. New users are automatically subscribed to this event when their accounts are created.
The secondary text on the export page in settings has been updated to reference how email notifications are optional, as has the toast shown when exporting a collection.
:)
=> Add optional export notifications

server/emails/mailer.tsx, server/emails/templates/components/Header.tsx
Removes requirement for images to be publicly accessible to work in email body.
closes #3870
=> Reference email image by cid for self hosted instances

app/editor/components/Styles.ts, app/styles/globals.ts
This first commit fixes problem number 6 in issue https://github.com/outline/outline/issues/4001, when printing a document.
The button "Show Source" in mermaid diagrams should be hidden, when printing a document.
The third commit fixes the problems number 1, 3, 4, 5, 7 in issue https://github.com/outline/outline/issues/4001, where backgrounds and task checkboxes are not visible when printing
=> Content is displayed wrongly when printing / Save as PDF

server/middlewares/methodOverride.ts, server/routes/api/attachments.ts, server/routes/api/cron.ts, server/routes/api/documents.ts, server/routes/api/index.test.ts, server/routes/api/index.ts, server/routes/api/notificationSettings.ts, server/test/env.ts, server/types.ts, server/validation.ts
=> fix: Remove ability to use `GET` for RPC API requests by default

app/scenes/DocumentDelete.tsx
fixes #4107
* Removes return inside the if statement that checks if the parent is available in the store to allow the rest of the code to be executed. 
* Else clause added to above if statement to redirect to collection if parent is not available in the store.
* Original redirect to collection wrapped in else in case there is no parent.
Sorry if there's a cleaner way to do this so that code isn't duplicated.
=> fix: Dialog doesn't close after deleting a document with a parent

.gitignore, docker-compose.yml, shared/editor/nodes/Table.ts, shared/editor/queries/getRowIndex.ts
Solves issue #4129 
I changed getRowIndex to return the row index whenever the user writes in a table cell. It still returns undefined if not in a table. Also, on Enter key pressed, we get the index from the modified getRowIndex and use it to add new row below the current one.
=> Enter in table cell adds a row after the current one

shared/editor/components/Styles.ts
Removes background-color from del selector, which is only used for strikethrough text.
Fixes #4200
=> fix: remove strikethrough text background

docker-compose.yml
Hello 👋 
I tried to setup Ouline for local development with `cp .env.sample .env` and `make up` as suggested [here](https://app.getoutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e/doc/local-development-5hEhFRXow7) and ran into this error:
```
Loaded configuration file "server/config/database.json".
Using environment "production".
ERROR: connect ECONNREFUSED 127.0.0.1:5432
error Command failed with exit code 1.
```
I believe this is due to exposing the wrong port in `docker-compose.yml`. 
I'm not sure if this is intended, a typo, or leftovers from #1271 - let me know what you think!
=> feat(build): update postgres port in docker-compose.yml

.env.sample, app.json, app/utils/sentry.ts, server/env.ts, server/presenters/env.ts, shared/types.ts
This adds a `SENTRY_TUNNEL` config option to bypass adblockers when sending reports to sentry (a sentry tunnel basically acts as a proxy). This also fixes some spelling mistakes in the sample environment file
=> Add `SENTRY_TUNNEL` option

server/routes/app.ts
Outline is deployed in docker containers, the disk is not expected to change so we can keep the html in memory.
=> perf: Don't go to disk for html more than once

app/components/PlaceholderText.tsx
Converts `PlaceholderText` component from class component to functional component as part of #4204.
Component specific quirks to look out for during review:
- Previous class level field - `width` is now migrated to a `widthRef`
- Previous shouldComponentUpdate is now migrated to React.memo using the custom comparison function
=> chore: convert PlaceholderText component to functional component (#4204)

app/components/Avatar/Avatar.tsx
Converts Avatar component to function component as per #4204 
Brief summary:
1. Removed `@observable` in favour of `React.useState` - not sure if that's the correct migration strategy. 
2. Removed `@observer` in favour of wrapping `Avatar` with `observer`
=> chore: convert Avatar component to functional component (#4204)

app/scenes/CollectionPermissions/AddGroupsToCollection.tsx
Converts `AddPeopleToGroup` component to functional component. 
Brief summary of changes:
1.  Used `useBoolean` hook to keep track of `newGroupModalOpen` state 
2. Used `useState` hook to keep track of `query`
3. Created the `debouncedFetch` using `useMemo` hook and to keep the dependencies minimal took the `query` in the argument instead of reading from the state variable and adding it to useMemo deps.
4. Removed the `withStores` and `withTranslation` hocs in favour of `useStores` and `useTranslation` hooks and removed the `@observer` directive as well.
=> chore: convert AddGroupToCollection component to functional component (#4204)

server/database/sequelize.ts, server/env.ts
Missing `DATABASE_URL` in configuration was causing server to crash rather than produce a human readable error, see:
https://github.com/outline/outline/discussions/4408
This also fixes `DATABASE_CONNECTION_POOL_URL` never being evaluated as it sat behind the required `DATABASE_URL`.
=> fix: `DATABASE_URL` missing in env does not produce validation error

app/components/Editor.tsx, app/scenes/Settings/components/DropToImport.tsx, app/scenes/Settings/components/ImageUpload.tsx, app/utils/files.ts, server/env.ts, server/migrations/20221120151710-attachment-expiry.js, server/models/Attachment.ts, server/models/FileOperation.ts, server/models/helpers/AttachmentHelper.ts, server/presenters/attachment.ts, server/presenters/index.ts, server/queues/tasks/CleanupExpiredAttachmentsTask.ts, server/routes/api/attachments.test.ts, server/routes/api/attachments.ts, server/routes/api/cron.ts, server/routes/api/documents.ts, server/utils/s3.ts, shared/types.ts
- Allows configurable larger uploads for data imports
- Enforces data uploads are private and expire(delete) quickly to minimize abuse
- Cleanup/refactor of `attachments.create` endpoint
- Deprecates `public` option on `attachments.create` payload
=> feat: Allow data imports larger than the standard attachment size

server/models/decorators/Encrypted.ts
if there isn't Token (refreshToken for example) function getEncryptedColumn returns empty object and break expression like "!this.refreshToken"
=> fix: getEncryptedColumn for empty token

server/commands/userProvisioner.ts
Sorry for that, but previous pull request had wrong commit (((
if OIDC provider gets user_id as integer Postgres failed query because providerId must be a string
=> if OIDC provider gets user_id as integer Postgres failed query 

.github/workflows/calibreapp-image-actions.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

app/components/Input.tsx, app/components/InputSearch.tsx, app/components/InputSearchPage.tsx, app/scenes/Settings/GoogleAnalytics.tsx, app/scenes/Settings/SelfHosted.tsx, app/scenes/Settings/components/WebhookSubscriptionForm.tsx, app/scenes/UserDelete.tsx
Remove confusing `ReactHookWrappedInput` workaround
issue #4204
=> chore: Move Input to functional component

app/components/DocumentBreadcrumb.tsx, app/components/Sidebar/components/CollectionLink.tsx, app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/DraggableCollectionLink.tsx, app/models/Collection.ts, server/commands/documentMover.ts, server/policies/document.test.ts, server/policies/document.ts
I don't really remember why we thought it was a good idea to prevent this, it's very useful to move a draft doc before you publish it.
This will use a new move modal once https://github.com/outline/outline/pull/4582 is complete, but for now the move UI remains unchanged.
closes #4644
=> feat: Allow moving draft documents

app/scenes/DocumentMove.tsx, server/commands/documentMover.test.ts, server/commands/documentMover.ts, server/models/Collection.test.ts, server/models/Collection.ts, server/models/Document.ts, server/routes/api/documents/documents.test.ts
- Don't override the `toJSON` method, renamed to `toNavigationNode`
- Made more resilient so the method returns the correct result at any time
- Allow collection `documentStructure` to self-heal
=> chore: Improvements to document move behavior

server/models/Attachment.ts, server/models/FileOperation.ts, server/queues/tasks/ExportDocumentTreeTask.ts, server/queues/tasks/ImportMarkdownZipTask.test.ts, server/queues/tasks/ImportMarkdownZipTask.ts, server/queues/tasks/ImportNotionTask.test.ts, server/queues/tasks/ImportNotionTask.ts, server/queues/tasks/ImportTask.ts, server/utils/s3.ts
This should address issues where the task processor crashes due to extremely large attachments.
=> chore: Use streams where possible in import/export to lower memory usage

app/components/PaginatedList.tsx, app/components/Sidebar/components/Collections.tsx, server/routes/api/collections.ts
Also reduced amount of collections loading at once
closes #4809
=> fix: Issue in PaginatedList does not always load more

app/components/Editor.tsx, app/components/HoverPreview.tsx, app/editor/index.tsx, shared/editor/marks/Link.tsx
closes #4837 
~May refactor `onHoverLink` here to pass the element rather than the event through, that will simplify things~
=> fix: Links with strikethrough do not have hover preview

package.json
Everything seems to work with Node 18, so I upgraded the max allowed node version to 18.
=> Upgrade maximum allowed Node version to 18

package.json
Reverts outline/outline#4844
Sorry, this broke Heroku deploy due to Webpack dep – need to wait until Vite is merged.
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
```
=> Revert "Upgrade maximum allowed Node version to 18"

shared/editor/plugins/Prism.ts
Aliases "vb" or "vba" need to be used for Prism, rather than "visualbasic".
=> fix: Visual Basic syntax higlighting (#4769)

shared/editor/components/Styles.ts, shared/editor/plugins/Prism.ts
Move line numbers to pseudo element, tested in Chrome/Safari/Firefox. Previously line numbers were another widget element inserted at the beginning of the code block which was somehow affecting cursor position on re-render.
closes #4895
=> fix: Cursor position changes on new token with line numbers enabled

.jestconfig.json, plugins/email/server/auth/email.test.ts, plugins/email/server/auth/email.ts, plugins/slack/server/api/hooks.test.ts, plugins/webhooks/server/processors/WebhookProcessor.test.ts, server/models/User.ts, server/routes/api/index.ts, shared/i18n/locales/en_US/translation.json
Re-enabled tests in plugin directory (Needs a little more work yet)
closes #5049
=> fix: Users should not be redirected to disabled authentication providers (#5055

shared/editor/nodes/Math.ts, shared/editor/nodes/MathBlock.ts, shared/editor/rules/math.ts
This change will unfortunately regress any shared links with Math blocks in them until they are re-saved, I don't see a way around that for now.
closes #4778
=> fix: Impossible to type more than one dollar symbol in a paragraph without triggering LaTeX

server/policies/document.test.ts, server/policies/document.ts, server/routes/api/comments/comments.ts
Closes #5065 
Although for now it's just an alias of the `read` permission but can be later modified to support tighter constraints enforced by admins specifically for _commenting_ - allow/disallow a `group` of users, allow/disallow commenting altogether on a document etc.
=> Additional policy regarding comments on a document

server/utils/ProsemirrorHelper.test.ts, shared/utils/ProsemirrorHelper.ts
Fixes an issue where the trim function would remove the only paragraph leaving the editor in a working, but confusing state. Also allows trim to remove multiple empty paragraphs rather than just one.
=> fix: Draft comment on text gets into a strange state when unfocused

app/components/Breadcrumb.tsx, app/components/CommandBarItem.tsx, app/components/DocumentCard.tsx, app/components/DocumentExplorerNode.tsx, app/components/DocumentExplorerSearchResult.tsx, app/components/DocumentMeta.tsx, app/components/Input.tsx, app/components/List/Item.tsx, app/components/ResizingHeightContainer.tsx, app/components/SearchListItem.tsx, app/editor/components/FloatingToolbar.tsx, app/editor/components/Input.tsx, app/editor/components/LinkEditor.tsx, app/editor/components/LinkSearchResult.tsx, app/editor/components/LinkToolbar.tsx, app/editor/components/SelectionToolbar.tsx, app/editor/index.tsx, app/menus/DocumentMenu.tsx, app/menus/NewTemplateMenu.tsx, app/menus/TemplatesMenu.tsx, app/scenes/Document/components/CommentForm.tsx, app/scenes/Document/components/CommentThread.tsx, app/scenes/Document/components/ReferenceListItem.tsx, app/scenes/Document/components/SidebarLayout.tsx, app/scenes/DocumentMove.tsx, app/scenes/DocumentPublish.tsx, app/styles/index.ts, shared/editor/components/Widget.tsx, shared/editor/nodes/index.ts
- Comment draft does not show "Post" button when unfocused (but should)
- Fixed flash of toolbar when closing on wide screens
- Fixed nesting of comments with other marks, comments are no longer broken up by links and formatting
- Fixed cannot use arrow keys to navigate suggested link search results
- Improved styling of link editor
- Animation in link editor search results
- Link editor now adjusts size to fit in comment sidebar
- Introduced a `mixin` for text ellipses
=> fix: Wide selection of comment toolbar fixes (#5160

app/components/ClickablePadding.ts, app/components/Editor.tsx, app/editor/index.tsx, app/scenes/Document/components/Editor.tsx, shared/editor/components/Styles.ts
Currently it can be quite frustrating to place your cursor right at the beginning of a paragraph as the area to the left is not part of the editor and clicking doesn't put the cursor at the beginning of the line – not any more!
=> Adds a 60px area to the left and right of editable area (#5197

shared/editor/lib/ExtensionManager.ts, shared/editor/marks/Code.ts
Previously inline code excluded all other marks.
=> fix: Allow strikethrough of inline code (#5207

Makefile, server/index.ts, server/utils/startup.ts
=> Autorun migrations in community edition

app/utils/routeHelpers.ts
This returns the window location's host AND protocol, instead of just host. In the only usage of this which I could find, it's for the "Copy link" feature in the comments menu.
This allows the same behaviour as all other share options, which return a fully valid URL.
=> Return window origin instead of host

server/models/helpers/DocumentHelper.tsx, server/utils/s3.ts
The parameter actually expects seconds and not milliseconds, according to S3 documentation:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
This was confusing me when debugging an issue with S3.
=> Remove "millisecond" suffix from getSignedUrl() function

server/models/Attachment.ts, server/models/FileOperation.ts, server/queues/tasks/ExportDocumentTreeTask.ts, server/queues/tasks/ExportJSONTask.ts, server/utils/ZipHelper.ts, server/utils/s3.ts
- Refactor attachment downloads during export to use promises instead of streams
- Date attachments in zip file correctly
- Add more debugging for memory usage during zip write
This partially reverts https://github.com/outline/outline/pull/4796 and instead of using streams or Blobs we pass unresolved promises to JSZip.
closes #5256
=> fix: Refactor attachment downloads during export to use promises (#5294

app/components/AuthenticatedLayout.tsx, app/components/Editor.tsx, app/components/IconPicker.tsx, app/components/InputColor.tsx, app/components/TableFromParams.tsx, app/components/Time.tsx, app/routes/authenticated.tsx, app/routes/index.tsx, app/scenes/Document/components/AsyncMultiplayerEditor.ts, app/utils/lazyWithRetry.ts
Automatically retry network requests when an import call fails. As the assets on the CDN are available for a long time retrying should eventually succeed.
=> Improve reliability by retrying failed imports

app/components/ExportDialog.tsx, app/models/Collection.ts, app/stores/CollectionsStore.ts, server/commands/collectionExporter.ts, server/migrations/20230621004649-add-include-attachments-file-operation.js, server/models/FileOperation.ts, server/queues/tasks/ExportDocumentTreeTask.ts, server/queues/tasks/ExportHTMLZipTask.ts, server/queues/tasks/ExportJSONTask.ts, server/queues/tasks/ExportMarkdownZipTask.ts, server/queues/tasks/ExportTask.ts, server/routes/api/collections.ts, shared/i18n/locales/en_US/translation.json
This is debugging for some failing exports, but seems useful enough – exports complete much faster when you don't need to include hundreds of mbs of files.
=> feat: Add option to not include attachments in exported data

server/collaboration/PersistenceExtension.ts, server/commands/documentCollaborativeUpdater.ts, server/commands/documentUpdater.ts, server/queues/processors/RevisionsProcessor.ts, server/routes/api/documents/documents.ts, server/routes/api/documents/schema.ts
In two scenarios it feels as though document revisions are created too late and will now be created sooner.
- Write a document revision when all collaborators leave a document
- Write a document revision when 'Done editing' in edit mode
=> Improve document revision creation

shared/editor/marks/Comment.ts
=> fix: Do not allow copy/pasting comment marks between documents

server/models/UserAuthentication.ts, server/utils/azure.ts, server/utils/oauth.ts
Parses the correct tenant ID from the access token and constructs the tenant-specific endpoint for refreshing auth in single-tenant apps.
closes #5532
=> fix: Azure single-tenant SSO tokens are unable to refresh

server/routes/app.ts, server/routes/index.ts, server/services/web.ts, server/static/index.html
Security hardening through removal of  "'unsafe-inline'", "'unsafe-eval'" CSP rules in favor of nonce-blessed script tags.
=> Add csp nonce to all inline script tags

app/components/Authenticated.tsx, app/components/WebsocketProvider.tsx, app/hooks/useCurrentToken.ts, app/scenes/Document/components/MultiplayerEditor.tsx, app/stores/AuthStore.ts, app/utils/ApiClient.ts, package.json, server/collaboration/AuthenticationExtension.ts, server/models/User.ts, server/routes/api/auth/auth.ts, server/routes/auth/index.ts, server/services/websockets.ts, server/utils/authentication.ts, server/utils/jwt.ts, server/utils/passport.ts, yarn.lock
Currently our `authToken` cookie is not http only which allows javascript access to the value – this was done so that the token could be read and passed to websockets through websocket messages however it leaves the app vulnerable to XSS vulnerabilities. 
This PR moves the auth for the main websocket to use the cookie directly, and the collaboration socket to use a new short-lived `collaborationToken` which will be sent in the `auth.info` payload and retained in memory only.
=> chore: Use `httpOnly` authentication cookie

app/components/Sidebar/components/DocumentLink.tsx, app/components/Switch.tsx, app/components/Text.ts, app/models/Document.ts, app/scenes/Document/components/Insights.tsx, server/commands/documentUpdater.ts, server/migrations/20230720002422-add-insights-control.js, server/models/Document.ts, server/policies/document.ts, server/presenters/document.ts, server/routes/api/documents/documents.ts, server/routes/api/documents/schema.ts, server/routes/api/views/views.ts, shared/i18n/locales/en_US/translation.json
Some documents contain sensitive topics, for these it's nice to disable being able to easily see who has viewed.
=> Add per-document control over who can see viewer insights

.env.sample, app/components/HoverPreview/Components.tsx, app/components/HoverPreview/HoverPreview.tsx, app/components/HoverPreview/HoverPreviewDocument.tsx, app/components/HoverPreview/HoverPreviewLink.tsx, app/components/HoverPreview/HoverPreviewMention.tsx, plugins/iframely/plugin.json, plugins/iframely/server/.babelrc, plugins/iframely/server/iframely.ts, plugins/iframely/server/unfurl.ts, server/env.ts, server/presenters/unfurls/document.ts, server/presenters/unfurls/mention.ts, server/presenters/unfurls/unfurl.ts, server/routes/api/urls/urls.test.ts, server/routes/api/urls/urls.ts, server/types.ts, server/utils/unfurl.ts, shared/types.ts
Enhances #5109 
Further improvements:
=> Preview arbitrary urls within a document

server/emails/templates/BaseEmail.tsx, server/models/Notification.ts, server/routes/api/notifications/notifications.ts
Adds a tracking pixel to outgoing email notifications allowing them to be remotely marked as read. This means in the app you won't have to manually clear notifications that you've already seen in your email client.
=> feat: Add tracking pixel to notifications for mark-as-read functionality

shared/editor/extensions/Prism.ts, shared/editor/nodes/CodeFence.ts
Adds the following languages to Outline's syntax highlighting:
- Verilog
- VHDL
=> Added syntax highlighting for the Verilog and VHDL languages

.env.sample, Makefile, package.json, plugins/email/server/auth/email.test.ts, server/env.ts, server/index.ts, server/routes/api/auth/auth.test.ts, server/routes/app.ts, server/scripts/install-local-ssl.js, server/utils/ssl.ts, vite.config.ts
Pretty much all the auth providers require SSL redirects now so it's become a development requirement – I've owned `outline.dev` for almost a year for this purpose 😄
=> Add support for SSL in development

app/scenes/Settings/SelfHosted.tsx, server/models/Integration.ts, server/routes/api/integrations/integrations.test.ts, shared/editor/embeds/Grist.tsx, shared/i18n/locales/en_US/translation.json, shared/types.ts
Add support for self hosted Grist instances.
This change adds the option to configure a grist instance url. With this you can embed urls from a self hosted grist instance.
=> feat: support self hosted grist

app/components/UserDialogs.tsx, app/models/User.ts, app/scenes/Invite.tsx, app/scenes/Settings/Members.tsx, app/stores/UsersStore.ts, server/commands/userDemoter.test.ts, server/commands/userDemoter.ts, server/commands/userInviter.test.ts, server/commands/userInviter.ts, server/models/User.ts, server/routes/api/teams/schema.ts, server/routes/api/users/schema.ts, server/routes/api/users/users.test.ts, server/routes/api/users/users.ts, shared/types.ts
Had some server errors related to incorrect payloads users were posting through the API that made me realize the switch to zod validation hadn't happened on all these endpoints.
Took the opportunity to centralize the `UserRole` type in an enum
Related #4284
=> Improve validation on `api/users` endpoints

app/components/Sidebar/Right.tsx, shared/utils/browser.ts
- Add Safari browser detect func in utils
- Apply display:block to right sidebar only on Safari Desktop  
Fixes bug that would cause sidebar contents to not display sometimes on Safari #5765
=> fix: Safari sidebar animation #5765

app/hooks/useQueryNotices.ts, app/routes/index.tsx, server/emails/templates/BaseEmail.tsx, server/emails/templates/CollectionCreatedEmail.tsx, server/emails/templates/CommentCreatedEmail.tsx, server/emails/templates/CommentMentionedEmail.tsx, server/emails/templates/ConfirmTeamDeleteEmail.tsx, server/emails/templates/ConfirmUserDeleteEmail.tsx, server/emails/templates/DocumentMentionedEmail.tsx, server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx, server/emails/templates/ExportFailureEmail.tsx, server/emails/templates/ExportSuccessEmail.tsx, server/emails/templates/InviteAcceptedEmail.tsx, server/emails/templates/InviteReminderEmail.tsx, server/emails/templates/WebhookDisabledEmail.tsx, server/emails/templates/WelcomeEmail.tsx, server/emails/templates/components/Footer.tsx, server/models/helpers/NotificationSettingsHelper.ts, server/models/helpers/SubscriptionHelper.ts, server/routes/api/notifications/notifications.ts, server/routes/api/subscriptions/schema.ts, server/routes/api/subscriptions/subscriptions.ts, shared/i18n/locales/en_US/translation.json, shared/types.ts
- Removed need to query user on all outgoing emails with unsubscribe link
- Added document specific unsubscribe link to email footer
- Small refactor of `unsubscribeUrl` logic to match pattern
- Clean up types in emails
Follow on https://github.com/outline/outline/pull/5707
=> Add document unsubscribe link in email footer

package.json, server/queues/tasks/ExportDocumentTreeTask.ts, server/routes/api/documents/documents.ts, server/routes/api/middlewares/apiWrapper.ts, server/routes/api/revisions/revisions.ts, server/utils/ZipHelper.ts, yarn.lock
When export an individual document as Markdown or HTML, if there are attachments a zip file will be returned with the attachments inside and relative paths.
closes #5293
=> feat: Return attachments when exporting an individual file

server/collaboration/ViewsExtension.ts
Using the `onAwarenessUpdate` hook resulted in the view being updated when the user comes on/offline and otherwise isn't necessarily viewing the document.  Also now updating  `user.lastActiveAt` to keep these in sync.
=> fix: Only update views in collaborative server on data change

server/policies/collection.ts
Just a typo, encountered while working on #5814 ...
=> Typo in `includesMembership` function

plugins/storage/server/api/files.test.ts, plugins/storage/server/api/files.ts, server/models/Attachment.ts, server/storage/files/LocalStorage.ts
- Adds additional strictness around unreleased `files.create` endpoint.
- Removes usage of sync nodejs methods
- Adds handling of client aborted upload part-way
Related #5763
=> fix: `files.create` permissions

shared/editor/extensions/Mermaid.ts, yarn.lock
Split from #5850, this PR only concerns with addressing #4802.
Performance improvement:
- Each diagram now maintains its rendering state.
- Updating code of one diagram only re-render its output. Before we re-render the whole doc page on each change. This is done by each diagram maintaining its current text input, and only update when the text input changes.
- Add debounce for updating the diagram.
Usability improvement:
- Display MermaidJS render error to the user, instead of just "Error rendering Diagram"
=> feat: update mermaid rendering flow

server/models/helpers/DocumentHelper.tsx, server/storage/files/LocalStorage.ts, shared/editor/components/Styles.ts, shared/editor/rules/links.ts
Signed urls are not generated, urls are relative.
closes #5932
=> fix: Links to attachments do not work in emailed notifications

app/components/WebsocketProvider.tsx, app/models/Comment.ts, app/models/Notification.ts, app/models/base/Model.ts, app/models/decorators/Field.ts, app/models/decorators/Relation.ts, app/stores/base/Store.ts
closes #5903 and creates a nice foundation for future improvements of model relationship definitions on client to match server.
Additional references can be added later to cleanup some custom logic, but keeping this small to land easily.
=> Add registering of client-side relationship properties

app/editor/components/ComponentView.tsx, app/editor/index.tsx, package.json, shared/editor/components/Image.tsx, shared/editor/components/hooks/useComponentSize.ts, yarn.lock
=> fix: Various compounding memory leaks in editor

shared/editor/commands/codeFence.ts, shared/editor/nodes/CodeFence.ts
Changes behavior of enter key in code blocks to match blockquotes.
- `Enter` on the last line should exit the code block if the line is empty
- `Shift`+`Enter` allows adding multiple newlines at end of code block
closes #5967
=> Make code block `Enter` behavior the same as quote block

server/routes/api/users/schema.ts, server/routes/api/users/users.test.ts, server/routes/api/users/users.ts
Hello !
We are using Outline API to create users and groups in outline from an external tool. We miss a way to find users' outline IDs from their email address (since "invite" does not work for already existing/invited users). We added it in users.list: this way we can fix our data and easily use the rest of the API. Would it be an interesting feature for others?
Thank you!
=> API : allow filter user list via emails

server/routes/api/attachments/attachments.ts, server/routes/api/collections/collections.ts, server/routes/api/comments/comments.ts, server/routes/api/documents/documents.ts, server/routes/api/fileOperations/fileOperations.ts, server/routes/api/stars/stars.ts, server/routes/api/teams/teams.ts
Closes #6042.
I also quickly searched through the code to identify similar cases and also changed them.
I made some observations that are probably covered by what was mentioned as the ongoing gradual migration to transaction in https://github.com/outline/outline/issues/6042#issuecomment-1773779264 but for completeness:
- Not every route that modifies the database has a transaction middleware yet. Even those that only read from the database could benefit from transaction isolation in PostgreSQL to get a consistent answer?
- Not every time a row is queried to be then modified a corresponding `UPDATE` lock is used. This may cause race conditions or loss of data in theory, but I did not thoroughly check if that is the case here.
- There are queries hidden inside functions, for example in …
=> Use transaction from middleware for more database queries

shared/editor/nodes/CodeFence.ts
Previously, on creating a new code block, Javascript was always the default option. This commit fixes that by remembering user's last language used and creating a new block with that language. 
We already had `rme-code-language` key to store users language preference. We were also checking and using the store value from this key if it existed. But we were not updating the storage to update this key when user changes the language. This commit fixes that.
Fixes #6040.
=> fix: remember prev selected lang when creating new code block

server/routes/api/groups/groups.test.ts, server/routes/api/groups/groups.ts, server/routes/api/groups/schema.ts
Hello it's me again. :)
We are still using the outline API to sync our internal groups with outline groups. We have an issue: we cannot create two groups with the same name, but we have no easy way to find the existing group with that name to update internal data.
Currently, I loop in Python on every result of `groups.list` until I find the matching name. I propose a way to filter this endpoint to lighten the load on our outline instance.
=> API - allow search of a group using its name

app/components/LanguagePrompt.tsx, app/scenes/Document/components/MultiplayerEditor.tsx, app/scenes/Settings/Details.tsx, app/scenes/Settings/Features.tsx, app/scenes/Settings/Preferences.tsx, app/scenes/Settings/Profile.tsx, app/scenes/Settings/Security.tsx, app/scenes/Settings/components/DomainManagement.tsx, app/stores/AuthStore.ts, app/stores/RootStore.ts, server/routes/api/teams/teams.ts
- It's now possible to use `team.save()` and `user.save()` as you can with other models, `updateUser` and `updateTeam` removed.
- There is no longer a second copy of the signed in user stored in the `AuthStore`
- API endpoint `teams.update` is now available
- Added missing transaction lock on `teams.update`
Continuation of https://github.com/outline/outline/commit/964d2b6bb35bec4a101043a27d28403eafd038ee refactor.
=> Cleanup and refactor `AuthStore` 

app/components/Editor.tsx, app/components/HoverPreview/HoverPreview.tsx, app/editor/index.tsx, app/hooks/usePrevious.ts, app/hooks/useRequest.ts, shared/editor/extensions/HoverPreviews.ts, shared/editor/marks/Link.tsx, shared/editor/nodes/Mention.ts, shared/editor/nodes/index.ts
Fixes an issue where briefly mousing over a link will cause an unfurl request that will show a preview card seconds later. 
- Refactor to `HoverPreviews` extension
- Nodes in the editor must now opt into previews with `use-hover-previews` in the element class
- Moved the delay logic to before `onHoverLink` is triggered
=> fix: Refactor hover previews to reduce false positives

app/components/CollectionDescription.tsx, app/components/Editor.tsx, app/components/HoverPreview/HoverPreview.tsx, app/components/Notifications/NotificationListItem.tsx, app/editor/components/BlockMenu.tsx, app/editor/components/EmojiMenu.tsx, app/editor/components/MentionMenu.tsx, app/editor/components/SuggestionsMenu.tsx, app/editor/extensions/BlockMenu.tsx, app/editor/extensions/EmojiMenu.tsx, app/editor/extensions/FindAndReplace.ts, app/editor/extensions/FindAndReplace.tsx, app/editor/extensions/HoverPreviews.tsx, app/editor/extensions/MentionMenu.tsx, app/editor/extensions/Suggestion.ts, app/editor/index.tsx, app/editor/menus/block.tsx, app/scenes/Document/components/CommentEditor.tsx, app/scenes/Document/components/Editor.tsx, shared/editor/extensions/HoverPreviews.tsx, shared/editor/extensions/Suggestion.tsx, shared/editor/lib/Extension.ts, shared/editor/lib/ExtensionManager.ts, shared/editor/nodes/Emoji.tsx, shared/editor/nodes/Mention.ts, shared/editor/nodes/index.ts, shared/editor/plugins/Suggestions.ts
This reduces a lot of plumbing and callbacks, as the extension can control the component directly rather than needing to pipe data through callbacks to the Editor state. It also means that components are only in the React tree when the extension is used, automatically.
Next up, link and selection toolbars – these will need a little more thought as they interact with `isEditorFocused` state and will need to share state, leaving for a separate PR.
=> Refactor Editor components to be injected by associated extension

.env.sample, server/env.ts, server/services/web.ts
Fixes #6119 
For now, the fix seems to be to relax CSP as hinted in https://github.com/facebook/react/issues/17997. Note that CSP is only changed for non-prod environments.
=> Make `react-devtools` extension work for outline in Firefox

server/middlewares/authentication.ts
Related to #6061 
When accessing a public link with a stale `accessToken` in cookies, the `/documents.info` endpoint returns a 401 `Invalid token` and the public document can't be accessed (you need to go to the homepage re-login the instance first or clear your cookies/use a private browsing session).
This PR tries to fix this issue by enforcing the `optional` field in the auth middleware even when an `accessToken` is present.
(Auth source: Keycloak OpenID Connect)
=> Fix optional authentication

package.json, yarn.lock
closes #6197 – This also increases the minimum Node version to 18, quite a big jump but there is no reason to keep supporting these super old versions. Onward~
=> Vite 5 upgrade

server/utils/queue.ts
Bull seems to have some sort of issue where background jobs will just completely stop processing without any errors or notice, this has been caught by monitoring on a couple of occasions and the only solution is to restart the worker processes.
This PR servers as an automatic healthcheck to auto-recover in these circumstances
=> Add health check for background queue

server/env.ts, server/index.ts, server/queues/HealthMonitor.ts, server/queues/index.ts, server/queues/queue.ts, server/services/worker.ts, server/storage/redis.ts
In the previous `createQueue` location it would also run on queue _consumers_. A foolish error!
=> fix: Queue health monitor should only run on worker processes

package.json, server/emails/templates/CommentCreatedEmail.tsx, server/emails/templates/CommentMentionedEmail.tsx, server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx, server/models/helpers/HTMLHelper.ts, yarn.lock
`inline-css` has dependencies on old unmaintained packages that aren't getting fixed, `css-inline` is a newer rust-based package with great performance and less dependencies that works well in testing
=> chore: Move from `inline-css` -> `css-inline`

plugins/email/server/auth/email.ts, server/middlewares/passport.ts
Redirect suspended user to `/?notice=user-suspended` in `email.ts` and `passport.ts`. 
Probably better to set redirect notice as constant somewhere and import it in both client and server. But this would be a much bigger refactoring.
Previous behavior. Notice that the `notice` query parameter in `http://127.0.0.1:3000/?notice=suspended` is `suspended`
Current behavior. The error message is now properly displayed
=> Fix Suspended User Login Error Redirect URL

shared/editor/extensions/Mermaid.ts
If we insert Mermaid diagram right before heading, anchor of the heading will be inserted between code block and mermaid diagram preview, this will cause diagram won't hide when section is folded.
1. Create a code block with Mermaid diagram
2. Create any level of heading right after the diagram 
- Mermaid diagram works properly
- Mermaid diagram still show but with some bugs as described above
As you can see in the screenshot, anchor of the heading has been inserted between the code block and the diagram, this will break css sibling tricks here:
https://github.com/outline/outline/blob/main/shared/editor/components/Styles.ts#L1496C1-L1496C43
That's because heading node will insert a invisible anchor right before the heading with priority (side: -1) higher than Mermaid diagram (side: 0 …
=> Bring Mermaid diagram priority higher than heading's anchor

shared/editor/extensions/Mermaid.ts
Before we introduce cache system into Mermaid diagram renderer, it will apply Outline appearance onto the diagram.
But after patch #5852, diagram won't apply its theme to match Outline on initialization randomly, and won't apply theme update anymore.
- Insert multiple Mermaid diagram, for example 20 diagrams
- Set Outline appearance to dark
- Refresh page to see the result (A)
- Update Outline appearance to light to see the result (B)
- Result (A) should render each Mermaid diagrams in dark theme
- Result (B) should re-render each Mermaid diagrams in default (light) theme 
- Result (A) shows diagrams in dark or default randomly, see screenshots below
- Result (B) won't trigger re-render and keeps as same as result (A)
This PR indicates two problems:
1. Mermaid initialization process is …
=> Render theme of Mermaid diagram properly

app/hooks/usePolicy.ts, app/menus/CommentMenu.tsx, app/menus/FileOperationMenu.tsx, app/menus/ShareMenu.tsx, app/menus/UserMenu.tsx, app/models/base/Model.ts, app/scenes/Collection.tsx, app/scenes/Document/Shared.tsx, app/scenes/Document/components/CommentThread.tsx, app/scenes/Document/components/Comments.tsx, app/scenes/Document/components/DataLoader.tsx, app/scenes/Document/components/DocumentMeta.tsx, app/scenes/Document/components/DocumentTitle.tsx, app/scenes/Document/components/Editor.tsx, app/scenes/Document/components/Header.tsx, app/scenes/Document/components/SharePopover.tsx
- Include policies in `loadRelations`
- Use model where available in `usePolicy`
- Use the same promise when in load in progress, parallelize fetches
=> chore: Improve relationship loading, include policies

app/models/Collection.ts, app/models/Document.ts, app/models/base/Model.ts, app/models/decorators/Field.ts, app/scenes/Document/components/CommentThreadItem.tsx, app/stores/CollectionsStore.ts, app/stores/CommentsStore.ts, app/stores/DocumentsStore.ts, app/stores/NotificationsStore.ts, app/stores/SharesStore.ts, app/stores/UsersStore.ts, app/stores/base/Store.ts, app/types.ts, app/utils/ApiClient.ts, shared/types.ts
- `fetch` will no longer return `undefined`
- Stronger types on CRUD model methods
- Added the ability to define return types for `ApiClient` 
- fix `fetchDocuments` throws error when unauthenticated
- Remove lots of use of `any`
=> chore: Improve typings around model methods

app/editor/components/FindAndReplace.tsx, app/editor/extensions/FindAndReplace.tsx, app/menus/DocumentMenu.tsx, app/scenes/Document/components/Header.tsx
Because find and replace is a widget tightly coupled to the editor state this is mostly plumbing to get a hook that can be used to toggle the state from outside the editor.
closes #6366
=> Add 'Find and replace' option to menu on mobile

app/components/WebsocketProvider.tsx, app/scenes/CollectionPermissions/index.tsx, app/scenes/Document/components/DocumentMeta.tsx, app/scenes/Document/components/History.tsx, app/stores/CollectionGroupMembershipsStore.ts, app/stores/CommentsStore.ts, app/stores/EventsStore.ts, app/stores/IntegrationsStore.ts, app/stores/MembershipsStore.ts, app/stores/SharesStore.ts, app/stores/UsersStore.ts, app/stores/base/Store.ts, plugins/slack/client/Settings.tsx
Ported from #5814 – removed `revoke` method language as it sounds like a mutation and is therefore confusing.
=> Duplicative method cleanup

app/components/WebsocketProvider.tsx, plugins/webhooks/server/tasks/DeliverWebhookTask.ts, server/migrations/20240204171556-add-event-changeset.js, server/models/Event.ts, server/models/Team.ts, server/models/User.ts, server/models/base/Model.test.ts, server/models/base/Model.ts, server/queues/processors/WebsocketsProcessor.ts, server/routes/api/users/users.ts, server/types.ts
- Fixed user model updates are not synced between clients
- Added `Model.changeset` to calculate difference since last persisted
- Added `Event.changes` column to store the above
- Added `Event.createFromContext` to simplify common creation pattern
Related https://github.com/outline/outline/pull/5909
=> fix: User updates are not synced between clients

server/middlewares/authentication.ts, server/migrations/20240204185157-team-last-active-at.js, server/models/Team.ts
This could be dynamically derived from users but it makes life a lot easier to have a column specifically for this.
=> chore: Track `lastActiveAt` for teams

server/emails/templates/BaseEmail.tsx, server/queues/processors/EmailsProcessor.ts, server/queues/processors/NotificationsProcessor.ts
closes #6478 – that was simpler than expected.
=> Move in-app notifications to instant, keep emails delayed

.env.sample, app.json, app/actions/definitions/navigation.tsx, app/scenes/Logout.tsx, server/env.ts, server/presenters/env.ts, shared/types.ts
Adds ability to add OIDC_LOGOUT_URI to .env to enable logout redirect. 
Closes #3954 
May need to be adjusted to check how the user was logged in? Currently whenever the user logs out, if OIDC_LOGOUT_URL is set, it will redirect to the OIDC logout endpoint, regardless of how the user logged in.
If the app only has OIDC authentication, this won't be an issue, but could be if the app has multiple authentication methods.
=> Add ability to logout from OIDC

shared/editor/components/Caption.tsx, shared/editor/components/ResizeHandle.tsx, shared/editor/components/Styles.ts
=> fix: Hide drag handles, empty captions, and selected outlines when printing

app.json, app/scenes/Login/index.tsx, server/env.ts, server/presenters/env.ts, shared/types.ts
Add another env var to prevent OIDC automatic redirect for those that do not wish to be automatically redirected to the OIDC login page.
=> Add ability to prevent OIDC redirect

app/editor/components/SuggestionsMenu.tsx
In SuggestionsMenu, Enter key events are not being propagated to handleLinkInputKeydown().
=> Propagate Enter key events in SuggestionsMenu so that handleLinkInputKeydown() can handle it.

server/static/index.html
Fixes a bug that results in a broken opensearch.xml for team subdomains.
See https://github.com/outline/outline/issues/3470 -- that issue, with the same reproduction steps, is happening again due to a change in 3eabb309493a88473932ddabefa1fdff93c11bde. It changed the opensearch URL from `/opensearch.xml` to `{cdn-url}/opensearch.xml`.
The team subdomain's `/opensearch.xml` is correct, but because the `<link rel="search" ...` points to the CDN URL, this correct opensearch.xml is not used.
=> Do not load opensearch.xml from CDN, so it uses the correct team subdomain

server/queues/tasks/DocumentImportTask.ts, server/routes/api/documents/documents.ts, server/services/worker.ts
Improves resiliency of document import process without changing API interface
=> chore: Move processing of `documents.import` to async worker

app/actions/definitions/notifications.tsx, app/components/ContextMenu/index.tsx, app/components/Notifications/Notifications.tsx, app/menus/NotificationMenu.tsx, app/stores/NotificationsStore.ts, server/routes/api/notifications/notifications.test.ts, server/routes/api/notifications/notifications.ts, shared/i18n/locales/en_US/translation.json
Closes #6463 
- Add an action "Archive all notifications".
- Add a menu inside `Notifications` popover which contains the `Archive` and `Settings` options.
- Filter the archived / non-archived notifications in the `notifications.list` API.
- Fetch only the non-archived notifications in the `Notifications` popover.
=> feat: Archive all notifications

plugins/google/server/auth/google.ts, server/commands/accountProvisioner.ts, server/commands/userProvisioner.ts
Google sends us the users preferred language, if it's a language we currently support then the display can be immediately set to this.
=> Automatically infer user language when signing in via Google

vite.config.ts
This PR explicitly sets the format of the filenames to `[name].[hash][ext]`.
----
Rollup 4 (Vite 5)  changed the default asset/chunk/entry filenames format to `[name]-[hash][ext]`, and the hashing algorithm is now base64. Since a base64 hash can contain `-`, bundle-stats is not able to safely extract the hash and compare the assets by filename:
- [More info about bundle-stats hash extraction for Vite/Rollup](https://relative-ci.com/documentation/guides/vite-config/#use-a-common-pattern-with-content-hashes-for-filenames)
- [Rollup 5 proposed changes](https://github.com/rollup/rollup/issues/5389#issuecomment-1938251936)
=> build: Vite - set rollup output filenames

server/routes/api/users/schema.ts, server/routes/api/users/users.test.ts, server/routes/api/users/users.ts
Allows filering the users by their permissions, separating from the status filter allows filtering by role and status, eg invited members, or suspended admins.
=> Add `role` parameter to `users.list` endpoint

app/editor/menus/formatting.tsx
This PR adds H3 option to the editor formatting toolbar.
As of now, the only way to change an existing heading level from H1/H2 to H3 is to remove the content and use the `slash directive` to insert a H3 node.
=> add H3 to editor formatting toolbar

app/menus/NotificationMenu.tsx, shared/i18n/locales/en_US/translation.json
The Notification settings were not added to the i18n translation.
Has been tested on the latest instance.
=> Untranslated button: Notification settings

server/errors.ts, server/middlewares/passport.ts
=> fix: Simplify redirect logic for self-hosted

app/components/CollectionDescription.tsx, app/models/Collection.ts, plugins/webhooks/server/tasks/DeliverWebhookTask.ts, server/migrations/20240524234042-add-content-to-collection.js, server/models/Collection.ts, server/models/helpers/DocumentHelper.tsx, server/presenters/collection.ts, server/queues/processors/WebsocketsProcessor.ts, server/queues/tasks/ExportJSONTask.ts, server/queues/tasks/ImportJSONTask.ts, server/routes/api/collections/collections.test.ts, server/routes/api/collections/collections.ts, server/routes/api/collections/schema.ts, server/routes/api/documents/documents.ts, server/types.ts
Follow on to #5553 – in order to update the editor with non-markdown-serializable functionality we also need to move collection storage to JSON.
=> Move collection description rendering to JSON

plugins/storage/server/api/files.ts, server/storage/files/BaseStorage.ts, server/storage/files/LocalStorage.ts, server/storage/files/S3Storage.ts
Fixes embedded videos unable to load in Safari.
closes #6949
=> Add range header support to `files.get`

app.json
Add the required `UTILS_SECRET` environment variable to `app.json`, so Outline can be deployed on PaaS such as Heroku or Scalingo.
=> fix(app.json): add UTILS_SECRET env var

package.json, server/routes/embeds.ts, server/routes/index.ts, server/services/web.ts, shared/editor/components/Frame.tsx, shared/editor/embeds/Gist.tsx, shared/editor/embeds/GitLabSnippet.tsx, yarn.lock
Moves GitLab and GitHub gist rendering to an isolated iframe with a dedicated CSP to reduce potential attack surface area of third-party hosted scripts.
=> Remove `gist.github.com`, `gitlab.com` from default CSP

plugins/email/server/auth/email.ts, plugins/email/server/auth/schema.ts
Fix case where email platform will spend the email signin link before the user has a chance to click it.
=> fix: Case where email platform will spend the email signin link

app/editor/extensions/BlockMenu.tsx, app/editor/extensions/EmojiMenu.tsx, app/editor/extensions/MentionMenu.tsx, app/editor/extensions/Suggestion.ts, shared/editor/plugins/Suggestions.ts
There are _some_ small oddities left here, but those will probably be okay left to a followup PR to land the majority here quickly.
For example, if you try to use `/notice` in a list item then it will fail as an individual list item cannot be converted to a notice – however the user intent here is to _insert_ a notice into the list.
=> Allow using `/` anywhere on a line or table

docs/SECURITY.md
The Node Security Project seems to be dead? The link leads to a squatted domain.
=> [docs] Remove dead link for Node Security Project

shared/editor/lib/changedDescendants.ts, shared/editor/nodes/Table.ts, shared/editor/plugins/FixTables.ts
Adds a plugin that fixes the last column in a table to ensure it fills the remaining width.
closes #7029
=> fix: Add a plugin to fix the last column in a table

.circleci/config.yml, Dockerfile, Dockerfile.base
There is no `aws-crt` prebuilt for Alpine ARM. We're not married to Alpine given it's compatibility issues if other small distros will work.
related #7033
=> Switch from Alpine -> Debian-slim

plugins/webhooks/server/tasks/DeliverWebhookTask.ts, server/presenters/document.ts
=> fix: Restore  field in document webhooks for backwards compat

server/routes/api/documents/documents.ts
Closes #7076 
Signing is not needed anymore since the attachments are part of the zip.
=> fix: remove attachment signing for document export

server/policies/document.test.ts, server/policies/document.ts
Currently guests that have been given more permissions at collection or document level are hard-coded to not have access to some functionality
=> fix: Open permissions for guests that have collection manage permission

server/commands/documentCreator.ts, server/commands/documentDuplicator.test.ts, server/commands/documentUpdater.ts, server/migrations/20240617151506-add-icon-to-document.js, server/models/Document.ts, server/models/Revision.ts, server/queues/tasks/ImportJSONTask.ts, server/queues/tasks/ImportMarkdownZipTask.ts, server/queues/tasks/ImportNotionTask.ts, server/queues/tasks/ImportTask.ts
Pre-requisite for #7038 
- Add `icon` and `color` column to `documents` and `revisions` table.
- On document creation and updation, set `icon` from `emoji` and `color` to `null`.
- On revision creation, set `icon` from `emoji` and `color` to `null`.
=> Add icon column to document

server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts
closes #7107
alt to https://github.com/outline/outline/pull/7108
=> fix: Incorrect policies returned from documents.update

server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts
Regression from #7038 
With the fallback logic, `undefined` is being set which prevents the icon removal.
=> fix: allow user to remove document icon

app/editor/extensions/SmartText.ts
Modify fraction regex statements to not match if directly preceded by a character
=> fix: Improve SmartText fraction regex pattern

app/components/Sharing/components/Suggestions.tsx, server/policies/collection.test.ts, server/policies/collection.ts, server/policies/document.ts
This causes a bug in enterprise edition where collections cannot be properly managed.
closes OLN-460
=> fix: Admins cannot query permissions on private collections

app/components/Collection/CollectionForm.tsx
=> Coalesce "No Access" collection permission to `null` to avoid invalidation

app/scenes/Document/components/Contents.tsx
This fixes a bug where the last heading in TOC does not get the active indicator when it is scrolled past.
=> fix: TOC active indicator for last heading

app/editor/components/FloatingToolbar.tsx, shared/editor/components/Image.tsx, shared/editor/styles/EditorStyleHelper.ts
Broken images can happen when pasting external content, in this case they are hard to select and remove
closes #7195
=> Add error state for broken images

plugins/azure/server/auth/azure.ts, plugins/azure/server/env.ts
As seen here https://github.com/outline/passport-azure-ad-oauth2 the Azure plugin already has the needed code to specify an specific azure tenant when using the azure tenant login. Therefore i added an ENV variable for this.
=> Add AZURE_TENANT_ID enviroment variable for specific azure tenant.

Dockerfile, Dockerfile.base
This PR resolve these warning during `docker build`:
- Dockerfile.base
```
1 warning found (use --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 25)
```
- Dockerfile
```
3 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 14)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 30)
```
=> Resolve buildx warnings during Docker image creation

server/policies/document.test.ts, server/policies/document.ts
The change below also works, but deleting extra lines to just rely on the "update" permissions simplifies things.
```
allow(User, "createChildDocument", Document, (actor, document) =>
and(
can(actor, "update", document),
or(
includesMembership(document, [DocumentPermission.Admin, DocumentPermission.ReadWrite]),
can(actor, "readDocument", document?.collection)
),
!document?.isDraft,
!document?.template
)
and(can(actor, "update", document), !document?.isDraft, !document?.template)
);
```
=> doc editors can create child docs

app/stores/UiStore.ts
This PR fixes a bug where it was possible to act on a collection in command bar after navigating from a document to a non-collection space (eg. home, trash, settings).
=> fix: unset active collection id when navigating away from a document

server/models/Collection.ts, server/models/Document.ts, server/queues/tasks/ExportDocumentTreeTask.ts, server/queues/tasks/ImportTask.ts, server/utils/url.ts
This PR removes the `doc/{docId}` format and sets the doc slug when collections are imported.
Documents which use `doc/{docId}` to link other documents do not have these references replaced with relative URLs when exported. This PR fixes this as well.
Bug mentioned [here](https://github.com/outline/outline/pull/7259#discussion_r1679128685)
Related #7259
=> fix: Set doc slug on importing collections

server/queues/tasks/ImportMarkdownZipTask.ts
=> fix: replace document links when importing markdown

server/models/Collection.ts, server/models/Pin.ts, server/models/Star.ts, server/models/UserMembership.ts, server/routes/api/collections/collections.ts, server/utils/removeIndexCollision.ts
In a workspace with hundreds of collections the calculation of `index` became larger than the column limit
closes #7283
=> fix: Index calculation does not take into account user scope

server/queues/tasks/ImportTask.ts
=> fix: use all properties from zip when importing a collection

app/models/WebhookSubscription.ts, plugins/webhooks/client/components/WebhookSubscriptionForm.tsx, server/models/IntegrationAuthentication.ts, server/models/User.ts, server/models/UserAuthentication.ts, server/models/WebhookSubscription.ts, server/models/decorators/Encrypted.ts
Working on https://github.com/outline/outline/pull/7377 I finally found a way around having to define explicit getter and setter for the encrypted decorator which cleans things up nicely.
Also fixed the types and return value for nullable encrypted columns.
=> chore: Refactor `@Encrypted` decorator

app/components/Button.tsx, app/components/ContextMenu/MenuItem.tsx, app/components/ContextMenu/index.tsx, app/components/InputSelect.tsx, app/index.tsx, package.json, shared/styles/globals.ts, yarn.lock
Removes the `focus-visible` polyfill as this caused a conflict with ProseMirror's DOM management in Chrome 127+ which made scrollable areas focusable.
Thankfully `:focus-visible` enjoys support in all major browser versions now, so this polyfill is no longer required and can be removed and usage replaced with the psuedo class.
=> fix: Unable to scroll elements in latest chrome

plugins/webhooks/server/tasks/DeliverWebhookTask.ts, server/commands/documentPermanentDeleter.test.ts, server/models/Group.ts, server/models/decorators/CounterCache.ts, server/presenters/group.ts, server/queues/processors/WebsocketsProcessor.ts, server/routes/api/collections/collections.ts, server/routes/api/groups/groups.ts, server/routes/api/urls/urls.ts, server/storage/database.ts, server/utils/CacheHelper.ts
This PR also adds a decorator to make it easy to cache any relationship count on any model going forward. 
This is useful foundational work towards https://github.com/outline/outline/pull/7275 as we really need to stop querying and returning all of the group memberships for performance (and reuse that for association for document memberships).
=> feat: Cache count of group members

plugins/slack/server/api/hooks.ts, server/models/helpers/SearchHelper.test.ts, server/models/helpers/SearchHelper.ts, server/routes/api/documents/documents.ts
A separate query for result count is not necessary if the number of results is less than the limit and the offset is 0, this covers the vast majority of search API requests.
=> perf: Avoid count query in search where possible

server/policies/index.ts, server/presenters/policy.ts
If there was a good reason for this to exist previously, it doesn't seem to be _required_ anymore.
=> perf: Remove old usage of dynamic require statement in policy serialization

app/hooks/useLastVisitedPath.tsx, app/scenes/Collection/index.tsx, app/scenes/Document/Shared.tsx, app/scenes/Document/index.tsx, app/scenes/Home.tsx, app/scenes/Login/index.tsx, app/stores/AuthStore.ts, app/utils/urls.ts
- Ensures that the `postLoginRedirect` cookie is not removed until it is used in edge cases.
- Ensures that the `postLoginRedirect` cookie is considered when returning to `/home`
closes #7423
=> fix: Refactor `postLoginRedirect` logic for reliability

plugins/github/server/index.ts, plugins/iframely/server/index.ts, server/utils/CacheHelper.ts
Came across this bug when working on Mattermost integration.
We've been using milliseconds for expiry when redis expects it in seconds.
redis: [doc](https://redis.io/docs/latest/commands/expire/)
ioredis: [doc](https://github.com/redis/ioredis?tab=readme-ov-file#expiration)
=> fix: Set redis expiry in seconds

app/models/Collection.ts, app/models/base/Model.ts, app/models/decorators/Lifecycle.ts
We have over time created a bundle of imperative code handling side effects, this adds frontend model lifecycle hooks in the same format as the backend hooks provided by Sequelize to allow us to tidy these things up.
=> Client lifecycle hooks

app/actions/definitions/documents.tsx, app/components/Sidebar/components/CollectionLink.tsx, app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/DraggableCollectionLink.tsx, app/components/Sidebar/components/GroupLink.tsx, app/components/Sidebar/components/SharedContext.ts, app/components/Sidebar/components/SharedWithMe.tsx, app/components/Sidebar/components/SharedWithMeLink.tsx, app/components/Sidebar/components/SidebarContext.ts, app/components/Sidebar/components/Starred.tsx, app/components/Sidebar/components/StarredContext.ts, app/components/Sidebar/components/StarredLink.tsx, app/components/Sidebar/hooks/useLocationState.ts, app/hooks/useTemplateActions.tsx, app/types.ts
This fixes several bugs where a document could be active highlighted in multiple locations and simplifies the logic for any number of sidebar "sections" going forward.
Each sub-tree of the sidebar must be wrapped in a `SidebarContext.Provider`.
=> fix: Refactor sidebar context management

app/actions/definitions/navigation.tsx, app/scenes/Logout.tsx
https://github.com/outline/outline/issues/6909
When you log out, auth.logout destroys the local session, and then the user is redirected to /. If the OIDC provider is the only configured authentication method, the user is immediately redirected to the OIDC provider’s authentication page. This triggers another window.location.replace call, which overwrites the previous destination. As a result, the user is not logged out of the OIDC provider and is instantly logged back in. You can observe this in the network requests, where the first window.location.replace is marked as canceled.
The fix simply prevents the redirect to the home page, allowing the browser enough time to complete the request.
=> logout for OIDC #6909

app/components/Sidebar/components/CollectionLink.tsx, app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/DraggableCollectionLink.tsx, app/components/Sidebar/components/SharedWithMe.tsx, app/components/Sidebar/components/SharedWithMeLink.tsx, app/components/Sidebar/components/SidebarLink.tsx, app/components/Sidebar/components/Starred.tsx, app/components/Sidebar/components/StarredLink.tsx, app/components/Sidebar/components/TrashLink.tsx, app/components/Sidebar/components/useDragAndDrop.tsx, app/models/Collection.ts, shared/types.ts
- Move more hooks out of sidebar components + improve types
- Fixed "Shared with me" documents cannot be dragged in "Starred" section
- Fixed read-only collections cannot be dragged in "Starred" section
- Fixed read-only documents cannot be dragged in "Starred" section
- Fixed dialog is full screen when dragging document into trash
closes #7500
=> fix: Allow dragging shared documents to starred section

shared/utils/domains.test.ts, shared/utils/domains.ts, shared/utils/urls.test.ts, shared/utils/urls.ts
URL with a different port should not be considered "internal"
closes #7245
=> fix: Consider port in `isInternalUrl` util

app/scenes/Settings/Preferences.tsx, app/scenes/Settings/Security.tsx, server/policies/user.ts, server/routes/api/teams/schema.ts, shared/constants.ts, shared/i18n/locales/en_US/translation.json, shared/types.ts
It is often preferable to prevent individual users from deleting their own account, they can still be deleted by workspace admins.
=> feat: Adds team preference to disable user account removal

server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts, server/routes/api/documents/schema.ts
Also, enables filtering archived docs by `collectionId`.
closes #7627
=> In `documents.archived`, allow `sort: "index"` in request

server/commands/documentUpdater.test.ts, server/models/helpers/DocumentHelper.tsx
=> fix: `document.content` column not updated when sending text attribute through API

package.json, server/scripts/release.js
Adds a script to automate release tagging, license updates etc, to ensure #7635 cannot happen again.
=> Add release script

shared/editor/embeds/index.tsx
This pr makes BiliBili embed behavior consistent with YouTube. It was annoying when we have multiple videos on one page.
ref: <https://player.bilibili.com/>
=> fix: disable bilibili autoplay

shared/editor/nodes/Math.ts, shared/editor/nodes/MathBlock.ts, shared/editor/rules/math.ts
This PR is expected to fix the markdown import/export compatibility issue in #6650.
Here is the test case, save as `.md` and use it to import document:
```plain
Here is inline $x=y$
$$
y=x
$$
```
Excepted result in Outline editor:
All general LaTeX texts should be converted to Outline `math_inline` or `math_block`.
This PR won't modify the input shortcut and trigger key. So the original trigger points (`$$` for inline, ```$$$ + Space``` for block) are preserved. And all imported or manaually inputed math nodes is still correct in `state`, only the generated `text` is changed.
Export an Outline document which contains math inline/block to markdown.
The result `.md` shoule be like (All formulas can be rendered correctly in any other editors):
I'm new to contributing to this project, and …
=> fix: Adjust math delimiter to fix markdown import/export compatibility issue

app/components/Icon.tsx, app/scenes/Document/components/Document.tsx
Closes #7693 
Nicely renders the document and collection title at the same location as well.
=> fix: align document and collection title

app/components/Text.ts, app/models/ApiKey.ts, app/scenes/ApiKeyNew/index.tsx, app/scenes/Settings/components/ApiKeyListItem.tsx, server/middlewares/authentication.test.ts, server/middlewares/authentication.ts, server/migrations/20240929194201-add-hash-to-api-key.js, server/models/ApiKey.test.ts, server/models/ApiKey.ts, server/presenters/apiKey.ts, shared/i18n/locales/en_US/translation.json
Towards #7675 – adds news column for storing the API key as a hashed value, and a preview of that value.
=> Add hashed column for API keys

app/editor/components/ComponentView.tsx, app/editor/components/NodeViewRenderer.tsx, app/editor/index.tsx, app/index.tsx
Instead of creating a new root for each react node in the editor we portal them into the main React context, this allows using things like the store and theme provider without any extra plumbing. 
Minimal viable version, foundational for #7680
=> chore: Moves ProseMirror NodeView to render within main React context

docker-compose.yml
`the attribute version is obsolete, it will be ignored, please remove it to avoid potential confusion`
[Reference in the compose-spec](https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-and-name-top-level-elements)
Also needs updating in the documentation here - https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
=> fix: Remove docker version in compose file

app/models/ApiKey.ts, app/scenes/Settings/ApiKeys.tsx, app/stores/ApiKeysStore.ts, server/policies/apiKey.ts, server/policies/user.ts, server/presenters/apiKey.ts, server/routes/api/apiKeys/apiKeys.test.ts, server/routes/api/apiKeys/apiKeys.ts, server/routes/api/apiKeys/schema.ts
Updates API key list endpoint to allow listing all API keys at the team level for admins. As this changes the default endpoint behavior there is a small chance of admins seeing API keys listed for other users under "Personal keys" until the app is reloaded.
The screen for listing team API keys is to follow
towards #7675 
follow on https://github.com/outline/outline/pull/7699
=> Allow returning team API keys for admins from `apiKeys.list`

app/components/WebsocketProvider.tsx, app/menus/CommentMenu.tsx, app/models/Comment.ts, app/scenes/Document/components/CommentThread.tsx, app/utils/routeHelpers.ts, server/routes/api/comments/comments.test.ts, server/routes/api/comments/comments.ts
=> fix: assorted comment bugs

server/policies/utils.ts
For list endpoints this should make a big overall difference to walltime spent.
=> perf: filter -> find to reduce policies iterated through

app/models/Comment.ts, app/scenes/Document/components/CommentThreadItem.tsx
There's more to improve here, but this is one of the main culprits.
Towards #7823
=> perf: Fix comments double rendering on mount

app/scenes/Document/Shared.tsx
This PR fixes a bug where the first load of a publicly shared doc(with sub docs) causes the main content to slide into the view.
By waiting until the first response is available, we ensure the app doesn't have a chance to render without a sidebar.
=> fix: wait for shared document to load

server/emails/mailer.tsx, server/emails/templates/BaseEmail.tsx, server/emails/templates/CollectionCreatedEmail.tsx, server/emails/templates/CollectionSharedEmail.tsx, server/emails/templates/CommentCreatedEmail.tsx, server/emails/templates/CommentMentionedEmail.tsx, server/emails/templates/ConfirmTeamDeleteEmail.tsx, server/emails/templates/ConfirmUserDeleteEmail.tsx, server/emails/templates/DocumentMentionedEmail.tsx, server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx, server/emails/templates/DocumentSharedEmail.tsx, server/emails/templates/ExportFailureEmail.tsx, server/emails/templates/ExportSuccessEmail.tsx, server/emails/templates/InviteAcceptedEmail.tsx, server/emails/templates/InviteEmail.tsx, server/emails/templates/InviteReminderEmail.tsx, server/emails/templates/SigninEmail.tsx, server/emails/templates/WebhookDisabledEmail.tsx, server/emails/templates/WelcomeEmail.tsx
This is a proactive change to prevent potential attacks in the vein of the recently discovered Zendesk vulnerability here:
https://gist.github.com/hackermondev/68ec8ed145fcee49d2f5e2b9d2cf2e52
By ensuring emails related to login/auth are sent from a unique email address each time we can protect against guessing the email in a third-party system
=> Make from address for authentication related emails unguessable

app/scenes/Document/components/Comments.tsx, shared/i18n/locales/en_US/translation.json
Closes #7818
- Factored out `readyToDisplay` to use as the dependency since refs can't be one. The effect then covers both the mounting + switching cases.
- It also ensures `document` can never be null, hence the typescript suppression.
- Due to the `50vh` bottom padding, the last comment appears in the middle of the screen. But I think this is the expected style given the padding.  If not, the scroll position can be adjusted further.
- In addition, the lack of a scrollbar might make it look like there are less comments, but again, I think this is expected (I got the same feeling when I opened the `/` command popup for the first time).
_p/s: I skipped the pre-PR discussion part given the size of the PR. I'm totally ok with re-doing/scrapping/dropping, etc._
=> Comments: scroll to most-recent during load and when switching sort setting

app/components/Editor.tsx, app/components/SearchPopover.tsx, app/scenes/Search/Search.tsx, app/scenes/Search/components/CollectionFilter.tsx, app/stores/DocumentsStore.ts, app/types.ts, plugins/slack/server/api/hooks.ts, server/models/helpers/SearchHelper.test.ts, server/models/helpers/SearchHelper.ts, server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts, server/routes/api/documents/schema.ts
Closes #7674
- Made query an optional param in `documents.search` API.
- Re-ordered the filters in the UI to provide a consistent interface before & after search.
- Render the filters conditionally based on search context.
- Add icon in collection filter.
=> feat: allow search without a search term

app/components/Table.tsx
Removes annoying warning + technically more correct.
(when opening `settings/shares`)
---
`header.id` does not exist in v7 (it does in v8). `@types/react-table` lied.
Stashed v7 documentation:
https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useTable.md#headergroup-properties
=> Fix header key for react-table v7

app/actions/definitions/navigation.tsx, app/menus/OrganizationMenu.tsx
> [!NOTE]  
> _Skipped the discussion part given the size; feel free to close directly if disagree :+1:_ 
When clicking on the top-left `OrganizationMenu > Settings`, I always get confused why it is showing me the Profiles page, given that the current context is workspace/org.
Switch the shortcut to point to `Workspace::details` instead. 
For Profile, it's more natural to click the profile button from the bottom-left that's already exist.
Not sure if the new analytics name will cause issues or not.
=> Jump to 'workspace' settings section if invoked from Org Menu

server/queues/processors/CollectionsProcessor.ts, server/queues/tasks/DetachDraftsFromCollectionTask.test.ts, server/queues/tasks/DetachDraftsFromCollectionTask.ts
Currently, the drafts are not detached when a collection is archived. This allows the user to publish the draft to an archived collection and perform updates later.
This PR ensures archival flow parity with the deletion flow. Specifically,
1. Drafts are now detached when a collection is archived.
2. Team's default view is reset if the archived collection was set as the default one.
=> fix: collection archival post-process parity with deletion

server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts
This PR fixes a bug wherein documents of a deleted collection cannot be restored from trash.
=> fix: restore documents from a deleted collection

server/queues/tasks/DocumentPublishedNotificationsTask.ts, server/queues/tasks/RevisionCreatedNotificationsTask.ts
=> fix: Document mentions can be incorrectly attributed during collab session

app/editor/index.tsx, app/scenes/Document/components/CommentForm.tsx, app/scenes/Document/components/CommentThread.tsx, shared/editor/components/Styles.ts, shared/editor/marks/Comment.ts
Closes #7470 
Note that this PR provides a forward fix. I don't think it's simple/straight-forward to fix the existing cases - need to load the localstorage in the comment mark instance. I guess the drafts count should be fairly low to ignore them.
=> fix: don't show comment marks for other users' drafts

server/policies/document.ts
Towards #7916.
Split the `manageUser` and `duplicate` policies for documents.
Right now, draft sharing is being allowed; so kept as-is. Not completely sure if this needs to be changed.
=> hide share option for templates

app/actions/definitions/documents.tsx, app/components/CommandBar/useTemplatesAction.tsx, app/models/Document.ts
This PR provides the following improvements around templates.
- Hide "New from template" menu item for the following cases.
- User does not have access to create document in a collection (An user with view permission to a collection).
- Template is deleted.
- Template is a draft.
- Conditionally show "New from template" action in the command bar.
- When user does not have create document permission in a collection, the action is hidden.
- When a collection is active, the templates in this collection + workspace templates are listed.
- When no collection is active, only the workspace templates are listed.
- Viewing a deleted template will now stay in the "Trash" page itself. Earlier, it was navigating to the templates page.
=> Improvements around templates

app/components/DocumentCard.tsx
When a document is unpinned from a collection, sometimes there's an inconsistency with the icon in the card.
This is because the `pin` gets deleted from the store before framer-motion can run the exit animation.
https://github.com/user-attachments/assets/e717b7a6-e61f-494f-b738-b2db29e2719f
=> store pin location on mount

package.json, server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx, server/utils/CacheHelper.ts, server/utils/MutexLock.ts, yarn.lock
If a change is made to a document that has many subscribers the same diff will be calculated and rendered once for each subscriber, this is expensive and can be avoided by caching the diff for a short period in redis after the first email is sent.
This PR also introduces a `CacheHelper.getDataOrSet` method to provide an interface for efficiently getting cache or calculating if missing.
closes #7982
=> Cache diff generation for email notifications

app/components/LanguagePrompt.tsx, app/components/Sidebar/Right.tsx, app/components/Sidebar/Sidebar.tsx, app/scenes/Document/components/Header.tsx, app/stores/AuthStore.ts, app/stores/UiStore.ts
It is possible to rapidly toggle some UI elements faster than these changes can be communicated between tabs via the `"storage"` event. When this happens it can cause an infinite loop that can only be stopped by closing a tab.
=> fix: Rare loop of storage events between tabs causing flickering UI

app/components/Actions.ts, app/components/CollectionDescription.tsx, app/components/ContentEditable.tsx, app/components/Guide.tsx, app/components/Header.tsx, app/components/Layout.tsx, app/components/Modal.tsx, app/components/Reactions/Reaction.tsx, app/components/Sidebar/Sidebar.tsx, app/components/Sidebar/components/SidebarButton.tsx, app/components/Sidebar/components/SidebarLink.tsx, app/components/Subheading.tsx, app/components/Table.tsx, app/components/Tabs.tsx, app/scenes/Document/components/CommentThreadItem.tsx, app/scenes/Document/components/Contents.tsx, app/scenes/Document/components/Document.tsx, app/scenes/Home.tsx, app/scenes/Search/components/SearchInput.tsx, app/scenes/Settings/components/ActionRow.tsx, app/typings/styled-components.d.ts, shared/styles/globals.ts, shared/styles/theme.ts
The background transitions are no longer needed since we're now using the `startTransition` API to switch between themes. Note: This does not fix the page becoming white when using `window.print` from the contenxt menu, that seems like a browser issue as we don't have any control beyond calling print.
closes #8005
=> fix: Flash of styles when printing dark mode

app/editor/extensions/Multiplayer.ts, app/scenes/Document/components/Document.tsx, shared/editor/extensions/History.ts, shared/editor/lib/Extension.ts, shared/editor/lib/ExtensionManager.ts
Centralize logic for undo/redo in command, overritten by multiplayer extension
=> fix: Undo/redo behavior incorrect in multiplayer editor

app/scenes/Document/components/CommentThread.tsx, shared/i18n/locales/en_US/translation.json
Closes #5079
- For the case of RTL, I followed how "Reply" is implemented (assumed that is the desired way). If it needs to be re-aligned, it can be fixed together with "Reply" later.
- The threshold number can be moved to `constants.ts` if we don't want to pollute the props.
=> Comment: collapse long replies

shared/utils/emoji.ts
Related #8006 
The logic is ported from [emoji-mart](https://github.com/missive/emoji-mart/blob/16978d04a766eec6455e2e8bb21cd8dc0b3c7436/packages/emoji-mart/src/helpers/native-support.ts#L45).
This has been tested in mac, ubuntu and windows platform.
=> Check flag emoji is supported

app/actions/definitions/documents.tsx, app/components/AuthenticatedLayout.tsx, app/scenes/Document/components/Comments.tsx, app/scenes/Document/components/DocumentMeta.tsx, app/scenes/Document/components/Editor.tsx, app/stores/UiStore.ts
Currently this is per-document and results in the comment sidebar bouncing in and out as you move around the workspace.
=> chore: Simplify comment sidebar persistence to be per-user

shared/editor/lib/markInputRule.ts, shared/editor/marks/Bold.ts, shared/editor/marks/Code.ts, shared/editor/marks/Highlight.ts, shared/editor/marks/Italic.ts, shared/editor/marks/Strikethrough.ts, shared/editor/marks/Underline.ts
Refactors inline mark matching to use a single consistent rule, adds ability to match when preceded by "(" "[" "{" characters.
closes #8083
=> feat: Improve inline rule matching

server/models/Event.ts, server/typings/sequelize.d.ts
This PR fixes a bug where events were not published in the `findOrCreateWithCtx` flow.
`findOrCreate` creates a nested transaction and sets the transaction created in the middleware as its parent. This child transaction is passed to all the hooks, including event [afterSave](https://github.com/outline/outline/blob/f448be5830045b886a890d4bf83f9e5bc1314866/server/models/Event.ts#L80). However, we _really_ need to execute the `afterCommit` hook on the parent transaction, since that gets committed by the middleware.
https://github.com/sequelize/sequelize/issues/17452 - This issue provides some more context what's happening under the hood.
Related #7920
=> fix: Use parent transaction for findOrCreate after-commit hook

server/migrations/20241231045203-add-attachments-teamId-index.js
Closes #7507 
There are quite a few use-cases of "id/teamId", "documentId/teamId", and "teamId" based queries.
It's better to create a simple index on `teamId` so that the query planner can combine multiple simple indexes (which we already have on `id` and `documentId`) when necessary.
=> Add teamId index on attachments table

app/scenes/Document/components/CommentSortMenu.tsx
Tiny change to skip invoking `users.update` API when switching from resolved view to existing sort preference view.
=> Skip unnecessary update of comment sort preference

server/queues/tasks/ImportJSONTask.ts
This pull request addresses issue [#7532](https://github.com/outline/outline/issues/7532), where the sorting order of documents is lost during the import process.  
- Updated the `mapDocuments` function in `ImportJSONTask` to use the `unshift` method instead of `push`.  
- Added a comment explaining the reason for the reversal, noting that `addDocumentToStructure` uses index 0 for insertion.  
- [Issue #7532: Sorting information is lost during import](https://github.com/outline/outline/issues/7532)  
- [Commit Reference: Changes in mapDocuments](https://github.com/outline/outline/compare/main...PrasadBandaru473:outline:7532-sorting-info-is-lost)
=> Preserve JSON Document Sorting Order During Import 

app/hooks/useTableRequest.ts, app/scenes/Settings/Members.tsx, app/scenes/Settings/Shares.tsx, app/stores/UsersStore.ts, server/routes/api/users/users.ts
Towards #7484 
This PR removes the intermediate `dataIds` state used in `useTableRequest`. This was causing issues in reactive updates from other places such as when inviting a user, adding new group. In hindsight, using `dataIds` was unnecessary - should have completely depended on the store data.
Along the way, two bugs that have been present for some time have been fixed.
1. When no filter is set, load the `active` users only (previously, we were loading all users).
2. Return invited user's email in `users.invite` response. This allows us to display the email in the members table without needing a refresh.
=> Improve useTableRequest for better reactivity

server/commands/userSuspender.ts, server/queues/processors/UserDeletedProcessor.ts
In `userSuspender` and `UserDeletedProcessor` flows, `GroupUser` deletion triggers an `afterBulkDestroy` hook - however we need the `afterDestroy` hook on each instance to update the group member counter cache.
It's not ideal to listen to `afterBulkDestroy` hook since it won't have the deleted instances data.
=> fix: Update counter cache when a user is deleted (or) suspended

shared/editor/queries/findCollapsedNodes.ts
This PR fixes #8221 by addressing the issue in `shared/editor/queries/findCollapsedNodes.ts` where nested collapsible headings were not handled properly. The problem stemmed from using a single `withinCollapsedHeading` variable, which failed to manage multiple collapsing levels accurately.
**Changes**  
- Replaced `withinCollapsedHeading` with a stack (`collapsedStack`) to track multiple collapsing levels.
- Ensured nested headings are correctly hidden under their collapsed parent headings.
**Expected Behavior**  
Collapsing higher-level headings (e.g., `##`) will now consistently hide all nested content, regardless of the state of lower-level headings.
=> fix: Handle nested collapsed headings in findCollapsedNodes

app/editor/extensions/BlockMenu.tsx, app/editor/extensions/EmojiMenu.tsx, app/editor/extensions/MentionMenu.tsx, app/editor/extensions/Suggestion.ts, shared/editor/plugins/Suggestions.ts
Improves and simplifies the logic for in-editor suggestion menus, it is not longer required to define multiple regexes, removes a regex evaluation from each keystroke.
=> fix: Various bugs in the suggestion menu logic

server/models/Attachment.ts, server/models/Collection.ts, server/models/Comment.ts, server/models/Document.ts, server/models/Group.ts, server/models/GroupMembership.ts, server/models/GroupUser.ts, server/models/Pin.ts, server/models/Reaction.ts, server/models/Share.ts, server/models/Star.ts, server/models/Subscription.ts, server/models/base/Model.ts, server/routes/api/collections/collections.ts, server/routes/api/comments/comments.ts, server/routes/api/documents/documents.ts, server/routes/api/groups/groups.ts
Towards #7920 
This PR removes the model namespace as a filter for publishing events. As such, it'll be used to customise the event's namespace when it's different from the model's table name.
The affected models are listed below.
| Model | Table name | Event namespace | Namespace customisation |
|--------|--------|--------|--------|
| ApiKey | apiKeys | api_keys | Retained |
| Attachment | attachments | attachments | Removed |
| Collection | collections | collections | Removed |
| Comment | comments | comments | Removed |
| Document | documents | documents | Removed |
| FileOperation | file_operations | fileOperations | Retained |
| Group | groups | groups | Removed |
| GroupMembership | group_permissions | N/A | N/A |
| GroupUser | group_users | groups | Added |
| Pin | pins | pins | …
=> Remove namespace filter for publishing events

server/models/GroupMembership.ts, server/models/UserMembership.ts, shared/editor/nodes/Mention.tsx
Fixes spurious events when publishing document
=> fix: Events lacking teamId published for sourced memberships

package.json, vite.config.ts, yarn.lock
[`rollup-plugin-webpack-stats@v2`](https://github.com/relative-ci/rollup-plugin-webpack-stats/releases) introduces a new way of detecting the correct chunk "initial" flag based on the dependency tree.
According to the report generated on the fork, multiple chunks are affected by the change, but from the tests the initial flag is set correctly (including the index entry): https://bit.ly/40IHFNz.
---
=> chore: Bump rollup-plugin-webpack-stats to v2.0.1

.env.sample
currently users will get errors when trying to setup their docker enviroments, default configs should be fast and not difficult, 
I still think this as a topic for this project needs some work, but this is a start.
=> update env.sample so that the connections work out of the packet by default, 

app/editor/extensions/ClipboardTextSerializer.ts
Editor content copied to the clipboard will now include markdown formatting. Less code, more functionality 👌 
closes #8292
=> Copy to clipboard as Markdown

app/editor/components/BlockMenu.tsx, app/editor/menus/block.tsx, shared/editor/commands/table.ts, shared/editor/types/index.ts
Flexible columns are frustrating when it comes to collaborative editing, moving this inline with other products by starting with a default width that can be resized.
=> Updates new tables to start with fixed column widths

app/scenes/Document/components/DataLoader.tsx
Skips unnecessary comments and shares endpoint invocations when viewing revisions
=> Skip auxiliary data load when viewing revisions

app/components/EventListItem.tsx, app/components/PaginatedEventList.tsx, app/components/PaginatedList.tsx, app/scenes/Document/components/History.tsx, app/stores/RevisionsStore.ts, server/routes/api/events/events.test.ts, server/routes/api/events/events.ts, server/routes/api/events/schema.ts, shared/utils/EventHelper.ts
Closes #8424 
This doesn't fix #8403 - it needs a bit more work to consolidate local document state.
I also noticed that document restore doesn't create a `documents.restore` event which sometimes messes up the history - will create a separate PR.
=> Move document history to `revisions.list` API

plugins/webhooks/server/tasks/CleanupWebhookDeliveriesTask.ts, server/models/base/Model.test.ts, server/models/base/Model.ts, server/queues/tasks/BaseTask.ts, server/queues/tasks/CleanupDeletedDocumentsTask.ts, server/queues/tasks/CleanupDeletedTeamsTask.ts, server/queues/tasks/CleanupExpiredAttachmentsTask.ts, server/queues/tasks/CleanupExpiredFileOperationsTask.ts, server/queues/tasks/CleanupOldEventsTask.ts, server/queues/tasks/CleanupOldNotificationsTask.ts, server/queues/tasks/ErrorTimedOutFileOperationsTask.ts, server/queues/tasks/InviteReminderTask.ts, server/queues/tasks/UpdateTeamsAttachmentsSizeTask.ts, server/routes/api/cron/cron.ts, server/services/cron.ts
These cron tasks running once/day are becoming a strain and are better moved to hourly – probably minutely in the future
Blocked by https://github.com/outline/outline/issues/8424
=> Add task to cleanup old events, change strategies to hourly

server/migrations/20250217230810-add-team-previous-subdomains.js, server/models/Team.test.ts, server/models/Team.ts, server/models/TeamDomain.test.ts, server/routes/index.ts, server/utils/passport.ts
If a subdomain is unused but another team previously used it, then we can safely redirect incoming requests.
closes #8266
=> feat: Redirect to previous subdomains

app/components/EventListItem.tsx, app/components/PaginatedEventList.tsx, app/components/PaginatedList.tsx, app/scenes/Document/components/History.tsx, app/stores/RevisionsStore.ts, server/routes/api/events/events.test.ts, server/routes/api/events/events.ts, server/routes/api/events/schema.ts, shared/utils/EventHelper.ts
Reverts outline/outline#8458 – some bugs here created duplicate headings in sidebar, and duplicate "latest" entries
=> Revert "Move document history to `revisions.list` API"

app/stores/DocumentsStore.ts
Closes #8473 
Feels right, but I couldn't think of a reason why the filtering was needed before.
=> fix: Don't remove data from store when fetching archived docs

app/components/EventListItem.tsx, app/scenes/Document/components/History.tsx
Separates the clickable revision history events from the metadata events which cannot be navigated, been meaning to do this for a long time.
| Before | After |
|--------|--------|
|  ![image](https://github.com/user-attachments/assets/e623ae9d-95d0-421a-bbc3-e08b19f78c69) | ![image](https://github.com/user-attachments/assets/0113aaaa-bbd6-4b92-9911-65dd7bcb5412) | 
Blocked by https://github.com/outline/outline/pull/8497
=> Improvements to history styling

app/hooks/usePinnedDocuments.ts, app/models/Document.ts, app/models/Pin.ts, app/scenes/Collection/index.tsx
Fixes a bug where the documents list sometimes slides up in the collection scene.
This was because the local cache wasn't updated when a pin is created / deleted. So, when there are no more pins to show, they still take up space until the latest data is retrieved from the server.
=> fix: Update local storage when creating/deleting pins

app/actions/definitions/collections.tsx
Fixes the lint warnings shown in IDE / PRs.
Verified all collection action touchpoints pass stores in the context.
---
Note: Other actions also use the imported stores, but don't cause lint errors - might be better to modify them to use from action context for consistency (can go incrementally here).
=> chore: Use stores from context in collection actions

app/components/Input.tsx, app/editor/components/FindAndReplace.tsx
This started as a bug fix to re-search the document when case sensitivity and regex are toggled through keyboard shortcut. Along the way, I noticed a couple of small improvs - individual commits have info about them. Please let me know if something needs to be changed/removed.
Included keyboard navigation is inspired by VSCode.
Also, I find the "Match word" variant very useful in VSCode - perhaps we can include it in Outline?
=> Assorted fixes/improvs in FindAndReplace popover

server/routes/api/comments/__snapshots__/comments.test.ts.snap, server/routes/api/comments/comments.test.ts, server/routes/api/comments/comments.ts, server/routes/api/comments/schema.ts, shared/editor/commands/table.ts
=> feat: allow sending text parameter to `comments.create`

app/scenes/Login/components/Notices.tsx, server/commands/accountProvisioner.test.ts, server/commands/accountProvisioner.ts, server/commands/teamProvisioner.ts, server/commands/userProvisioner.ts, shared/i18n/locales/en_US/translation.json
Sometimes there can be multiple workspaces with the same SSO provider, in this circumstance usually one is deleted/disabled.
If a user logs in from the homepage without a team subdomain we should always prioritize the enabled one.
=> fix: If multiple authentication providers match, prioritize enabled one

app/scenes/Document/components/History.tsx
Closes #8403 
Also fixes the spurious revision shown as the latest when any non-revision events like delete, unpublish happens.
=> fix: Show diff from document when revision has not been created yet

app/components/WebsocketProvider.tsx, server/services/websockets.ts
The previous breaking editor change left some clients hanging out in tabs, while there is already a reload mechanism using API requests it seems as though this is not reliable enough.
=> Send editor version down websocket and force reload

server/models/helpers/NotificationHelper.test.ts, server/models/helpers/NotificationHelper.ts
Fixes a bug where comment creation notifications incorrectly check for "document updates" type.
=> fix: Check user has enabled create-comment notification in email flow

shared/constants.ts
This has turned out to be more inline with customer expectations based on other tools, so changing the default.
=> Default comments to `Order in doc`

app/models/Share.ts, app/scenes/Settings/Shares.tsx, app/scenes/Settings/components/SharesTable.tsx, server/routes/api/shares/schema.ts, server/routes/api/shares/shares.test.ts, server/routes/api/shares/shares.ts
To match other tables, you should be able to filter here – this is useful when there are hundreds or thousands of links and you're trying to find specific links to revoke.
closes #8585
=> feat: Add filtering to shared links admin table

server/queues/tasks/RevisionCreatedNotificationsTask.test.ts
Moving to a slower CI seems to have unearthed some ordering race conditions
=> fix: Flaky test ordered event expectations

server/commands/documentCollaborativeUpdater.ts, server/commands/documentCreator.ts, server/commands/documentDuplicator.ts, server/models/Document.ts, server/models/Revision.test.ts, server/models/Revision.ts, server/models/helpers/DocumentHelper.tsx, server/models/helpers/ProseMirrorHelper.test.ts, server/models/helpers/ProsemirrorHelper.tsx, server/presenters/document.ts, server/queues/processors/RevisionsProcessor.ts, server/queues/tasks/DocumentUpdateTextTask.ts, server/routes/api/documents/documents.test.ts
The core of this PR is to move the potentially expensive serialization from every collaborative persistence into a delayed task runner.
Because of this change we can no longer rely on `text` being up to date, which is where the other changes come in – removing reliance on `text`. At this point the column is used essentially only for search indexing content.
=> perf: Move text serialization to task runner

server/routes/api/revisions/revisions.test.ts, server/routes/api/revisions/schema.ts
Allow removing custom name through API
=> fix: Allow setting revision name to `null`

package.json, server/routes/api/index.ts, server/routes/index.ts, yarn.lock
Upgrade `koa-router` and `dd-trace` to allow dep update
=> chore: Upgrade `path-to-regexp`

server/storage/files/BaseStorage.ts, shared/editor/commands/insertFiles.ts, shared/editor/lib/FileHelper.test.ts, shared/editor/lib/FileHelper.ts
Using `startsWith` to parse content type is not safe, better to check the entire string.
=> fix: Potential unsafe `content-type` check

server/routes/api/middlewares/apiResponse.ts
=> fix: API middleware wrapper triggers on JSZip stream

package.json, yarn.lock
In a stroke of bad luck this weeks update of dd-trace landed on a new version that has several bugs:
https://github.com/DataDog/dd-trace-js/issues/5389
=> fix: `dd-trace` upgrade causes errors/high memory consumption

app/actions/definitions/collections.tsx, app/actions/definitions/documents.tsx, app/actions/definitions/navigation.tsx, app/components/InputSearchPage.tsx, app/routes/authenticated.tsx, app/scenes/Search/Search.tsx, app/scenes/Search/components/RecentSearchListItem.tsx, app/utils/routeHelpers.ts
Browsers mess with the path when it includes slashes – automatically changing back to forward slash. Even better than that, it doesn't matter if it's encoded – they'll _still_ mess with it. Moving the search term to query string, with the path variant as a fallback for backwards compat.
closes #8644
=> fix: Move search term to `q` query string

shared/editor/marks/Link.tsx
Allows events to continue if they are clicks _or_ middle clicks.
It doesn't appear to need any further customization, because the underling link handler already opens in a new tab.
Tested:
- Editing middle click
- Reading middle click
- Editing normal click
- Reading normal click
=> Allow middle click

server/routes/api/notifications/notifications.ts, server/routes/api/notifications/schema.ts, server/routes/api/subscriptions/schema.ts, server/routes/api/subscriptions/subscriptions.ts
Add a client-side redirect to prevent anti-virus from loading unsubscribe links and inadvertently unsubbing the user. We have this same protection in place for email signin tokens, and email update tokens.
=> fix: Add prevention of auto-following unsubscribe links in emails

server/policies/document.test.ts, server/policies/document.ts
=> fix: Allow team admin to manage permissions on any document they have access to 

app/hooks/useQueryNotices.ts, server/models/helpers/SubscriptionHelper.test.ts, server/models/helpers/SubscriptionHelper.ts, server/routes/api/subscriptions/subscriptions.test.ts, server/routes/api/subscriptions/subscriptions.ts, shared/i18n/locales/en_US/translation.json, shared/types.ts
Hopefully all the existing tests make this easier to review – TLDR: We include a link to unsubscribe in document notification emails, when #8392 was added this wasn't updated to account for collection subscriptions.
=> fix: Unsubscribe link for collection subscriptions 

app/editor/extensions/PasteHandler.tsx
closes #8748 – this is a temporary fix, in the future mentions can support heading links but I would like to do that in a way that can show a preview of the heading too
=> fix: Direct link to heading lost when pasting

server/utils/CacheHelper.ts
This PR suppresses any exceptions that could arise during redlock flow. It's fine to suppress as sometimes the operation could fail when the lock has already expired (or) some other process has active lock on it.
More on this here - https://github.com/mike-marcacci/node-redlock/issues/168
This exception ends up failing the document update emails - noticed it in #8763
=> fix: Release redis lock only when it hasn't expired

app/editor/extensions/PasteHandler.tsx, app/editor/menus/code.tsx, shared/editor/extensions/Prism.ts, shared/editor/lib/code.ts
This required a refactor as `HTML` and `XML` share the same prism formatter (`markup`), previously we assumed that the prism language and our internal stored language were the same except for two hardcoded exceptions for plaintext and mermaid.
closes #8766
=> feat: Add `XML` as code formatting option

plugins/notion/server/utils/NotionConverter.test.ts, plugins/notion/server/utils/NotionConverter.ts, plugins/notion/server/utils/__snapshots__/NotionConverter.test.ts.snap, server/test/fixtures/notion-page-with-empty-text-nodes.json
Closes #8782 
Empty content in bookmark caption, code block and math block from Notion causes the "empty text node" error in Prosemirror. Other cases of converting to "text" node works fine.
=> fix: Handle empty text blocks from Notion response

server/models/helpers/NotificationHelper.test.ts, server/models/helpers/NotificationHelper.ts, server/queues/tasks/DocumentPublishedNotificationsTask.ts, server/queues/tasks/RevisionCreatedNotificationsTask.ts
So far I've been unable to reproduce the reported issue of users receiving emails for comments they didn't participate in, but this is a nice refactor that simplifies, improves performance, and removes the dangerous `onlySubscribers` prop
closes #8807
=> fix: Improve performance of notification queries

server/routes/api/collections/collections.ts
Closes #8840 
I could not reproduce the bug through app - I suppose the bug must've occurred through a direct API invocation.
However, the fix made in this PR is likely the bug source.
On a related note, I'm not sure if the containing block is needed.. maybe it's being used in enterprise edition?
Also, the guard in L587/588 feels out-of-date with comment in L584 🤔
=> fix: Skip sequelize hooks when creating user membership in collections.update

server/routes/api/notifications/notifications.test.ts, server/routes/api/notifications/notifications.ts
This is the cause of a couple of spots of downtime in recent days.
=> fix: Missing transaction in save causing deadlocks

server/collaboration/ConnectionLimitExtension.test.ts, server/collaboration/ConnectionLimitExtension.ts
Fixes a regression in [#8751](https://github.com/outline/outline/pull/8751/files#diff-074611e897564d35bc1cb7e548e081e800f80f11604c09cebf020a916c87f560) where the connection count would be increased before a connection is successfully established, resulting in an incorrect count if another extension rejects the connection.
=> fix: Collaboration server inaccurately counts connections

server/models/helpers/ProsemirrorHelper.tsx
This mapping is no longer needed since Markdown is no longer the canonical store and is only used for import/export.
It was actually causing bugs where a paragraph containing a url would be removed and replaced with an embed on import.
=> fix: Remove url->embed mapping in Markdown import

app/components/Sidebar/Sidebar.tsx
Hey, this is adressing this issue #8872  concerning the sidebar closing too fast when hovering off.
I added a half a second delay when the poiter leaves the sidebar to make it a little more convenient.
closes #8872
=> Added delay on sidebar exit

server/utils/indexing.test.ts, server/utils/indexing.ts
This seems to be due to a bug in Sequelize when selecting fields to query. The bug can be reproduced by removing the changes in `indexing.ts` and running the included tests
=> fix: `collectionIndexing` results in `teamId` undefined error

.github/workflows/ci.yml
Separated from `tom/async-syntax-highlighting` – A few key pieces were missing from these workflows
=> fix: `bundle-size` CI

server/policies/collection.ts
Changing this to match workspace export, to bulk export data of any form should require admin permissions
=> Require collection manage permissions to export

shared/editor/lib/code.ts
A small mistake here with the last refactor caused this to repeatedly fail loading
=> fix: Infinite loop loading page with vbnet code embed

app/components/Sidebar/components/DocumentLink.tsx, app/components/Sidebar/components/NavLink.tsx, app/components/Sidebar/hooks/useDragAndDrop.tsx
Note: This is also an issue for collections but will require a larger refactor to solve due to the arrangement of components, probably makes sense to land the fix for docs first.
Related #8988
=> fix: Cannot drag-select text while editing document title in sidebar

plugins/github/server/github.ts, plugins/iframely/server/iframely.ts, server/routes/api/urls/urls.test.ts, server/routes/api/urls/urls.ts, server/types.ts
With the introduction of GitHub mentions (and more in the pipeline), we need to ensure iframely fallback is not used for such connected integrations.
This ends up causing issues due to data format mismatch between iframely and GitHub for e.g.
=> Ensure iframely fallback is not executed for connected unfurl integration

plugins/storage/server/api/files.ts
An additional protective layer when using the local file storage provider, this doesn't fix any specific known issues.
=> Add additional CSP protection to `files.get` endpoint

app/components/DocumentBreadcrumb.tsx, app/editor/components/LinkEditor.tsx, app/editor/components/MentionMenu.tsx, shared/editor/types/index.ts
Attempt to implement the optimization mentioned in #8930 for the display content of the document search box item in the context and link.
=> Display breadcrumb instead of collection name when link and mention document

server/policies/team.test.ts, server/policies/team.ts
There is no real harm to loosening this permission. Viewers can currently be upgraded to edit rights in specific collections and documents, but in these cases they do not have access to templates.
closes #8736
=> fix: Allow viewers to read templates

app/components/HoverPreview/Components.tsx, app/components/HoverPreview/HoverPreviewIssue.tsx, app/components/HoverPreview/HoverPreviewPullRequest.tsx, shared/components/Backticks.tsx, shared/components/IssueStatusIcon/GitHubIssueStatusIcon.tsx, shared/components/IssueStatusIcon/LinearIssueStatusIcon.tsx, shared/components/IssueStatusIcon/index.tsx, shared/components/PullRequestIcon.tsx, shared/editor/components/Mentions.tsx
Various fixes to the styling of issue/PR hovercards and iconography
=> fix: Tidying mention hover cards

app/components/PaginatedList.tsx
Regressed in https://github.com/outline/outline/pull/9030 – this is what you get for vibe coding
=> fix: Double fetch on refactored paginated list

plugins/linear/shared/LinearUtils.ts
Prevents multiple installations and an improved permission management experience.
=> Switch Linear to `actor=app` method

server/models/helpers/NotificationHelper.test.ts, server/models/helpers/NotificationHelper.ts
Finally solves this issue, it required the following to be true:
- There must be a draft without a collection
- Someone should comment on the draft
- Other users must have access to the draft through a user or group membership
- Other users must have document subscriptions to at least one other document
- If all the above is true they will be notified, when they should not have been
Prior to the [fix here](https://github.com/outline/outline/pull/8997/files#diff-0a9c587545d94867afe9683cdeb90d01295f6dd2f07b7a0b5f4470c7a93c7cb3R209-R212) they would be sent a notification for _every other document subscription_ in the db. In the worst case scenario with a large Outline instance and a large group given access to the draft document this could result in thousands of spurious notifications. …
=> fix: Notifications received for draft with access but no subscription

app/scenes/Collection/index.tsx, app/stores/CollectionsStore.ts
- Not searching the store by urlId led to unnecessary requests on the collection overview screen
- Guarding the fetch meant that documents would not load if needed
=> fix: Subtle collection loading bug

app/components/Sidebar/Sidebar.tsx, app/editor/components/FloatingToolbar.tsx, shared/styles/globals.ts, shared/utils/browser.ts
We need to respect the "safe" areas for mobile devices
=> fix: Mobile toolbar overlaps with home indicator

app/editor/extensions/SmartText.ts, shared/editor/commands/table.ts, shared/editor/nodes/Table.ts
Adds an input rule to trigger table creation when typing pipe dash dash (the beginning of a markdown table syntax)
=> feat: Add input rule to create new tables

vite.config.ts
We also have cache on headers but sw is more reliable
=> Add server worker cache for attachments/files

app/components/Sidebar/components/StarredLink.tsx, app/models/Star.ts
An error was introduced in https://github.com/outline/outline/pull/9120 due to this type being incorrect, `collectionId` on star is nullable.
=> fix: Error loading collection

server/models/Document.ts, server/models/helpers/SearchHelper.ts, server/routes/api/documents/documents.ts, server/routes/api/groupMemberships/groupMemberships.ts, server/routes/api/pins/pins.ts, server/routes/api/stars/stars.ts, server/routes/api/userMemberships/userMemberships.ts, server/utils/permissions.ts
This scope should never be queried without `withMembership` so lets combine these two and simplify things here. These scopes are a mess, this is just a start to making sense of them.
=> Remove `withCollectionPermissions` scope

plugins/notion/server/utils/NotionConverter.ts, server/test/fixtures/notion-page-with-empty-text-nodes.json
=> fix: Introduce more guards against empty text nodes in `NotionConverter`

package.json, server/commands/documentLoader.ts, server/commands/documentMover.ts, server/models/Collection.test.ts, server/models/Collection.ts, server/models/Document.test.ts, server/models/Document.ts, server/routes/api/collections/collections.ts, server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts, server/routes/api/shares/shares.ts, server/storage/database.ts, server/test/factories.ts, server/utils/indexing.ts, yarn.lock
While `documentStructure` was removed from collection responses, it was never removed from the SELECT statements for collection data. This PR updates that so it is only queried where necessary to return or update the structure
=> perf: Remove `documentStructure` from default query select

server/queues/tasks/ExportDocumentTreeTask.ts, server/queues/tasks/ExportTask.ts
Regression from https://github.com/outline/outline/pull/9141
=> fix: `ExportDocumentTreeTask` needs `documentStructure`

app/editor/components/FindAndReplace.tsx
CMD+F twice should open native browser find
Regressed in https://github.com/outline/outline/pull/8560
=> fix: CMD+F with in-app find interface open should open native find

app/scenes/Settings/Integrations.tsx
Annoyingly group by does not produce an empty array, but undefined in this situation
=> fix: JS error when no integrations are connected

app/components/ContextMenu/Template.tsx
To adress the issue #9201
Updated key props in Template component to be more descriptive  to avoid potential key collisions and improve debugging.
Wrapped MenuItem with a div when using a Tooltip to ensure correct DOM structure and avoid React warnings.
Minor refactoring for clarity and consistency across menu item types.
=> Fix: Add missing key prop to context menu items to avoid React warning

app/components/EditableTitle.tsx
In this PR, I addressed an issue where editing the title in the sidebar and hitting "Enter" would cause a flash of the previous value, specifically for documents. issue #9195
Moved setIsEditing(false) after successful onSubmit to prevent premature UI updates.
Now properly exits edit mode on both success and error cases.
Eliminates the flash of old values when submitting with Enter.
https://github.com/user-attachments/assets/28058917-1210-46b7-9fc0-33d92a64bcbb
=> Fix flash of previous value after editing title in sidebar for documents

plugins/oidc/server/auth/oidc.ts
Supersedes #9169.
ADFS' userinfo endpoint only provides the sub claim, which causes the generic OIDC authentication plugin to fail, as it expects email, preferred_username etc.
This pull request enhances the OIDC authentication plugin by falling back to the OIDC id_token which could contain these claims. 
Regression tested against ADFS and Keycloak -- authentication works with both. 
(Typescript is not my bread and butter -- let me know if I need to rethink any of this!)
=> fix: fall back to id_token when OIDC userinfo endpoint is sparse

app/components/EditableTitle.tsx
=> fix: Reset editing state when collection/document title is unmodified

server/validation.test.ts, server/validation.ts
I can't reproduce the original issue, but it's straight forward and reasonable to sanitize this character
=> fix: Remove # from stored filesystem keys

server/routes/index.ts
=> fix: Use team name on link metadata if public branding enabled

server/queues/processors/WebsocketsProcessor.ts
=> fix: null `collectionId` received in websocket payload for unpublished drafts

plugins/notion/server/notion.ts
Closes #9287 
Probably the only "unsupported" block with children right now, which might be why this wasn't faced before.
=> fix: Skip fetching children for unsupported Notion blocks

app/components/CopyToClipboard.ts, app/components/DocumentExplorer.tsx, app/components/Guide.tsx, app/components/List/Item.tsx, app/components/Modal.tsx, app/components/SearchPopover.tsx, app/components/Sharing/Document/DocumentMemberList.tsx, app/components/Sharing/components/Suggestions.tsx, app/components/Sidebar/Sidebar.tsx, app/components/Sidebar/components/NavLink.tsx, app/components/Sidebar/components/SharedWithMeLink.tsx, app/components/Sidebar/components/StarredLink.tsx, app/hooks/useEmbeds.ts, app/hooks/useMenuHeight.ts
This commit addresses `typescript-eslint/no-shadow` violations.
**Summary of Actions:**
1.  **Initial Analysis & Setup:**
*   My plan was to identify `no-shadow` errors using `yarn lint`, then systematically fix them across `app/`, `server/`, `shared/`, and `plugins/` directories.
2.  **Actual Changes Made:**
*   I successfully disabled the pre-commit hook temporarily.
*   I manually identified and fixed shadowing issues in several files within `app/components/` and `app/hooks/`. Renamed variables included:
*   `app/components/Avatar/AvatarWithPresence.tsx`: inner `props` to `p`.
*   `app/components/CopyToClipboard.ts`: `elem` to `childElem`.
*   `app/components/DocumentExplorer.tsx`: `itemRefs` to `existingItemRefs`, `node` to `ancestorNode`, inner `node` to `n`.
* …
=> chore: resolve `typescript-eslint/no-shadow` errors.

app/components/Sharing/Document/AccessControlList.tsx, app/components/Sharing/Document/PublicAccess.tsx
Due to the usage of `asChild` all tooltip children must be accessible
=> fix: Inaccessible tooltips after conversion

server/commands/accountProvisioner.ts, server/commands/documentDuplicator.ts, server/commands/documentMover.ts, server/commands/teamProvisioner.test.ts, server/commands/teamProvisioner.ts, server/commands/userInviter.ts, server/commands/userProvisioner.ts, server/emails/templates/BaseEmail.tsx, server/emails/templates/InviteEmail.tsx, server/emails/templates/SigninEmail.tsx, server/logging/Logger.ts
This commit addresses several linting warnings reported by ESLint:
- @typescript-eslint/no-shadow:
- I renamed variables in inner scopes to avoid conflicts with variables in outer scopes in the following files:
- server/commands/accountProvisioner.ts
- server/commands/documentDuplicator.ts
- server/commands/documentMover.ts
- server/commands/teamProvisioner.test.ts
- server/commands/teamProvisioner.ts
- server/commands/userInviter.ts
- server/commands/userProvisioner.ts
- server/emails/templates/BaseEmail.tsx
- @typescript-eslint/no-explicit-any:
- I replaced `any` with more specific types (Record<string, unknown> or void) in the following files:
- server/emails/templates/BaseEmail.tsx
- server/emails/templates/InviteEmail.tsx
- server/emails/templates/SigninEmail.tsx
- …
=> chore: Fix various lint warnings

app/components/Switch.tsx
We need to set the target `name` and `id` in the Switch event since some pages use them in handlers, eg. [Preferences](https://github.com/outline/outline/blob/main/app/scenes/Settings/Preferences.tsx#L56), [Security](https://github.com/outline/outline/blob/main/app/scenes/Settings/Security.tsx#L93) page..
Ideally, Switch's `onChange` handler should be changed to `(checked: boolean) => void`, but that'd mean a lot of changes throughout the app.
Regressed in #9358
=> fix: Set name and id in `Switch` events

server/queues/tasks/BaseTask.ts
Removes deprecated non-typesafe schedule method which was superseded in #9079
=> chore: Cleanup deprecated task schedule method

server/models/Notification.ts
=> fix: Ensure notification relationships are loaded in `EmailProcessor`

server/models/Collection.ts
No functional difference here, just avoid extra passed attributes
=> fix: options vs rest usage

app/actions/definitions/documents.tsx, app/components/AuthenticatedLayout.tsx, app/models/Collection.ts, app/scenes/Document/components/DocumentMeta.tsx, app/scenes/Document/components/Editor.tsx, server/policies/document.ts
Refactor to use policies for comment so the collection is not required to be loaded on the client
closes #9446
=> fix: Commenting unavailable on individually shared documents

app/components/PaginatedList.tsx
`offset` incorrectly moves forward when no search is made.
closes #9463
=> fix: Public share search offset is incorrect

plugins/notion/server/notion.ts
Fairly simple way to delay retries, provided Notion's retry delays are not very long.
If it doesn't solve the issue, we might have to look into a bit more complex (since each job can have 3 concurrent pages) flow 👇 
1. Store the partial progress in Redis.
2. Retry the job -> resume from where it left off based on cached progress.
=> Use `Retry-After` header for Notion rate-limit retries

server/routes/api/shares/schema.ts, server/routes/api/shares/shares.test.ts, server/routes/api/shares/shares.ts
For API users, allow settings this configuration at the point of creation
=> feat: Allow `allowIndexing` and `showLastUpdated` to be set in `shares.create`

plugins/notion/server/tasks/NotionAPIImportTask.ts
Follow on to #9427 loosens message requirements to catch linked database errors
=> fix: Not correctly catching linked databases

app/models/SearchQuery.ts, server/migrations/20250630100046-add-oauth-to-search-queries-source.js, server/models/SearchQuery.ts
Fixes search API returning 400 validation error for OAuth-authenticated requests when search parameters are provided.
OAuth-authenticated users could perform searches with empty parameters, but received validation errors when providing any search parameters:
**Working:**
POST /api/documents.search
{"query": "", "limit": 10}  // ✅ Success
Failing:
POST /api/documents.search
{"query": "test", "limit": 10}  // ❌ 400 Error
Error Message:
"oauth" is not a valid choice in ["slack","app","api"] (source)
- Empty search queries bypass the search query logging/tracking system (I think)
- Non-empty search queries trigger the SearchQuery model creation for analytics
- OAuth requests are internally tagged with source: "oauth"
- Database enum enum_search_queries_source only included ["slack", "app", …
=> fix: Add OAuth support to search query source enum

shared/editor/nodes/Image.tsx, shared/editor/nodes/SimpleImage.tsx
Tracked this back to the very original code 5y ago, there doesn't seem to be a solid reason for this other than perhaps a misunderstanding of the `token` internals at the time.
https://github.com/outline/rich-markdown-editor/blame/b0e6a7ee8ea8f70d57a1c91525d828d023a30b8a/src/nodes/Image.tsx#L243
closes #9531
=> fix: Importer truncates newlines in captions

shared/editor/lib/markdown/rules.ts, shared/editor/marks/Code.ts, shared/editor/nodes/CodeFence.ts, shared/editor/nodes/HardBreak.ts, shared/editor/nodes/index.ts, shared/editor/rules/breaks.ts
closes #9532 – Another fun markdown parsing bug that's existed for years
=> fix: Incorrect parsing of hard breaks from Markdown

shared/editor/nodes/HardBreak.ts, shared/editor/rules/breaks.ts
On markdown import we do not care about the semantics of these two things.
=> fix: Map hardbreaks to breaks

app/components/Collaborators.tsx, app/components/IconPicker/index.tsx, app/components/Notifications/NotificationsPopover.tsx, app/components/primitives/Popover.tsx, app/scenes/Collection/components/ShareButton.tsx, app/scenes/Document/components/ShareButton.tsx, app/styles/animations.ts
- Added a `Popover` primitive that has base styles with entry/exit animations.
- `Collaborators`, `IconPicker`, and `Notifications` were already ported to Radix. They now use the new primitive.
- Ported document and collection share popovers in this PR.
Towards #6456
=> Migrate share popovers to Radix

package.json, yarn.lock
Upgraded radix-dialog and radix-select to use compatible internal layers (dismissable-layer, focus-scope, etc.).
Closes #9573
=> fix: Use compatible versions of Radix internals

app/components/Notifications/NotificationsPopover.tsx
Previously this was the case, but was lost in an earlier Radix refactor that stopped quietly rendering the Notifications component.
=> fix: Restore preloading of notifications

shared/collaboration/CloseEvents.ts, shared/editor/version.ts
By change 4999 is the highest valid number, using 5000 caused the server to crash rather than issue the error code when this codepath is hit
=> fix: `EditorUpdateError` code outside valid range

server/commands/documentLoader.ts, server/routes/api/documents/documents.test.ts, server/routes/api/documents/documents.ts
=> fix: Blank page is rendered when link to draft without collection is shared

app/hooks/useSettingsConfig.ts, plugins/slack/client/index.tsx
This actually works well with the recent changes that only show integrations in the sidebar if you have them connected/installed.
closes #9607
=> fix: Viewers unable to connect personal Slack

plugins/oidc/server/auth/oidc.ts
A touch hacky, but I believe this patch is the only way to have this work without another larger refactor
=> fix: Refresh tokens do not work with OIDC discovery

vite.config.ts
Sentry depends on consistency, this will mean a small increase in bundle size again
=> chore: Keep classnames in build

shared/editor/components/Image.tsx, shared/editor/nodes/Image.tsx, shared/editor/nodes/SimpleImage.tsx
`EventBoundary` wrapper component further down the react tree captures `click` events, rendering these `onClick` handlers vestigial. Getting rid of these to avoid confusion.
=> `EventBoundary` wrapper component further down the react tree captures `click` events

server/commands/revisionCreator.test.ts, server/commands/revisionCreator.ts, server/models/Revision.test.ts, server/models/Revision.ts, server/queues/processors/RevisionsProcessor.test.ts, server/queues/tasks/RevisionCreatedNotificationsTask.test.ts, server/routes/api/documents/documents.test.ts, server/routes/api/revisions/revisions.test.ts, server/types.ts
=> chore: Move `Revision` event writing to model layer

server/models/Collection.test.ts, server/models/Collection.ts
In the file imports flow, we were incorrectly querying for team's first collection to resolve index collision (basically overwriting the `where` clause).
=> fix: Skip overwriting non-transaction fields in `firstCollectionForTeam` query

app/utils/sentry.ts
This regressed as part of #9523 – however, relying on this string comparison was bad practice to begin with, a further enhancement here might be to inherit all of these errors from a single ignored type?
=> fix: Frontend errors not properly filtered when source is minified

app/components/WebsocketProvider.tsx
This is one of those "How did this ever work?" bugs, as far as I can tell a POJO has always been passed to this method that expects a model instead with `modelName` attribute.
closes #9667
=> fix: Invariant violation with `addToArchive` called with non-model

.oxlintrc.json, package.json, server/routes/api/authenticationProviders/authenticationProviders.ts, yarn.lock
This PR:
- Removes`@eslint/eslintrc`, `@eslint/js`, as they're unneccessary dependencies
- Adds `eslint`, `typescript` to the root of the `.oxlintrc.json` to ensure that eslint and typescript plugins are enabled
=> chore(linter): improve oxlint setup

app/components/RevisionListItem.tsx, app/components/Sidebar/components/SidebarLink.tsx, app/hooks/useClickIntent.ts, app/scenes/Document/components/ReferenceListItem.tsx
Quick win that I noticed on large shared sites. Refactored to a hook and moved the `RevisionListItem` to use this same logic
=> perf: Prefetch references on hover

app/editor/extensions/UpArrowAtStart.ts, app/scenes/Document/components/CommentEditor.tsx, app/scenes/Document/components/CommentForm.tsx, app/scenes/Document/components/CommentThread.tsx, app/scenes/Document/components/CommentThreadItem.tsx
Quick improvement to act like other best-in-class chat/commenting apps
closes #9700
=> feat: Up arrow in comment input should jump to editing previous comment

plugins/slack/server/auth/slack.test.ts, plugins/slack/server/auth/slack.ts
#9641
- Issue: Slack authentication fails with "Invalid authentication" error when both OIDC and Slack are enabled simultaneously.
- Root Cause: Slack authentication was not extracting the domain from the user's email address, unlike other auth providers (OIDC, Google, Azure, Discord).
- Fix: Added domain extraction from user's email in Slack auth to match the behavior of other authentication providers.
- Impact: Users can now authenticate with Slack even when OIDC is enabled, allowing organizations to use both authentication methods together.
=> fix: extract domain from user email in Slack authentication

shared/editor/plugins/TableLayoutPlugin.ts
Follow on https://github.com/outline/outline/pull/9792
=> fix: Error in TableLayoutPlugin when table does not exist in previous state

server/models/Revision.ts
=> fix: Remove revision data from event `changeset` as it is immutable

app/editor/menus/formatting.tsx, app/scenes/KeyboardShortcuts.tsx, shared/editor/marks/Highlight.ts
=> fix: duplicate highlight shortcut key label

app/scenes/Shared/index.tsx
=> fix: Missing `ROOT_SHARE_ID` default

app/scenes/Shared/index.tsx
`useRequest` updates the local React state while `Shared` scene depends on MobX store.
Intermediate render between the two state updates cause a flash of 404 page.
It's very subtle, doesn't happen all the time.
=> fix: Flash of 404 page due to timing diff between React & MobX state

app/components/SearchPopover.tsx, app/components/primitives/Popover.tsx
Turns out `PopoverAnchor` can be used in place of a trigger, rather than build a combobox.
Supersedes #9751
=> Migrate `SearchPopover` to Radix

app/utils/urls.test.ts, app/utils/urls.ts
=> fix: `/auth/` and `/s/` url paths should not be allowed as post-login redirect

app/components/InputColor.tsx
This should have been in a popover to start with, but alas, it was using the context menu primitive.
=> Move `ColorPicker` to Radix popover

app/components/Notifications/NotificationsPopover.tsx, app/stores/NotificationsStore.ts
Regressed in #9583 
Stumbled on it when migrating notifications menu to Radix.
=> fix: Prefetch non-archived notifications only

server/routes/api/shares/shares.test.ts, server/routes/api/shares/shares.ts
Allows revoking a collection share.
Related #9529
=> fix: Allow users to revoke a collection share

server/models/ApiKey.ts, server/policies/apiKey.ts, server/routes/api/apiKeys/apiKeys.test.ts, server/routes/api/apiKeys/apiKeys.ts
=> fix: Admins unable to revoke workspace API keys created by other users

vite.config.ts
Add support for `range` requests when using local file storage
=> fix: Remove `attachments.redirect` sw caching

package.json, yarn.lock
Somehow this dep was quite out of date and dependabot never mentioned it
=> chore: Upgrade `request-filtering-agent`

shared/editor/nodes/Image.tsx
=> fix: Prevent both img `parseDOM` rules matching

app/components/Sidebar/components/SidebarLink.tsx
Truncated labels now perfectly match line height and show ellipses. 
closes #9931
=> fix: Properly truncate multiline labels in sidebar

app/components/DocumentCopy.tsx, app/components/DocumentExplorer.tsx, app/hooks/useCollectionTrees.ts, app/scenes/DocumentMove.tsx, app/scenes/DocumentPublish.tsx
I said it in the issue, but I just can't quite understand how this was so broken – items in the dialog seemed quite "random" in use as a consequence of passing flattened trees into `DocumentExplorer`. Perhaps will dig deeper into the history tomorrow
closes #9946
=> fix: Document move/copy/publish dialog behavior

server/env.ts
=> fix: Unable to use `DATABASE_HOST` env

app/hooks/useEditorClickHandlers.ts, app/scenes/Collection/index.tsx, app/scenes/Document/components/Comments.tsx, app/scenes/Document/components/DataLoader.tsx, app/scenes/Document/components/History.tsx, app/stores/CollectionsStore.ts, app/stores/DocumentsStore.ts
I cannot reproduce the original issue but based on the stack trace ending up in `documents.get` with an undefined id this will address it. Also took the opportunity to remove the inefficient `getByUrl` method.
closes #9974
=> chore: Remove `getByUrl`

app/components/Lightbox.tsx
The next/prev image animates when navigating away from "Error loading image" component 👇 
https://github.com/user-attachments/assets/58ed2beb-73f5-44bc-a035-fe46b5052f14
=> Unset animation upon its completion

app/components/Lightbox.tsx
When the active image in Lightbox is deleted in editor, it zooms out to `(0, 0)` coords upon closing Lightbox.
=> Fix: Deleted image zooms out to `(0, 0)` upon closing Lightbox

app/editor/menus/formatting.tsx, shared/editor/commands/toggleList.ts, shared/editor/nodes/OrderedList.ts
This PR adds lettered lists to the editor. This means users can now use uppercase, or lowercase letters for their ordered lists instead of just numbers.
https://github.com/user-attachments/assets/2412e465-fffd-4ce7-87ee-f99de38e5a01
fixes #9489
=> feat: Ordered alphabetical lists

shared/editor/commands/splitHeading.ts
=> fix: Enter in empty heading after collapsed heading

server/utils/oauth.test.ts, server/utils/oauth.ts
Some OIDC providers return 401 Unauthorized errors with an empty body when the access token has expired.
Avoid trying to parse the body as JSON before we've checked whether the status code is OK.
Fixes #10251.
=> fix: Recognise authentication_required for some OIDC providers

server/routes/api/groups/groups.test.ts, server/routes/api/groups/groups.ts
This PR aims to allow users get the total number of groups when accessing the groups.list endpoint.
fixes: #10265
=> enhancement: return group total

app/components/Sidebar/hooks/useSidebarLabelAndIcon.tsx
Noticed that documents starred with a letter icon show as "?" in the sidebar
=> fix: Letter icon not displayed correctly in 'Starred' section

shared/editor/components/Image.tsx, shared/editor/nodes/Image.tsx
This PR address the chrome specific issue where downloading an image can lead to a CORS error if the image isn't properly cached.
It does this by catching the error and rerunning the download action with an added instruction to force an update on the image cache.
It also adds a fallback to open the image on a separate tab if the image cannot be downloaded for some reason or another.
fixes: #10261
Before: 
https://github.com/user-attachments/assets/59f0e545-bf00-48e6-ad5c-d5ee1e40d7e8
After: 
https://github.com/user-attachments/assets/97720566-cd41-4048-bd4d-89633f58f88e
=> fix CORS err on img download

app/components/Sidebar/components/SidebarLink.tsx
=> fix: Overlap of unread badge on long titles in sidebar

server/commands/documentCollaborativeUpdater.ts
Going with suppressing the timestamp modification here for now, the history is accurately stored in `revisions` table and this is a somewhat rare race condition.
closes  #10259
=> fix: Do not update `lastModifiedById` on deleted documents

Dockerfile, Dockerfile.base
- Use same Node.js version in build and runner image
- Reduce size of the image by applying the chown directly in the COPY
=> Small improvements to the Docker build

shared/editor/commands/toggleList.ts
This PR aims to fix the issue where changing a list type only applies to the list items at the top level and not the nested lists.
fixes #9382 
https://github.com/user-attachments/assets/1e2a714d-102a-4559-96ad-2f438b304001
=> fix: change list children to match list parent when list style changes
