shared/editor/components/Styles.ts
shared/editor/embeds/Trello.tsx
shared/editor/extensions/PasteHandler.ts
shared/editor/lib/markdown/serializer.ts
shared/editor/nodes/Embed.tsx
shared/editor/nodes/TableCell.ts
shared/editor/nodes/TableHeadCell.ts
shared/editor/rules/embeds.ts

Also cut the bottom of trello embeds so they look nicer 🙈

feat: Allow embeds to be used inside tables

---

shared/editor/extensions/Prism.ts
shared/editor/nodes/CodeFence.ts

Added Syntax Highlighting for JSX and TSX

feat: add syntax highlighting for jsx and tsx

---

Dockerfile

Tools like [Renovate](https://github.com/renovatebot/renovate), for automated dependency updates, make use of the OCI image source annotation to display a changelog, when a pull request with a new version is created.
https://docs.renovatebot.com/modules/datasource/docker/

Add OCI image source label

---

app/components/CollectionDescription.tsx
app/editor/components/SelectionToolbar.tsx
app/editor/components/ToolbarButton.tsx
app/editor/components/ToolbarMenu.tsx
app/editor/index.tsx
app/editor/menus/commenting.tsx
app/editor/menus/readOnly.tsx
app/scenes/Document/components/Document.tsx
shared/editor/components/Styles.ts
shared/editor/lib/Extension.ts
shared/editor/lib/ExtensionManager.ts
shared/editor/marks/Comment.ts
shared/editor/types/index.ts

Allows commenting outside edit mode when seamless editing is disabled.

---

app/components/ContentEditable.tsx

fix: Cursor jump on long title edit on Firefox

---

server/routes/api/searches/index.ts
server/routes/api/searches/schema.ts
server/routes/api/searches/searches.test.ts
server/routes/api/searches/searches.ts
server/test/factories.ts

Request validation for `/api/searches.*`

---

server/routes/api/shares/__snapshots__/shares.test.ts.snap
server/routes/api/shares/index.ts
server/routes/api/shares/schema.ts
server/routes/api/shares/shares.test.ts
server/routes/api/shares/shares.ts

Request validation for `/api/shares.*`

---

.env.sample
app.json

Resolve `OIDC_DISPLAY_NAME` mismatch

---

server/routes/api/developer/developer.ts
server/routes/api/developer/index.ts
server/routes/api/developer/schema.ts

Request validation for `/api/developer.*`

---

server/routes/api/stars/index.ts
server/routes/api/stars/schema.ts
server/routes/api/stars/stars.test.ts
server/routes/api/stars/stars.ts
server/validation.ts

Request validation for `/api/stars.*`

---

server/routes/api/subscriptions/index.ts
server/routes/api/subscriptions/schema.ts
server/routes/api/subscriptions/subscriptions.test.ts
server/routes/api/subscriptions/subscriptions.ts

Request validation for `/api/subscriptions.*`

---

server/queues/tasks/CommentCreatedNotificationsTask.ts
server/queues/tasks/CommentUpdatedNotificationsTask.ts
server/queues/tasks/DocumentPublishedNotificationsTask.ts
server/queues/tasks/RevisionCreatedNotificationsTask.ts

fix: Duplicate mentions results in duplicate notifications

---

server/presenters/unfurls/common.ts
server/presenters/unfurls/mention.ts
server/routes/api/urls/urls.ts

Display correct info in hover preview

---

app/components/HoverPreview/HoverPreview.tsx

Close hover preview upon scroll

---

app/components/HoverPreview/Components.tsx
app/components/HoverPreview/HoverPreview.tsx
app/components/HoverPreview/HoverPreviewDocument.tsx
app/components/HoverPreview/HoverPreviewLink.tsx
app/components/HoverPreview/HoverPreviewMention.tsx

Calculate `HoverPreview` position inside `useLayoutEffect`

---

app/actions/definitions/navigation.tsx
app/components/Header.tsx
app/components/Sidebar/components/HistoryNavigation.tsx
app/hooks/useWindowScrollPosition.ts
app/scenes/Document/components/MultiplayerEditor.tsx
app/scenes/KeyboardShortcuts.tsx
app/styles/index.ts
app/utils/Desktop.ts
app/utils/keyboard.ts
shared/editor/lib/isModKey.ts
shared/editor/nodes/CodeFence.ts
shared/utils/browser.ts

fix: `ctrl+a` does not work on Windows in code block

---

server/emails/mailer.tsx
server/emails/templates/BaseEmail.tsx
server/emails/templates/ConfirmUserDeleteEmail.tsx
server/emails/templates/ExportFailureEmail.tsx
server/emails/templates/ExportSuccessEmail.tsx
server/emails/templates/InviteAcceptedEmail.tsx
server/emails/templates/InviteEmail.tsx
server/emails/templates/InviteReminderEmail.tsx
server/emails/templates/SigninEmail.tsx
server/emails/templates/WebhookDisabledEmail.tsx
server/emails/templates/WelcomeEmail.tsx

Send `List-Unsubscribe` email header

---

app/components/HoverPreview/Components.tsx
app/components/HoverPreview/HoverPreview.tsx
app/components/HoverPreview/HoverPreviewLink.tsx

Re-position hover preview correctly to prevent going out of page bounds

---

app/components/Sidebar/components/SharedDocumentLink.tsx

Keep nested docs in shared sidebar collapsed by default

---

server/emails/mailer.tsx
server/emails/templates/BaseEmail.tsx
server/emails/templates/CollectionCreatedEmail.tsx
server/emails/templates/CommentCreatedEmail.tsx
server/emails/templates/CommentMentionedEmail.tsx
server/emails/templates/ConfirmUserDeleteEmail.tsx
server/emails/templates/DocumentMentionedEmail.tsx
server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx
server/emails/templates/ExportFailureEmail.tsx
server/emails/templates/ExportSuccessEmail.tsx
server/emails/templates/InviteAcceptedEmail.tsx
server/emails/templates/InviteEmail.tsx
server/emails/templates/InviteReminderEmail.tsx
server/emails/templates/SigninEmail.tsx
server/emails/templates/WebhookDisabledEmail.tsx
server/emails/templates/WelcomeEmail.tsx
server/emails/templates/components/EmailLayout.tsx

Go-To Actions with transactions emails

---

server/commands/userDemoter.ts
server/commands/userSuspender.ts
server/commands/userUnsuspender.ts
server/models/User.ts
server/routes/api/users/users.ts

fix: Add locks to user mutations

---

server/middlewares/multipart.ts
server/middlewares/validate.ts
server/routes/api/BaseSchema.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts

`multipart` middleware

---

server/commands/documentCreator.ts
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts

Allow setting createdAt, emoji properties through `documents.create`

---

Dockerfile

See https://github.com/outline/outline/issues/5716#issuecomment-1729851112

chore: Create data directory inside Dockerfile

---

plugins/webhooks/server/tasks/DeliverWebhookTask.ts
server/commands/userDemoter.test.ts
server/migrations/20230921071140-rename-collection-groups.js
server/migrations/20230922105047-rename-collection-users.js
server/models/Collection.ts
server/models/CollectionGroup.ts
server/models/CollectionUser.ts
server/models/Group.ts
server/models/GroupPermission.ts
server/models/User.test.ts
server/models/User.ts
server/models/UserPermission.ts
server/models/index.ts
server/policies/collection.test.ts
server/presenters/collectionGroupMembership.ts
server/presenters/membership.ts
server/queues/processors/WebsocketsProcessor.ts
server/routes/api/attachments/attachments.test.ts
server/routes/api/collections/collections.test.ts
server/routes/api/collections/collections.ts
server/routes/api/documents/documents.test.ts
server/routes/api/revisions/revisions.test.ts
server/routes/api/shares/shares.test.ts
server/routes/api/views/views.test.ts

`UserPermission` and `GroupPermission` models

---

server/commands/documentMover.ts
server/models/Collection.ts
server/models/Document.ts
server/queues/processors/RevisionsProcessor.ts
server/routes/api/documents/documents.ts
server/utils/jwt.ts

Quick fix of typescript types on these overriden methods

fix: Types on overridden findByPk methods

---

app/editor/components/FloatingToolbar.tsx
app/editor/components/SelectionToolbar.tsx
app/editor/components/ToolbarButton.tsx
app/editor/components/ToolbarMenu.tsx
app/editor/menus/formatting.tsx
shared/editor/marks/Code.ts
shared/editor/marks/Comment.ts
shared/editor/nodes/CodeFence.ts
shared/editor/nodes/index.ts
shared/editor/queries/isInCode.ts

feat: Allow commenting in code

---

app/components/Sidebar/components/Starred.tsx
app/hooks/usePaginatedRequest.ts
shared/i18n/locales/en_US/translation.json

`usePaginatedRequest` hook for simpler handling of pagination on FE

---

app/components/Editor.tsx
app/editor/index.tsx
app/scenes/Document/components/CommentForm.tsx
shared/i18n/locales/en_US/translation.json

Adds a specific button to make it clear that images can be added to comments (this was already possible through paste or drag and drop)

Add a button to upload images into comments

---

server/routes/api/urls/schema.ts
server/routes/api/urls/urls.test.ts
server/routes/api/urls/urls.ts
shared/i18n/locales/en_US/translation.json

New endpoint for frontend inputs to check whether a CNAME is correctly set and unique.

API: Add endpoint to check custom domain resolution

---

app/scenes/Document/components/DataLoader.tsx
app/scenes/Error402.tsx
app/utils/ApiClient.ts
app/utils/errors.ts
server/commands/documentCreator.ts
server/commands/documentLoader.ts
server/errors.ts
server/migrations/20231111023920-add-source-metadata.js
server/models/Document.ts
server/queues/tasks/ImportJSONTask.ts
server/queues/tasks/ImportMarkdownZipTask.ts
server/queues/tasks/ImportNotionTask.ts
server/queues/tasks/ImportTask.ts
server/routes/api/documents/documents.ts
shared/i18n/locales/en_US/translation.json
shared/types.ts

Storing useful metadata from the source of imported documents, .e.g original file name and type.

Store source metadata for imported documents

---

vite.config.ts

Closes #6139 
**Before**:
**After**:

Restore working of `babel-plugin-styled-components`

---

server/migrations/20231120074257-add-column-id-to-user-permissions.js
server/migrations/20231120142213-add-column-id-to-group-permissions.js
server/models/GroupPermission.ts
server/models/UserPermission.ts

Closes #6180 
Ported from [here](https://github.com/sequelize/sequelize/issues/2263#issuecomment-287467495).

Add column `id` to `user_permissions` and `group_permissions`

---

tsconfig.json

Set `noErrorTruncation` compiler flag

---

.circleci/config.yml
Dockerfile
Dockerfile.base

closes #6199 – tests got  25% faster 😱

Update tests and docker to Node 20 LTS

---

server/models/Document.test.ts
server/models/Document.ts

Document.findByPk() with `userId` and `rejectOnEmpty`

---

shared/editor/embeds/Tldraw.test.ts
shared/editor/embeds/Tldraw.tsx

feat: add support for tldraw snapshot links

---

server/migrations/20231206041706-search-query-score.js
server/models/SearchQuery.ts
server/presenters/searchQuery.ts
server/routes/api/searches/schema.ts
server/routes/api/searches/searches.test.ts
server/routes/api/searches/searches.ts

Add backend for scoring search results.

Add score column to `search_queries`

---

app/components/Editor.tsx
app/components/SearchListItem.tsx
app/components/SearchPopover.tsx
app/editor/components/LinkEditor.tsx
app/hooks/usePaginatedRequest.ts
app/scenes/Search/Search.tsx
app/stores/DocumentsStore.ts

Part of #4204
Towards #5918 
Towards #5337

Convert Search page to functional component

---

app/components/AuthenticatedLayout.tsx
app/components/Button.tsx
app/components/Layout.tsx
app/components/MobileScrollWrapper.tsx
app/components/Sidebar/Right.tsx
app/components/Sidebar/Sidebar.tsx
app/components/Tooltip.tsx
app/editor/components/FloatingToolbar.tsx
app/hooks/useEventListener.ts
app/hooks/useWindowSize.ts
app/index.tsx
app/scenes/Document/components/SidebarLayout.tsx
shared/styles/depths.ts

This goes a long way towards fixing #6242

fix: Positioning of editing toolbar on mobile devices

---

app/components/DocumentBreadcrumb.tsx
app/models/base/Model.ts
app/models/decorators/Relation.ts
app/stores/CollectionsStore.ts

closes https://github.com/outline/outline/issues/6230

fix: Load relationships on search page load

---

server/models/User.test.ts
server/models/User.ts
server/queues/processors/UserDeletedProcessor.test.ts
server/queues/processors/UserDeletedProcessor.ts

Separate relationship deletion from PII removal, including missing relationships 
closes OLN-171

fix: Cleanup relationships when user is deleted

---

shared/utils/urls.ts

fix: www. should not be counted as an internal URL

---

yarn.lock

Seeing some issues with checksum integrity, seems like we can now get sha-1 addition for speed

chore: Update checksums

---

app/stores/UsersStore.ts
server/models/helpers/TextHelper.ts
server/routes/api/schema.ts
shared/editor/embeds/YouTube.tsx
shared/editor/lib/FileHelper.ts

Seems to be the cause of build issues with latest versions of babel 🤔

fix: Remove try/catch statements without error argument

---

plugins/email/server/auth/email.test.ts
plugins/email/server/auth/email.ts
plugins/email/server/auth/schema.ts
plugins/slack/server/auth/schema.ts
plugins/slack/server/auth/slack.test.ts
plugins/slack/server/auth/slack.ts
server/models/helpers/AuthenticationHelper.ts

Zod schemas for routes under `/plugins`

---

server/routes/api/integrations/integrations.ts
server/routes/api/integrations/schema.ts

Add missing `integrations.info` endpoint

---

app/editor/extensions/SmartText.ts

Quick PR, based on discussion here:
https://github.com/outline/outline/discussions/6477

feat: replace (--) with emdash

---

server/commands/teamUpdater.ts
server/types.ts

This method was particularly embarrassing

chore: Simplify `teamUpdater` with changes from #6490

---

app/actions/definitions/developer.tsx
app/actions/definitions/documents.tsx
app/actions/index.ts
app/components/ActionButton.tsx
app/types.ts

Reduces plumbing going forward.
cc @apoorv-mishra as discussed

chore: Automatically display errors as toast if uncaught in actions

---

package.json
server/models/Attachment.ts
server/models/Document.ts
server/queues/processors/FileOperationDeletedProcessor.ts
server/queues/tasks/CollectionCreatedNotificationsTask.ts
server/queues/tasks/ImportNotionTask.ts
server/queues/tasks/ImportTask.ts
yarn.lock

- Handle latest Notion export directory structure
- Clear data on file operation delete
- Do not send notifications on bulk collection creation
- Decrease parallelization of file upload

chore: Various importer improvements

---

server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts

fix: Missing context in search results

---

shared/editor/embeds/Diagrams.tsx

Error for self-host draw.io

---

app/hooks/useMobile.ts

fix: show complete page without scrollbar in print view

---

plugins/oidc/server/env.ts
server/env.ts
server/index.ts
server/utils/startup.ts

fix: Restore env validation for plugins

---

app/actions/definitions/developer.tsx
app/env.ts
app/utils/sentry.ts
plugins/oidc/server/env.ts
plugins/slack/server/env.ts
server/env.ts
server/models/decorators/Public.ts
server/presenters/env.ts
server/routes/app.ts
server/test/setup.ts
server/utils/decorators/Public.ts
shared/env.ts
shared/types.ts
shared/utils/urls.ts

Share env vars client-side using `@Public` decorator

---

.eslintrc
app/editor/index.tsx
server/routes/api/index.ts
server/utils/decorators/Public.ts
server/utils/fetch.ts
server/utils/prefetchTags.tsx
server/utils/validators.ts
shared/editor/components/hooks/useDragResize.ts
shared/editor/lib/ExtensionManager.ts
shared/editor/lib/markdown/rules.ts
shared/editor/lib/markdown/serializer.ts
shared/editor/plugins/Suggestions.ts
shared/editor/rules/breaks.ts
shared/editor/rules/checkboxes.ts
shared/types.ts
shared/utils/ProsemirrorHelper.ts
shared/utils/date.ts
shared/utils/files.ts

Because https://github.com/outline/outline/commit/fc37070ac86e9ca325cd0e0d930deffe61b31df7 wasn't caught before merge. Fixed a few, but there are hundreds that will need gradually working through as files are touched.

chore: Add eslint rule for `no-shadow`

---

shared/editor/lib/markInputRule.ts
shared/editor/marks/Code.ts

fix: Backtick shortcut not applied correctly with composition

---

server/queues/tasks/ExportJSONTask.ts
server/queues/tasks/ImportJSONTask.ts
server/queues/tasks/ImportTask.ts
server/types.ts

Add title emoji support in JSON import/export

---

server/env.ts
server/storage/database.ts

As mentioned in #6669, I need support for specifying a custom Postgres schema. This PR seeks to implement this requirement.

feat: support custom db schema

---

plugins/azure/server/index.ts
plugins/email/plugin.json
plugins/email/server/index.ts
plugins/google/server/index.ts
plugins/iframely/server/index.ts
plugins/oidc/server/index.ts
plugins/slack/server/index.ts
plugins/storage/server/index.ts
plugins/webhooks/plugin.json
plugins/webhooks/server/index.ts
server/emails/templates/index.ts
server/models/helpers/AuthenticationHelper.ts
server/presenters/providerConfig.ts
server/queues/processors/index.ts
server/queues/tasks/index.ts
server/routes/api/authenticationProviders/authenticationProviders.ts
server/routes/api/index.ts
server/routes/api/urls/urls.ts
server/routes/auth/index.ts
server/utils/PluginManager.ts

`PluginManager` refactor

---

plugins/iframely/server/iframely.ts
plugins/iframely/server/index.ts
server/routes/api/urls/urls.test.ts
server/routes/api/urls/urls.ts
server/utils/CacheHelper.ts
server/utils/PluginManager.ts

Helper for cache related utilities

---

plugins/slack/server/api/hooks.ts
server/models/Comment.ts
shared/i18n/locales/en_US/translation.json

feat: Enable unfurling comments in Slack

---

server/migrations/20240329012958-remove-old-role-columns.js

Final step of migration to `role`, towards https://github.com/outline/outline/issues/2946
1. https://github.com/outline/outline/pull/6721
2. https://github.com/outline/outline/pull/6724
3. This PR.

chore: Remove `isViewer` and `isAdmin` columns

---

app/models/User.ts
server/models/Share.ts
server/models/User.ts
server/models/base/ParanoidModel.ts
server/policies/apiKey.ts
server/policies/attachment.ts
server/policies/authenticationProvider.ts
server/policies/collection.test.ts
server/policies/collection.ts
server/policies/comment.ts
server/policies/document.test.ts
server/policies/document.ts
server/policies/fileOperation.ts
server/policies/group.ts
server/policies/integration.ts
server/policies/notification.ts
server/policies/pins.ts
server/policies/searchQuery.ts
server/policies/share.ts
server/policies/star.ts
server/policies/subscription.ts
server/policies/team.ts
server/policies/user.ts
server/policies/userMembership.ts
server/policies/utils.ts
server/policies/webhookSubscription.ts
server/routes/api/documents/documents.test.ts
server/routes/api/groups/__snapshots__/groups.test.ts.snap
server/routes/api/users/__snapshots__/users.test.ts.snap
server/routes/api/users/users.test.ts

Policies are impossible to work on, this makes them nicer?

Policies refactor

---

app/components/DuplicateDialog.tsx
app/models/Document.ts
app/stores/DocumentsStore.ts
server/commands/documentDuplicator.test.ts
shared/i18n/locales/en_US/translation.json

feat: duplicate a document as draft

---

app/models/Team.ts
app/scenes/Settings/Security.tsx
server/migrations/20240413042634-member-team-create.js
server/models/Team.ts
server/policies/team.ts
server/presenters/team.ts
server/routes/api/teams/schema.ts
shared/i18n/locales/en_US/translation.json

Add security preference for workspace creation in cloud

---

app/components/DocumentListItem.tsx
server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts

fix: Improved phrase matching in search

---

app/components/HoverPreview/Components.tsx
app/components/HoverPreview/HoverPreview.tsx
app/editor/extensions/HoverPreviews.tsx
server/routes/api/urls/schema.ts

Fixes hover preview going out of window bounds

---

app/actions/definitions/documents.tsx
app/scenes/APITokenNew.tsx
app/scenes/Settings/Details.tsx
app/scenes/Trash/index.tsx
shared/i18n/locales/en_US/translation.json

**New token...** page.
A distinction should be made between **empty trash** and **empty**.

Handle several translation issues

---

app/components/Sharing/SharePopover.tsx
app/components/Sharing/UserSuggestions.tsx
app/models/Team.ts

Document share dialog should allow inviting new users

---

app/editor/extensions/SmartText.ts
shared/editor/lib/InputRule.ts

fix: Disable smart text replacements in code mark

---

app/actions/definitions/documents.tsx
server/policies/document.test.ts
server/policies/document.ts
server/routes/api/documents/documents.ts

fix: Policies on archived documents disallow unarchive

---

plugins/storage/server/api/files.ts
server/storage/files/BaseStorage.ts
server/storage/files/S3Storage.ts
shared/editor/components/Widget.tsx
shared/editor/nodes/Attachment.tsx

Allow PDF's to load in browser without download.

Use inline content disposition for common images and PDFs

---

app/components/InputMemberPermissionSelect.tsx
app/components/InputSelect.tsx
app/components/InputSelectPermission.tsx
app/components/Sharing/Collection/SharePopover.tsx
app/components/Sharing/Document/DocumentMemberListItem.tsx
app/components/Sharing/Document/SharePopover.tsx
app/components/WebsocketProvider.tsx

Part of https://github.com/outline/outline/issues/6454

feat: Adds permission selector in document/collection invite flow

---

app/components/Icons/CircleIcon.tsx
app/editor/components/ToolbarMenu.tsx
app/editor/menus/formatting.tsx
shared/editor/components/Styles.ts
shared/editor/lib/markInputRule.ts
shared/editor/marks/Highlight.ts
shared/editor/queries/getMarksBetween.ts
shared/editor/queries/isList.ts
shared/editor/queries/isMarkActive.ts
shared/editor/queries/isNodeActive.ts

Add more highlighter color choices

---

server/commands/documentCreator.ts
server/models/helpers/ProsemirrorHelper.tsx
server/models/helpers/TextHelper.ts

fix: Attributes lost creating template on server

---

app/scenes/Document/Shared.tsx
app/scenes/Document/components/Document.tsx
app/stores/DocumentsStore.ts
server/presenters/publicTeam.ts
server/routes/api/documents/documents.ts
shared/types.ts

feat: TOC position for publicly shared docs

---

app/scenes/Settings/Details.tsx
server/routes/api/teams/schema.ts
server/routes/api/teams/teams.test.ts

fix: Allow user to remove team logo

---

app/components/ArrowKeyNavigation.tsx
app/components/List/Item.tsx
app/components/PaginatedList.tsx
app/components/Sharing/Collection/SharePopover.tsx
app/components/Sharing/Document/SharePopover.tsx
app/components/Sharing/components/ListItem.tsx
app/components/Sharing/components/SearchInput.tsx
app/components/Sharing/components/Suggestions.tsx
app/scenes/Search/Search.tsx
app/scenes/Search/components/RecentSearches.tsx
package.json
shared/i18n/locales/en_US/translation.json
yarn.lock

Enable keyboard navigation in member invite list

---

app/scenes/Document/components/CommentForm.tsx
app/scenes/Document/components/CommentThread.tsx
app/scenes/Document/components/CommentThreadItem.tsx
app/scenes/Document/components/Comments.tsx
app/scenes/Document/components/HighlightText.ts

fix: Missing highlighted text on first comment while composing
closes #7103

fix: Unable to scroll until multiple comments

---

Dockerfile.base

Useful for healthchecks.
Related https://github.com/outline/outline/discussions/7051#discussioncomment-9810808

Add `HEALTHCHECK` into docker image

---

app/components/Icons/CollectionIcon.tsx
app/scenes/Collection/index.tsx
app/scenes/Document/components/Document.tsx
app/scenes/Document/components/DocumentTitle.tsx
shared/utils/IconLibrary.tsx

Allow direct editing of collection icon

---

server/routes/api/comments/comments.test.ts
server/routes/api/schema.ts
shared/editor/nodes/Image.tsx
shared/utils/ProsemirrorHelper.ts

Disallow empty comments and comments with only whitespaces

---

app/components/List/Item.tsx
app/components/Modal.tsx
app/components/Sharing/Collection/SharePopover.tsx
app/components/Sharing/components/Suggestions.tsx
app/hooks/useMaxHeight.ts
app/scenes/Collection/components/ShareButton.tsx
app/scenes/Document/components/ShareButton.tsx

Prevent modal top from shrinking

---

shared/editor/embeds/index.tsx

#7203 Added support for read only links format tldraw.com/ro/HASH

Add support for TLDR viewer links

---

server/commands/accountProvisioner.ts
server/commands/documentCreator.ts
server/commands/documentUpdater.ts
server/models/Document.test.ts
server/models/Document.ts
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts
server/routes/api/shares/shares.test.ts

fix: Outdated `updatedBy` returned in document mutations

---

app/components/Icon.tsx
app/scenes/Collection/index.tsx
app/scenes/Document/components/DocumentTitle.tsx

- Shares more logic between document and collection title
- Fixes icons being too tight with sidebar at tablet size
- Fixes icon fallback for collection not being a "light" component

fix: Inconsistencies with title icon positioning

---

plugins/oidc/server/auth/oidc.ts

Add `POST` handling for oidc callback

---

app/editor/components/ToolbarMenu.tsx
app/editor/menus/code.tsx
shared/editor/lib/code.ts
shared/editor/nodes/CodeFence.ts

Implementation for the feature discussed in #7211

feat: show frequent languages in code block menu

---

plugins/webhooks/client/components/WebhookSubscriptionForm.tsx
plugins/webhooks/server/tasks/DeliverWebhookTask.ts
server/migrations/20240709031512-group-permission-source-id.js
server/models/Collection.ts
server/models/Group.ts
server/models/GroupMembership.test.ts
server/models/GroupMembership.ts
server/models/UserMembership.ts
server/models/index.ts
server/presenters/collectionGroupMembership.ts
server/presenters/documentGroupMembership.ts
server/queues/processors/WebsocketsProcessor.ts
server/routes/api/collections/collections.test.ts
server/routes/api/collections/collections.ts
server/routes/api/documents/documents.test.ts
server/types.ts
shared/utils/EventHelper.ts

This aligns the naming with `UserMembership`
Setup for #6639
Related to #7268

chore: Rename `GroupPermission` -> `GroupMembership`

---

server/routes/api/users/users.test.ts
server/routes/api/users/users.ts

Previous code was silently dropping invites beyond 20.

fix: Error when passed too many user invites

---

server/commands/documentCreator.ts

Suppress document publish notification upon document creation

---

plugins/webhooks/server/tasks/DeliverWebhookTask.ts
server/routes/api/documents/documents.ts
server/types.ts

Ignore `documents.empty_trash` for `DeliverWebhookTask`

---

app/components/Sidebar/components/DocumentLink.tsx
app/scenes/Document/components/Document.tsx

fix: Ensure document changes are saved on unmount

---

server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts

Remove trailing spaces from search query

---

app/components/Sidebar/App.tsx
app/components/Sidebar/components/Collections.tsx
app/stores/UiStore.ts

Fetch collections upon initial load

---

server/migrations/20240806080954-group-users-paranoid.js
server/models/GroupUser.ts

Remove paranoid deletion from `GroupUser`

---

app/hooks/useEditorClickHandlers.ts
server/models/helpers/DocumentHelper.test.ts
server/models/helpers/DocumentHelper.tsx
server/models/helpers/ProsemirrorHelper.tsx
server/presenters/document.ts
server/routes/api/documents/documents.ts

fix: Copied internal links in shared documents are incorrect

---

server/migrations/20240810080954-group-users-remove-deleted-at.js

Follow up to https://github.com/outline/outline/pull/7356
Towards https://github.com/outline/outline/pull/7275

chore: Add PK to `group_users`, remove `deletedAt` column

---

app/scenes/Document/components/DataLoader.tsx
app/stores/base/Store.ts
server/routes/api/comments/comments.test.ts
server/routes/api/comments/comments.ts

Fixes several issues preventing reliable loading of comments

fix: Issues viewing document comments past default pagination

---

app/editor/components/SuggestionsMenu.tsx

fix  https://github.com/outline/outline/issues/7410

refactor: Improve search functionality in SuggestionsMenu

---

app/editor/extensions/SmartText.ts

fix: Do not replace smart quotes in code

---

app/hooks/useAutoRefresh.ts
app/hooks/useIdle.ts
app/scenes/Document/components/CommentThreadItem.tsx
plugins/github/server/index.ts
plugins/iframely/server/index.ts
plugins/slack/server/processors/SlackProcessor.ts
server/collaboration/ViewsExtension.ts
server/emails/templates/CommentCreatedEmail.tsx
server/emails/templates/CommentMentionedEmail.tsx
server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx
server/queues/HealthMonitor.ts
server/queues/processors/EmailsProcessor.ts
server/queues/queue.ts
server/routes/index.ts
server/services/cron.ts
server/services/web.ts
server/utils/CacheHelper.ts
shared/utils/time.ts

Specify time conversion unit

---

server/scripts/20240825000000-invalidate-unfurls-cache.ts
server/scripts/bootstrap.ts

chore: Script to invalidate unfurls cache

---

server/commands/teamPermanentDeleter.ts
server/models/base/Model.ts
server/queues/processors/WebsocketsProcessor.ts
server/types.ts

New `Replace` type utility

---

server/models/base/Model.test.ts
server/models/base/Model.ts

fix: Set DB batch limit

---

.circleci/config.yml
plugins/slack/server/api/hooks.test.ts
plugins/slack/server/auth/slack.test.ts
plugins/slack/server/auth/slack.ts
plugins/storage/server/api/files.test.ts
plugins/webhooks/server/processors/WebhookProcessor.test.ts
server/models/decorators/CounterCache.ts

fix: Include plugin tests on CI

---

shared/editor/extensions/Prism.ts
shared/editor/nodes/CodeFence.ts

feat: Adds 'Dockerfile' as language

---

server/migrations/20240912222438-add-unaccent-extension.js
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts

fix: Include results from users with accents in @mention search

---

app/editor/components/MentionMenu.tsx
app/editor/components/SuggestionsMenu.tsx
app/stores/UsersStore.ts
shared/i18n/locales/en_US/translation.json

feat: Add ability to tag users out of document

---

plugins/oidc/server/auth/oidc.ts
server/commands/teamProvisioner.test.ts
server/commands/teamProvisioner.ts
server/utils/passport.ts

fix: OIDC signin to prevent duplicate auth providers

---

server/commands/groupCreator.ts
server/commands/groupDestroyer.ts
server/commands/groupUpdater.ts
server/commands/groupUserCreator.ts
server/commands/groupUserDestroyer.ts
server/routes/api/groups/groups.ts

In an effort to add OIDC group mapping in our fork (https://github.com/Japan7/outline/commit/183b884911f227d58fc90c9aad65024b7611c3ac), I've created several commands for `Group` and `GroupUser` that I believe could also be integrated upstream.

feat: group/groupuser commands

---

shared/editor/commands/codeFence.ts
shared/editor/nodes/CodeFence.ts
shared/editor/queries/findStartOfLine.ts

Adds natural behavior of `Tab`, `Shift-Tab` in code blocks

---

app/components/Sharing/Document/AccessControlList.tsx
app/components/Sharing/Document/PublicAccess.tsx
app/components/Sharing/components/index.tsx

Sticky public access toggle

---

server/models/Document.ts

fix: Correctly decorate urlId as Unique

---

server/queues/tasks/CommentCreatedNotificationsTask.ts
server/queues/tasks/CommentUpdatedNotificationsTask.ts
server/queues/tasks/DocumentPublishedNotificationsTask.ts
server/queues/tasks/RevisionCreatedNotificationsTask.ts
server/utils/policies.ts

Follow-up to [this commit](https://github.com/outline/outline/commit/e032bb5ab8ace06329d131ce301af5d847d4f5ff)

fix: check doc access before sending mention email

---

server/models/Document.ts

perf: use findAll for querying document collaborators

---

app/components/WebsocketProvider.tsx
app/models/Document.ts
app/models/base/ArchivableModel.ts
app/models/decorators/Relation.ts
app/stores/AuthStore.ts
app/stores/DocumentsStore.ts
app/stores/base/Store.ts
app/types.ts
server/models/Document.ts
server/models/base/ArchivableModel.ts

Show nested docs on Archive page

---

server/queues/tasks/ImportTask.ts
server/utils/ZipHelper.ts
server/utils/fs.test.ts
server/utils/fs.ts

fix: Error during import with long filenames

---

server/models/Backlink.ts
server/models/Document.test.ts
server/models/Document.ts
server/routes/api/documents/documents.ts
server/test/factories.ts

fix: show all document backlinks for a user

---

server/emails/templates/DocumentMentionedEmail.tsx
server/emails/templates/components/Diff.tsx
server/models/helpers/DocumentHelper.tsx
server/models/helpers/ProseMirrorHelper.test.ts
server/models/helpers/ProsemirrorHelper.tsx
server/queues/processors/EmailsProcessor.ts
server/test/factories.ts

feat: include content in document mentioned email

---

app/editor/extensions/Multiplayer.ts
shared/editor/components/Styles.ts

Hide remote users selections after a timeout

---

app/components/HoverPreview/HoverPreview.tsx
app/components/HoverPreview/HoverPreviewMention.tsx
app/editor/extensions/MentionMenu.tsx
server/policies/user.ts
server/policies/utils.ts
server/presenters/unfurl.ts
server/presenters/user.ts
server/routes/api/urls/urls.ts
server/routes/api/users/users.test.ts
server/routes/api/users/users.ts
shared/types.ts

Allow querying by user emails in order to `@mention` them

---

app/components/SearchPopover.tsx
app/components/Sidebar/Shared.tsx

fix: add sidebar toggle for public docs

---

server/models/Document.ts

fix: check collection group membership for backlinks

---

app/components/Sidebar/Sidebar.tsx

fix: Do not consider hover activity when page/window is out of focus

---

server/migrations/20241030235556-event-auth-type.js
server/models/Event.ts

Track which auth type events are created from, going forward.
towards #7845

Add `authType` column to events

---

plugins/webhooks/server/api/webhookSubscriptions.ts
server/commands/collectionDestroyer.ts
server/commands/documentCollaborativeUpdater.ts
server/commands/revisionCreator.test.ts
server/commands/revisionCreator.ts
server/commands/subscriptionCreator.ts
server/commands/teamUpdater.ts
server/models/Event.ts
server/queues/processors/RevisionsProcessor.ts
server/routes/api/apiKeys/apiKeys.ts
server/routes/api/attachments/attachments.ts
server/routes/api/auth/auth.ts
server/routes/api/authenticationProviders/authenticationProviders.ts
server/routes/api/collections/collections.ts
server/routes/api/comments/comments.ts
server/routes/api/documents/documents.ts
server/routes/api/userMemberships/userMemberships.ts
server/routes/api/users/users.ts
server/types.ts

chore: `Event.createFromContext` usage

---

server/emails/templates/BaseEmail.tsx
server/emails/templates/CommentCreatedEmail.tsx
server/emails/templates/CommentMentionedEmail.tsx
server/emails/templates/DocumentMentionedEmail.tsx
server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx
server/routes/api/teams/schema.ts
shared/constants.ts
shared/types.ts

Add security preference to remove document content in email notifications

Add new security preference

---

app/components/Editor.tsx
app/scenes/Document/components/CommentEditor.tsx
app/scenes/Document/components/Editor.tsx
app/scenes/Settings/Preferences.tsx
shared/constants.ts
shared/i18n/locales/en_US/translation.json
shared/types.ts

Closes [#7769 Add user preference to disable smart quotes](https://github.com/outline/outline/issues/7769)
The last commit can potentially be removed if we don't care about that scenario. See commit message for details.

Add user preference to disable smart quotes

---

shared/editor/components/Styles.ts

fix: heading disclosure transform

---

app/models/User.ts
app/stores/AuthStore.ts
server/migrations/20241105203523-add-user-timezone.js
server/models/User.ts
server/presenters/__snapshots__/user.test.ts.snap
server/presenters/user.ts
server/routes/api/users/schema.ts
server/routes/api/users/users.test.ts
server/routes/api/users/users.ts
server/utils/zod.ts

feat: store user timezone

---

app/stores/DocumentsStore.ts
package.json
server/utils/DocumentConverter.test.ts
server/utils/DocumentConverter.ts
yarn.lock

I wasn't planning on adding this, but it's a quick win and people keep trying to import these files – so 🤷

feat: Adds support for importing CSV files

---

app/components/Sharing/Document/PublicAccess.tsx
app/models/Share.ts
server/migrations/20241105132600-add-allowIndexing-to-shares.js
server/models/Share.ts
server/presenters/share.ts
server/routes/api/shares/schema.ts
server/routes/api/shares/shares.ts
server/routes/app.ts
server/static/index.html
shared/i18n/locales/en_US/translation.json

Closes #7486
- Added `nofollow` as well.

share: add `allowIndexing`

---

app/components/CommandBar/useTemplatesAction.tsx
app/stores/DocumentsStore.ts
server/queues/processors/WebsocketsProcessor.ts

fix: show all templates in the menu

---

app/scenes/Document/components/Editor.tsx

show resolved view when a resolved comment is opened from notif email

---

.circleci/config.yml

20% reduction in build time by only starting postgres and redis for server tests.

Reduce build time

---

vite.config.ts

Another 30s saved on build time

Remove sourcemap generation in bundle size calc

---

app/components/Reactions/ReactionPicker.tsx
app/scenes/Document/components/CommentThreadItem.tsx
shared/i18n/locales/en_US/translation.json

Moves the resolve functionality inline at the top of comment threads for easier use

Add inline resolve action on comment threads

---

app/stores/UiStore.ts

Fixes the inconsistency when changing themes.

Persist theme after update

---

server/storage/files/S3Storage.ts

fix: S3 expiry not passed correctly

---

server/migrations/20241127151705-attachment-tracking.js
server/models/Team.ts
server/queues/tasks/UpdateTeamAttachmentsSizeTask.ts
server/queues/tasks/UpdateTeamsAttachmentsSizeTask.ts

Some busy work that's been needed for a while for cloud hosting – track on team the amount of storage size being used.

Tracking of total uploaded attachments / team

---

app/scenes/Document/components/Document.tsx

Cleans up a random test string rendered in the document

Cleanup random text

---

app/menus/TemplatesMenu.tsx
app/scenes/Document/components/Document.tsx
app/utils/date.ts
server/commands/documentCreator.ts
server/models/helpers/ProsemirrorHelper.tsx
server/models/helpers/TextHelper.ts
shared/utils/ProsemirrorHelper.ts
shared/utils/TextHelper.test.ts
shared/utils/TextHelper.ts

fix: Template variables are not applied on client

---

app/components/Breadcrumb.tsx
app/components/Collaborators.tsx
app/components/DocumentBreadcrumb.tsx
app/components/Header.tsx
app/components/Sidebar/Right.tsx
app/menus/TemplatesMenu.tsx
app/scenes/Document/components/Header.tsx

Elements in the document header will now better adjust to available space rather than wrapping over the right sidebar

fix: Improved responsiveness of document header elements

---

app/editor/components/FindAndReplace.tsx
app/editor/extensions/FindAndReplace.tsx

Adds count of occurences and index to find and replace

---

app/menus/DocumentMenu.tsx
app/scenes/Document/components/DataLoader.tsx
app/scenes/Document/components/Document.tsx

@infinite-persistence should fix both issues you reported
closes #8073

fix: Embed toggle is unresponsive

---

app/components/DocumentBreadcrumb.tsx
app/components/Sidebar/components/SidebarContext.ts
app/models/Document.ts

Couple of quick follow ons from https://github.com/outline/outline/pull/7956

fix: Use sidebarContext in header breadcrumbs

---

server/queues/processors/DocumentUserAddedProcessor.ts

Small update to ensure that you're subscribed to changes upon having a document shared.

fix: Subscribe to document automatically on share

---

server/emails/templates/CommentCreatedEmail.tsx
server/emails/templates/DocumentPublishedOrUpdatedEmail.tsx
server/models/helpers/NotificationHelper.ts

fix: Permissions checks on notification emails do not take into account shares

---

app/editor/menus/formatting.tsx
shared/editor/marks/Comment.ts
shared/editor/queries/isMarkActive.ts

fix: Cannot leave overlapping comments

---

app/editor/extensions/EmojiMenu.tsx
app/hooks/usePersistedState.ts
shared/editor/lib/table.ts
shared/utils/browser.ts
shared/utils/urls.ts

fix: Exported HTML does not include table column sizes

---

server/commands/documentCollaborativeUpdater.ts
server/models/Document.ts
server/models/GroupMembership.ts
server/models/UserMembership.ts
server/models/helpers/SearchHelper.ts
server/queues/processors/WebsocketsProcessor.ts

Exclude state column by default in document queries

---

server/models/helpers/DocumentHelper.test.ts
shared/editor/lib/textBetween.ts

fix: textBetween line breaks

---

app/models/Group.ts
server/commands/groupCreator.ts
server/commands/groupUpdater.ts
server/migrations/20241219023150-group-external-id.js
server/models/Group.ts
server/presenters/group.ts
server/routes/api/groups/groups.test.ts
server/routes/api/groups/groups.ts
server/routes/api/groups/schema.ts

Only accessible through the API for now.
closes #8099

Add `externalId` property on groups

---

plugins/webhooks/server/api/webhookSubscriptions.test.ts
plugins/webhooks/server/api/webhookSubscriptions.ts
server/models/WebhookSubscription.ts

Convert `WebhookSubscription` mutations

---

shared/editor/components/Caption.tsx
shared/editor/components/ImageZoom.tsx
shared/editor/nodes/Image.tsx
shared/editor/nodes/Video.tsx

fix: Scale width of caption with image

---

app/editor/extensions/FindAndReplace.tsx

fix: Highlight matching mentions in find and replace

---

server/models/helpers/NotificationHelper.ts

fix: Notify previously mentioned users when new comment is added to a thread

---

app/editor/extensions/ClipboardTextSerializer.ts
app/editor/index.tsx
server/models/helpers/DocumentHelper.tsx
shared/editor/commands/table.ts
shared/editor/lib/textSerializers.ts
shared/utils/ProsemirrorHelper.ts

fix: Incorrect plain text serialization in `exportTable`

---

server/queues/tasks/ImportJSONTask.ts

Reverts outline/outline#8183 closes #8240

Revert "Preserve JSON Document Sorting Order During Import "

---

app/editor/extensions/FindAndReplace.tsx
shared/editor/nodes/Mention.ts

fix: Mentions should not be able to contain node content

---

app/editor/index.tsx
app/scenes/Document/components/Editor.tsx
shared/editor/components/Styles.ts

There's actually a bunch more to do here, I have a refactor of the rtl logic in mind – but this moves things in the right direction and closes #8207

fix: Improve styling with mixed RTL content

---

app/editor/components/NodeViewRenderer.tsx
app/editor/index.tsx

fix: NodeView does not re-render when editable prop changes

---

server/models/Collection.ts
server/models/Document.ts
server/models/GroupMembership.ts
server/routes/api/collections/collections.ts
server/routes/api/documents/documents.ts
server/types.ts

Convert `GroupMembership` mutations

---

app/scenes/Document/Shared.tsx
app/scenes/Document/components/Document.tsx
app/scenes/Document/components/Header.tsx

fix: Render TOC only when the shared document has headings

---

server/models/Collection.ts
server/models/UserMembership.ts
server/routes/api/collections/collections.ts
server/routes/api/documents/documents.ts
server/types.ts

Convert `UserMembership` mutations

---

plugins/azure/server/auth/azure.ts
plugins/discord/server/auth/discord.ts
plugins/oidc/server/auth/oidc.ts
server/utils/passport.ts

fix: Dropbox OIDC requires POST to `userinfo` endpoint

---

app/components/Avatar/Avatar.tsx
app/components/Avatar/AvatarWithPresence.tsx
app/components/Avatar/Initials.tsx
app/components/Collaborators.tsx
app/components/DocumentViews.tsx
app/components/EventListItem.tsx
app/components/Facepile.tsx
app/components/Sharing/Collection/AccessControlList.tsx
app/components/Sharing/Document/AccessControlList.tsx
app/components/Sharing/Document/DocumentMemberListItem.tsx
app/components/Sharing/components/Suggestions.tsx
app/components/Sidebar/Shared.tsx
app/components/Sidebar/Sidebar.tsx
app/editor/components/MentionMenu.tsx
app/scenes/Collection/components/MembershipPreview.tsx
app/scenes/Document/components/CommentThread.tsx
app/scenes/Document/components/Insights.tsx
app/scenes/Login/index.tsx
app/scenes/Search/components/UserFilter.tsx
app/scenes/Settings/components/GroupDialogs.tsx
app/scenes/Settings/components/ImageInput.tsx
app/scenes/Settings/components/PeopleTable.tsx
plugins/github/client/Settings.tsx

Change facepile to clip path

---

server/commands/subscriptionCreator.test.ts

fix: Flaky subscriptionCreator test

---

app/actions/definitions/documents.tsx

Tiny change - not sure why it wasn't available before..

Allow creation of nested document from command bar

---

server/queues/processors/DocumentSubscriptionProcessor.ts
server/queues/tasks/DocumentSubscriptionTask.ts

Manage document subscription when a group is added to (or) removed from a document

---

app/actions/definitions/documents.tsx
app/menus/DocumentMenu.tsx
app/models/Document.ts
app/stores/DocumentsStore.ts
app/stores/SubscriptionsStore.ts
server/routes/api/subscriptions/subscriptions.test.ts
server/routes/api/subscriptions/subscriptions.ts

Allow reusing subscription data from the store.
Towards #7340

Fetch subscription data using 'subscriptions.info' API

---

package.json
server/models/helpers/DocumentHelper.tsx
server/queues/tasks/RevisionCreatedNotificationsTask.ts
server/typings/index.d.ts
yarn.lock

Prevents notification emails being sent for small and invisible changes

fix: Notifications sent for insignificant changes

---

app/scenes/Document/components/Header.tsx

Hides templates dropdown menu for viewers and guests

fix: Guard templates dropdown menu

---

app/components/Sidebar/App.tsx
app/components/Sidebar/components/DraftsLink.tsx
app/components/Sidebar/hooks/useDragAndDrop.tsx
app/components/WebsocketProvider.tsx
app/models/Document.ts
app/stores/DocumentsStore.ts
server/models/Document.ts
server/queues/processors/WebsocketsProcessor.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts
server/types.ts

Enable dragging a document into drafts

---

server/migrations/20250217012609-document-title-index.js

perf: Add trigram index for doc title search

---

app/editor/extensions/PasteHandler.tsx
plugins/storage/server/api/files.test.ts
plugins/storage/server/api/files.ts
server/routes/api/attachments/attachments.ts
server/storage/files/BaseStorage.ts
server/utils/fetch.ts
shared/editor/components/Caption.tsx

Fixes a bunch of separate issues related to pasting content with images.
closes #8457

fix: copy pasting the content from some medium into outline does not get the images

---

app/components/Sidebar/components/ArchiveLink.tsx
app/components/Sidebar/components/SidebarContext.ts

Sets sidebar context for archive section

fix: Set sidebar context for archive section

---

app/components/EventListItem.tsx
app/components/PaginatedEventList.tsx
app/components/PaginatedList.tsx
app/scenes/Document/components/History.tsx
app/stores/RevisionsStore.ts
server/routes/api/events/events.test.ts
server/routes/api/events/events.ts
server/routes/api/events/schema.ts
server/routes/api/revisions/revisions.ts
shared/utils/EventHelper.ts

Reverts outline/outline#8495 – @hmacr this reverts the revert, easiest would be to push your fixes to this branch
Also, closes #8487

Move document history to `revisions.list` API

---

app/components/InputSelect.tsx
app/components/Sharing/Collection/AccessControlList.tsx
server/models/GroupMembership.ts
server/models/UserMembership.ts

fix: Prevent last user/group with collection manage permission being removed

---

app/menus/TableOfContentsMenu.tsx

Wrap headings on mobile ToC

---

app/editor/components/FloatingToolbar.tsx
app/editor/components/SelectionToolbar.tsx
app/editor/menus/notice.tsx
shared/editor/nodes/Notice.tsx
shared/editor/queries/isInNotice.ts

feat: change notice type

---

app/components/Notifications/Notifications.tsx

feat: Badging icon for installed PWA

---

server/models/User.test.ts
server/models/User.ts

https://github.com/outline/outline/pull/8582 just failed with this

test: Fix flaky `availableTeams` test

---

app/components/ContextMenu/MenuItem.tsx
app/editor/components/Input.tsx
app/editor/components/LinkEditor.tsx
app/editor/components/MentionMenu.tsx
app/editor/components/SuggestionsMenuItem.tsx

Back due to popular demand 😆 
closes #8444

feat: Restore document search in link toolbar

---

app/components/Fade.ts
app/components/Fade.tsx
app/scenes/Search/components/RecentSearches.tsx
app/scenes/Settings/Groups.tsx
app/scenes/Settings/Members.tsx
app/scenes/Settings/Shares.tsx
app/scenes/Settings/components/MembersTable.tsx

Just a minor jank annoyance, introduced a `ConditionalFade` component for these cases.

fix: Members table always fades in

---

app/scenes/Document/components/MultiplayerEditor.tsx
app/stores/DocumentPresenceStore.ts
app/types.ts

Regressed in 225449796a68ba91df5d119b88a72016a106206c

fix: Current user presence in documents is incorrect

---

server/routes/api/collections/collections.ts
server/routes/api/collections/schema.ts

feat: Add query parameter to `collections.list`

---

app/actions/definitions/documents.tsx
app/components/CommandBar/CommandBarItem.tsx
shared/utils/keyboard.ts

Customer requested, a quick shortcut (cmd+/) to search in the specific document context.

feat: Add `Search in document` to command menu, add shortcut

---

shared/editor/commands/table.ts
shared/editor/nodes/Table.ts

https://github.com/user-attachments/assets/2f793dc2-03d9-4294-80f4-2163e0473e64
closes #8590

fix: Creates a gap cursor position between tables positioned next to each other

---

app/components/ContextMenu/MenuItem.tsx

fix: Danger button focus ring [quick]

---

app/models/Revision.ts
server/migrations/20250301234423-add-name-to-revisions.js
server/models/Revision.ts
server/policies/index.ts
server/policies/revision.ts
server/presenters/revision.ts
server/routes/api/revisions/revisions.test.ts
server/routes/api/revisions/revisions.ts
server/routes/api/revisions/schema.ts
server/routes/api/shares/shares.test.ts
shared/validations.ts

Add `name` column to revisions

---

app/components/LocaleTime.tsx
app/hooks/useLocaleTime.ts

Hook is needed elsewhere, backporting to community ed.

Add `useLocaleTime`

---

app/scenes/Document/components/Document.tsx

fix: Apply full width from template

---

shared/editor/marks/Code.ts

Allow links in code marks

---

app/stores/CollectionsStore.ts

fix: Filter archived collections in start view selection

---

server/queues/processors/DocumentSubscriptionProcessor.ts
server/queues/tasks/DocumentSubscriptionTask.ts

Changing the auto subscription behaviour as it may lead to noisy notifications.

fix: Skip auto creating subscriptions when user/group is added to a document

---

server/queues/tasks/DocumentSubscriptionTask.ts

Follow-on from #8630 
Related #8354

fix: Skip unsubscribing when user has access to document

---

shared/editor/embeds/index.tsx

fix: Add more tldraw url support

---

app/models/Document.ts
app/models/FileOperation.ts
app/scenes/Search/components/DocumentFilter.tsx

Add missing relationship decorators

chore: Misc fixes

---

package.json
yarn.lock

Partially revert https://github.com/outline/outline/pull/8652

chore: Bump `dd-trace`

---

shared/editor/marks/Code.ts
shared/editor/nodes/CodeFence.ts

fix: Inline code converts to block on paste from remote source

---

shared/editor/nodes/CheckboxItem.ts
shared/editor/nodes/ListItem.ts

A simple change in the spec
closes #8611
closes #8216

fix: First item in list must be a paragraph

---

shared/editor/commands/table.ts
shared/utils/csv.test.ts
shared/utils/csv.ts

This method wasn't covering quite enough characters

chore: Improve CSV output sanitization

---

app/components/EventListItem.tsx
app/components/List/Item.tsx

fix: Styling of selected event list item

---

.jestconfig.json

Double test timeout

---

server/emails/mailer.tsx

Improves DX, especially on low bandwidth connections

chore: Always log outgoing emails in development

---

app/scenes/Settings/Preferences.tsx
app/scenes/Settings/Security.tsx

Towards #6456 
Additional components from #8541

Migrate language, theme and user-role input-select to Radix

---

server/models/UserAuthentication.ts

fix: Write `lastValidatedAt` when accessToken changes

---

app/components/WebsocketProvider.tsx
server/queues/processors/WebsocketsProcessor.ts

fix: Add missing `users.delete` event handling

---

app/components/CollectionDescription.tsx
app/editor/index.tsx

fix: Mentions of current user not highlighted

---

app/components/Editor.tsx
app/models/Document.ts
shared/types.ts
shared/utils/ProsemirrorHelper.test.ts
shared/utils/ProsemirrorHelper.ts

Updated type to prevent future regression
closes #8729

fix: Error rendering read only editor with paragraph without text content

---

server/queues/tasks/ValidateSSOAccessTask.ts

Refactor logic for validating authentication tokens

---

.jestconfig.json

Revert "Double test timeout"

---

app/editor/components/SuggestionsMenuItem.tsx
app/editor/extensions/Suggestion.ts

fix: Allow dash,emdash,underscore in mention search

---

app/components/WebsocketProvider.tsx
server/services/websockets.ts

Reverts outline/outline#8582 – moving this to collaboration server where it belongs

Revert "Send editor version down websocket and force reload"

---

app/components/ConnectionStatus.tsx
app/scenes/Document/components/MultiplayerEditor.tsx
server/collaboration/CloseEvents.ts
server/collaboration/ConnectionLimitExtension.ts
server/collaboration/EditorVersionExtension.ts
server/routes/api/middlewares/editor.ts
server/services/collaboration.ts
shared/collaboration/CloseEvents.ts

Prevent outdated clients from connecting to collaboration server

---

plugins/storage/server/api/files.test.ts
server/test/TestServer.ts

fix: Do not wait for connections at end of test suites

---

server/routes/api/notifications/notifications.test.ts
server/routes/api/notifications/notifications.ts

`notifications.pixel` was hanging in production due to ctx not having auth, added tests.

fix: `notifications.pixel` requests hang

---

plugins/notion/client/Imports.tsx
plugins/notion/server/env.ts

fix: Disable Notion import when env is not available

---

package.json
plugins/oidc/server/auth/OIDCStrategy.ts
plugins/oidc/server/auth/oidc.ts
server/utils/passport.ts
yarn.lock

fix: Use configured proxy for OIDC server-to-server requests

---

.github/dependabot.yml

Revert "Change @aws-sdk dependency update frequency from weekly to monthly"

---

server/models/helpers/NotificationHelper.ts

Noticed while working on https://github.com/outline/outline/pull/8734 that this is querying all users in the team unnecessarily when `onlySubscribers: true`

perf: Avoid querying all users in team for common notification types

---

.github/config.yml

Remove maintainers from probot "more information" behavior

---

server/models/Collection.ts
server/routes/api/collections/collections.test.ts
server/routes/api/collections/collections.ts
server/utils/removeIndexCollision.ts
server/validation.ts

Closes #8795 
~Draft since we might need a script to correct the existing indexes - could be a separate PR?~
Correction script will be a separate PR

fix: Handle index collision when creating a collection

---

.github/workflows/lint.yml

chore: Attempt auto-lint of Codegen PR's

---

.github/workflows/lint.yml

chore: Change lint rule to trigger on actor rather than branch name

---

shared/editor/commands/toggleList.ts

fix: Handle switching between regular lists and todo lists

---

server/queues/processors/DocumentSubscriptionProcessor.ts
server/queues/tasks/CollectionSubscriptionRemoveUserTask.ts
server/queues/tasks/CollectionSubscriptionTask.ts
server/queues/tasks/DocumentSubscriptionRemoveUserTask.ts

Manage collection subscriptions when user (or) group is removed from a collection

---

app/models/Import.ts
app/scenes/Settings/components/ImportListItem.tsx
server/migrations/20250327110739-add-error-to-imports.js
server/models/Import.ts
server/models/ImportTask.ts
server/presenters/import.ts
server/queues/processors/ImportsProcessor.ts
server/queues/tasks/APIImportTask.ts
server/queues/tasks/ErrorTimedOutImportsTask.ts

This PR enables storing API import flow errors in DB - useful for debugging.

Store import error in DB

---

shared/editor/nodes/Mention.tsx

fix: Show @ symbol on mentions in email snippets

---

app/editor/components/SuggestionsMenu.tsx

chore: Missing react key in SuggestionMenu

---

app/editor/extensions/PasteHandler.tsx
shared/editor/queries/isInCode.ts
shared/editor/queries/isMarkActive.ts
shared/editor/queries/isNodeActive.ts

fix: Paste partially over code prevents pasting PM nodes

---

app/components/Fade.tsx
app/scenes/Document/components/CommentThread.tsx
shared/hooks/useComponentSize.ts

closes #8834
regressed in https://github.com/outline/outline/pull/8338

fix: New comments are measured incorrectly

---

shared/editor/lib/table.ts

fix: Table columns sometimes lost in copy paste

---

server/queues/processors/ImportsProcessor.ts

Log fields that cause UniqueConstraintError in ImportsProcessor

---

plugins/discord/server/auth/discord.ts
server/commands/accountProvisioner.test.ts
server/commands/accountProvisioner.ts

fix: Allow OIDC without team name

---

app/actions/definitions/documents.tsx
app/models/Document.ts
shared/i18n/locales/en_US/translation.json

Add option to copy as plain text

---

server/models/Document.test.ts
server/models/Document.ts

Closes #8867 
Related #8042 
Note: There are other bugs in archive / delete / restore flows. This PR addresses just the reported one.

fix: Update collection 'documentStructure' when archived document is deleted

---

.eslintrc
app/stores/base/Store.ts

Might be nice to catch the inconsistent imports in pre-commit hook.

eslint: Increase severity to error for lodash imports

---

app/editor/extensions/ClipboardTextSerializer.ts

fix: Markdown copy should not occur for single node situations

---

shared/editor/components/Styles.ts
shared/editor/extensions/CodeHighlighting.ts

fix: Text color of plain text and markdown code blocks
Related to https://github.com/outline/outline/pull/8934

fix: Line numbers in code blocks flash in on load

---

app/editor/components/PasteMenu.tsx

Regression in https://github.com/outline/outline/pull/8870

fix: Editor crashes on shared page with no user

---

shared/editor/extensions/CodeHighlighting.ts
shared/editor/lib/code.ts

This is a shame, but at least it's maintainable
closes #8957

fix: Hardcode dynamic imports to avoid production issues

---

app/scenes/Settings/components/ImageUpload.tsx

Started out as a couple of bug fixes (stated in title) and ended up refactoring a bit to use existing patterns.

fix: Reset avatar zoom, set missing text in upload button

---

shared/editor/extensions/CodeHighlighting.ts

perf: Cache promise when loading code languages

---

shared/editor/nodes/Image.tsx

fix: Full-width image control should act as toggle

---

app/components/Modal.tsx
app/scenes/Invite.tsx

fix: Small modal overflow scrolling behavior

---

app/stores/base/Store.ts

fix: Deleted users appear in mention menu before search query

---

app/components/Table.tsx
app/scenes/Settings/components/MembersTable.tsx

fix: Improve settings table layout on mobile

---

shared/editor/components/Styles.ts

fix: Overflow on math blocks

---

plugins/storage/server/api/files.test.ts
plugins/storage/server/api/files.ts
server/models/Attachment.ts

fix: Cannot load avatars in some instances

---

shared/editor/components/Styles.ts

fix: Heading weight changes when linkified

---

plugins/linear/server/linear.ts

fix: Linear status icon completion percentage edge case

---

plugins/linear/server/api/linear.ts
plugins/linear/server/index.ts
plugins/linear/server/tasks/UploadLinearWorkspaceLogoTask.ts
server/queues/tasks/UploadLinearWorkspaceLogoTask.ts
server/storage/files/BaseStorage.ts

fix: Store Linear workspace logo in storage

---

plugins/slack/server/api/hooks.ts
server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts
server/routes/api/documents/documents.ts

Boost recently updated documents in search results

Add recency boost to search results

---

plugins/slack/server/api/hooks.ts
server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts
server/routes/api/documents/documents.ts

Revert "Add recency boost to search results"

---

plugins/linear/server/api/linear.ts

fix: Store Linear workspace logo only when it's available

---

plugins/github/server/api/github.ts
plugins/linear/server/api/linear.ts
plugins/notion/server/api/notion.ts
plugins/slack/server/auth/slack.ts
server/middlewares/apexAuthRedirect.ts

Extract subdomain auth redirect

---

server/services/websockets.ts

If the websocket connection comes from anywhere other than the client we can drop the connection immediately. This is a defense in depth measure.

fix: Prevent cross-domain websocket connections to on-premise instances

---

app/models/Document.ts
app/scenes/Document/components/References.tsx
app/stores/DocumentsStore.ts

fix: Backlinks should be ordered alphabetically

---

app/actions/definitions/teams.tsx
app/components/PaginatedList.tsx
app/components/Sidebar/App.tsx
app/hooks/useLoggedInSessions.ts
app/hooks/useRequest.ts
app/menus/TeamMenu.tsx
app/routes/authenticated.tsx
app/routes/index.tsx
app/scenes/Login/Login.tsx
app/scenes/Login/OAuthAuthorize.tsx
app/scenes/Login/components/BackButton.tsx
app/scenes/Login/components/ConnectHeader.tsx
app/scenes/Login/components/TeamSwitcher.tsx
plugins/github/server/api/github.ts
plugins/linear/server/api/linear.ts
plugins/linear/shared/LinearUtils.ts
plugins/notion/server/api/notion.ts
plugins/slack/server/api/hooks.ts
plugins/slack/server/auth/slack.ts
server/middlewares/apexAuthRedirect.ts
server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts
server/routes/api/documents/documents.ts
shared/i18n/locales/en_US/translation.json

Due to multi-subdomains extra changes are needed for the authorize flow in cloud

OAuth server cloud compatibility

---

app/components/Collection/CollectionForm.tsx

Related https://github.com/outline/outline/discussions/9126

Pick collection color based on existing collections

---

shared/editor/commands/table.ts
shared/editor/nodes/Math.ts
shared/editor/nodes/Table.ts

fix: Improve behavior when hitting backspace/delete with table cell selections

---

shared/editor/queries/table.ts

fix: Non user-facing JS error

---

server/migrations/20250327062414-resolve-collection-index-collisions.js
server/scripts/20250327062414-resolve-collection-index-collisions.ts

Add script to resolve existing collection index collisions

---

server/models/Document.ts
server/models/helpers/SearchHelper.ts
server/routes/api/documents/documents.ts
server/routes/api/groupMemberships/groupMemberships.ts

fix: Chained scopes overwrite

---

shared/editor/components/Styles.ts

fix: LaTeX blocks show vertical scrollbar

---

app/stores/DocumentsStore.ts

fix: Backlinks are limited at 25

---

app/components/Sidebar/Settings.tsx
app/hooks/useEmbeds.ts
app/hooks/useSettingsConfig.ts
app/scenes/Settings/Integrations.tsx
app/scenes/Settings/components/IntegrationCard.tsx
app/stores/IntegrationsStore.ts
plugins/googleanalytics/client/Settings.tsx
plugins/matomo/client/Settings.tsx
plugins/slack/client/Settings.tsx
plugins/umami/client/Settings.tsx

Other minor refactors and removal of duplicate data loading

fix: Non-integration plugins missing in settings

---

server/utils/ZipHelper.ts

Related https://github.com/outline/outline/discussions/5450

fix: Various cases that could leave file handles open on export

---

.github/workflows/auto_close_prs.yml

Fed up of dealing with this manually, time to automate

chore: Add automation to close PRs that never accept CLA

---

server/models/helpers/ProsemirrorHelper.tsx

fix: Add encoding meta tag to exported HTML

---

plugins/slack/server/auth/slack.ts
server/commands/documentLoader.ts
server/commands/documentMover.ts
server/models/Collection.ts
server/models/Document.ts
server/policies/collection.test.ts
server/queues/processors/WebsocketsProcessor.ts
server/queues/tasks/CollectionSubscriptionRemoveUserTask.ts
server/routes/api/collections/collections.ts
server/routes/api/comments/comments.ts
server/routes/api/documents/documents.ts
server/routes/api/events/events.ts
server/routes/api/pins/pins.ts
server/routes/api/shares/shares.ts
server/routes/api/stars/stars.ts
server/routes/api/subscriptions/subscriptions.ts
server/services/websockets.ts
server/test/factories.ts

perf: Normalize `Collection.findByPk`

---

app/components/IconPicker/index.tsx
app/scenes/Collection/index.tsx

fix: Icon on collection home does not match sidebar when private

---

server/middlewares/apexAuthRedirect.ts

Strict attribute access exposed an issue here but it was silently caught and not logged

fix: Apex redirect regression

---

app/scenes/KeyboardShortcuts.tsx

Add new markdown shortcut for tables to shortcut UI

---

server/queues/tasks/CleanupDeletedDocumentsTask.ts

fix: `CleanupDeletedDocumentsTask` attribute selection

---

server/emails/templates/CollectionCreatedEmail.tsx
server/models/Collection.ts

fix: Ensure collection `withUser` scope is not overriden

---

app/components/Sidebar/components/Collections.tsx

fix: Consider active collections only for index computation

---

server/models/Collection.ts
server/routes/api/collections/collections.test.ts
server/routes/api/collections/collections.ts

Resolve index collision when restoring collection

---

app/components/ContextMenu/Template.tsx
app/hooks/useTemplateMenuItems.tsx
app/menus/DocumentMenu.tsx
app/menus/TemplatesMenu.tsx
app/scenes/Document/components/Document.tsx
app/scenes/Document/components/Header.tsx
shared/i18n/locales/en_US/translation.json

Adds menu option to apply template to existing document

---

server/storage/files/LocalStorage.ts

Add additional logging to `getFileStream` failures

---

server/validation.ts

This will help us get to the bottom of some Notion importer failures which are just being logged as `ValidationError`

chore: Add additional details to validation errors

---

server/queues/processors/ImportsProcessor.ts

fix: Guard all import tasks being filtered out

---

app/components/Avatar/Avatar.tsx
app/components/Avatar/index.ts
app/components/Notifications/NotificationListItem.tsx

fix: Initial avatars in notification popover malformed

---

app/editor/extensions/BlockMenu.tsx
shared/editor/nodes/Doc.ts
shared/editor/plugins/PlaceholderPlugin.ts

Adds some perf improvements to placeholders plugin - because it must be recalculated on selection change this only really helps with remote changes

perf: Utilize plugin state in placeholder plugin

---

app/components/ContextMenu/Template.tsx
app/hooks/useMenuContext.tsx
app/hooks/useMenuState.tsx

Regressed in #9298 - obvious in hindsight

fix: Submenus no longer work in dev

---

server/scripts/20250327062414-resolve-collection-index-collisions.ts

fix: First time migration fails

---

app/components/WebsocketProvider.tsx

fix: invalidate stale policy only

---

plugins/github/server/github.ts
plugins/linear/server/linear.ts
server/presenters/unfurl.ts
server/types.ts

chore: Cleanup unfurl temporary backward compatibility

---

shared/editor/nodes/HardBreak.ts

fix: Use br tag for breaks inside tables

---

server/queues/tasks/ImportTask.ts

fix: Persist document icon & color in import flow

---

plugins/linear/client/Settings.tsx
plugins/linear/server/api/linear.ts
plugins/linear/server/linear.ts
shared/i18n/locales/en_US/translation.json

Check for error response from Linear OAuth API.
Related #9417

Handle OAuth error in Linear callback

---

server/routes/api/collections/collections.test.ts
server/routes/api/collections/collections.ts

fix: Memberships loaded for incorrect user in collection add_user/remove_user

---

app/actions/definitions/documents.tsx
app/components/SearchActions.ts

fix: All documents should show in CMD+K when searching by title

---

shared/editor/lib/FileHelper.ts

fix: PNG without dimension data should fallback to async loading

---

plugins/notion/server/notion.ts

Added handling of timed out requests during Notion import. Seems to happen quite a lot 😬

fix: Notion API timed out during import

---

server/utils/turndown/sanitizeLists.ts
server/utils/turndown/tables.ts
shared/i18n/locales/en_US/translation.json

fix: Various fixes for HTML -> Markdown conversion

---

server/commands/documentImporter.ts
server/utils/DocumentConverter.ts

Fixed a check for the first line being a title

fix: Double title on import of some documents

---

app/actions/index.ts

fix: Navigate routes and links in kbar

---

shared/editor/components/Image.tsx

fix: Include image caption as alt attribute

---

app/components/Reactions/ReactionPicker.tsx
app/editor/components/FindAndReplace.tsx
app/scenes/ApiKeyNew/components/ExpiryDatePicker.tsx
app/scenes/Document/components/CommentThread.tsx
app/scenes/Document/components/CommentThreadItem.tsx
app/scenes/Document/components/Comments.tsx
plugins/slack/client/components/SlackListItem.tsx

With this, all components except SearchPopover have been migrated to use Radix popover.
I think SearchPopover will need a different primitive - something like a Combobox.
Towards #6456

Migrate remaining popovers to Radix

---

server/commands/documentCreator.test.ts
server/commands/documentCreator.ts

closes #9575
closes #9574
closes #9570

fix: JSON export->import loses content

---

app/components/ActionButton.tsx
app/scenes/Errors/Error404.tsx

fix: Buttons on not found page don't work

---

server/commands/teamUpdater.ts
server/queues/processors/CollectionsProcessor.ts
server/routes/api/collections/collections.ts
server/routes/api/teams/teams.ts

chore: Add event writing for team domain mutation

---

vite.config.ts

Revert "chore: Keep classnames in build"

---

package.json
server/env.ts
server/index.ts
server/services/collaboration.ts
server/storage/redis.ts
yarn.lock

Previously collaboration must be ran as a single thread, now you may optionally provide `REDIS_COLLABORATION_URL` to allow communication between multiple instances/processes.
closes #9280

feat: Allow horizontal scaling of collaboration service

---

app/components/Sidebar/components/SidebarButton.tsx
app/components/Sidebar/components/SidebarLink.tsx
app/editor/components/FloatingToolbar.tsx
shared/utils/browser.ts

fix: Double tap required in sidebar on iOS

---

server/middlewares/transaction.ts
server/storage/database.ts

It's better to be delayed a few hundred ms than error.
closes #9668

chore: Add exponential backoff / retry for deadlocks

---

server/models/View.test.ts
server/models/View.ts
server/routes/api/documents/documents.test.ts
server/routes/api/views/views.test.ts
server/routes/api/views/views.ts

chore: Convert View to event backend

---

app/models/decorators/Relation.ts

Unable to reproduce this locally, so adding additional logging
related #9680

chore: Add additional logging

---

server/models/AuthenticationProvider.ts
server/routes/api/authenticationProviders/authenticationProviders.ts
server/routes/api/integrations/integrations.ts

chore: `Integration` events to model layer

---

app/scenes/Document/components/Document.tsx

fix: Element overlaying last backlink

---

shared/editor/components/Frame.tsx

fix: Add additional allow properties for Frame

---

server/commands/documentImporter.test.ts
server/commands/documentImporter.ts

fix: Title content after period sometimes stripped in import

---

shared/editor/components/Styles.ts
shared/editor/marks/Code.ts
shared/editor/plugins/CodeWordDecorations.ts

fix: Wrap words in inline span to ensure correct break wrapping

---

app/components/Editor.tsx
app/editor/index.tsx
app/scenes/Document/components/Editor.tsx
shared/editor/components/Styles.ts

fix: Hide previous inline comments when disabled

---

server/models/helpers/SearchHelper.test.ts
server/models/helpers/SearchHelper.ts

fix: Documents accessible only through group memberships do not appear in search results

---

app/components/Sidebar/components/NavLink.tsx

Sidebar navigation feels punchier

perf: Restore fast-click functionality

---

app/components/Sidebar/components/NavLink.tsx

Regressed in https://github.com/outline/outline/pull/9733

fix: Cannot tap-scroll on mobile sidebar

---

server/utils/ImportHelper.test.ts
server/utils/ImportHelper.ts

Related https://github.com/outline/outline/issues/6273

fix: Improve importer to be more resilient to hidden directories

---

app/utils/urls.test.ts
app/utils/urls.ts

fix: Anchor with some UTF8 characters not correctly decoding

---

shared/editor/embeds/index.tsx

See https://github.com/outline/outline/issues/9765#issuecomment-3138907453

fix: Loosen Tella.tv embed regex

---

shared/editor/commands/table.ts

fix: Alignment not copied onto new table rows

---

app/routes/index.tsx
server/logging/sentry.ts
server/routes/api/notifications/notifications.ts
shared/editor/commands/table.ts
shared/editor/plugins/TableLayoutPlugin.ts

I added logging to make these more apparent in https://github.com/outline/outline/pull/9784, hence finding them now.

chore: More missing transactions

---

server/commands/shareLoader.ts
server/routes/api/shares/shares.ts

fix: Generate sitemap for shares with custom slugs

---

server/routes/api/documents/documents.ts
server/routes/api/shares/shares.ts
server/routes/app.ts
server/utils/passport.ts

Considered a couple of options, but this seems the most reasonable for now.
closes #9817
closes #9821

fix: Add option as to whether state cookie is considered for team context

---

app/scenes/Document/components/Document.tsx
shared/editor/components/Styles.ts

fix: Full-width nodes misaligned when ToC is open in full-width document

---

app/components/IconPicker/components/SkinTonePicker.tsx

Another one that was technically a menu, we gain a bit of nice animation here too with the switch
towards #6456

chore: Move `SkinTonePicker` to Radix popover

---

shared/styles/globals.ts

Fixes horizontal body shift upon opening/closing Lightbox #9704

Don't shift body horizontally when dialogs open

---

server/commands/teamCreator.ts
server/models/Collection.ts
server/models/Event.ts
server/models/User.ts
server/utils/authentication.ts

fix: Correct transaction usage through team creation process

---

server/env.ts
server/queues/tasks/ImportTask.ts
server/queues/tasks/UploadAttachmentsForImportTask.ts

Make configurable for edge cases. closes #9933

fix: Increase timeout on remote file storage operations

---

.sequelizerc
app/utils/routeHelpers.ts
plugins/github/shared/GitHubUtils.ts
plugins/linear/shared/LinearUtils.ts
plugins/notion/shared/NotionUtils.ts
plugins/slack/shared/SlackUtils.ts
plugins/webhooks/server/tasks/DeliverWebhookTask.ts
server/emails/templates/WebhookDisabledEmail.tsx
server/migrations/20250630175759-add-collection-id-to-shares.js

chore: Formatting

---

package.json
yarn.lock

Upgrade `vite-plugin-pwa`

---

server/middlewares/csp.ts

chore: More CSP hardening

---

app/utils/ApiClient.ts
plugins/storage/server/api/files.ts
server/middlewares/authentication.ts
server/routes/api/documents/documents.ts
server/routes/auth/index.ts

fix: Frontend requests do not send `Content-Type` header in request

---

.github/dependabot.yml

Dependabot group for radix-ui dependencies.

chore: Dependabot group for radix-ui

---

app/hooks/usePersistedState.ts

This PR fixes a bug where draft comments are not re-synced when navigating between documents.
It seems `usePersistedState` always had this bug but we didn't face this until a recent change that retained sidebar open state between navigation.

fix: Sync draft comment from local storage when navigating between documents

---

server/models/helpers/AuthenticationHelper.ts

Map export endpoint to read permissions

---

app/menus/DocumentMenu.tsx
server/queues/tasks/DocumentImportTask.ts
server/routes/api/documents/documents.test.ts
server/routes/api/documents/documents.ts
server/routes/api/documents/schema.ts

Aligns document import permission checks with creation flow.
Closes #9986

fix documents.import permission checks for shared parent

---

server/migrations/20250826204500-modify-shares-unique-constraint-with-revoked-condition.js

fix: Update unique db constraint to account for revoked share links

---

plugins/oidc/server/oidcDiscovery.ts
server/utils/fetch.ts

fix: Allow access to private IP address for OIDC

---

server/utils/oauth.ts

fix: Unable to access private OIDC server endpoints

---

app/components/EditableTitle.tsx

fix: Sidebar hidden editing outline

---

app/components/Sidebar/components/SidebarLink.tsx

fix: Truncation in sidebar links

---

server/models/Document.ts
server/models/Relationship.ts

perf: Improve perf of `findSourceDocumentIdsForUser`

---

app/editor/extensions/FindAndReplace.tsx

fix: False matches on wrap-around strings

---

app/components/Actions.ts
app/components/Header.tsx
app/components/Lightbox.tsx

Quick win, tidied some old styling

feat: Add additional copy link control to lightbox

---

package.json
shared/editor/nodes/TableCell.ts
shared/editor/queries/table.ts
yarn.lock

fix: Table row selection logic with merged cells

---

app/scenes/Shared/index.tsx

closes #10162
regressed in #9529

fix: Single shared doc uncentered

---

package.json
plugins/linear/server/api/linear.ts
plugins/linear/server/linear.ts
server/commands/accountProvisioner.ts
server/models/IntegrationAuthentication.ts
shared/utils/time.ts
yarn.lock

closes #10032
ref https://linear.app/developers/oauth-2-0-authentication#refresh-an-access-token

chore: Store refresh tokens for Linear integration

---

app/hooks/useBuildTheme.ts
app/index.tsx

This is particularly handy for embedding content elsewhere

feat: Allow theme override with query string

---

app/editor/components/SelectionToolbar.tsx

feat: Restore 'Copy' button on public code blocks

---

app/components/Lightbox.tsx
app/hooks/useSwipe.tsx
package.json
shared/i18n/locales/en_US/translation.json
yarn.lock

Pan & Zoom
